// Code generated by protoc-gen-go. DO NOT EDIT.
// source: vega/commands/v1/commands.proto

package v1

import (
	vega "code.vegaprotocol.io/protos/vega"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	_ "github.com/mwitkow/go-proto-validators"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UndelegateSubmission_Method int32

const (
	UndelegateSubmission_METHOD_UNSPECIFIED     UndelegateSubmission_Method = 0
	UndelegateSubmission_METHOD_NOW             UndelegateSubmission_Method = 1
	UndelegateSubmission_METHOD_AT_END_OF_EPOCH UndelegateSubmission_Method = 2
	UndelegateSubmission_METHOD_IN_ANGER        UndelegateSubmission_Method = 3
)

var UndelegateSubmission_Method_name = map[int32]string{
	0: "METHOD_UNSPECIFIED",
	1: "METHOD_NOW",
	2: "METHOD_AT_END_OF_EPOCH",
	3: "METHOD_IN_ANGER",
}

var UndelegateSubmission_Method_value = map[string]int32{
	"METHOD_UNSPECIFIED":     0,
	"METHOD_NOW":             1,
	"METHOD_AT_END_OF_EPOCH": 2,
	"METHOD_IN_ANGER":        3,
}

func (x UndelegateSubmission_Method) String() string {
	return proto.EnumName(UndelegateSubmission_Method_name, int32(x))
}

func (UndelegateSubmission_Method) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_9c3a53c66a940c51, []int{10, 0}
}

// An order submission is a request to submit or create a new order on Vega
type OrderSubmission struct {
	// Market identifier for the order, required field
	MarketId string `protobuf:"bytes,1,opt,name=market_id,json=marketId,proto3" json:"market_id,omitempty"`
	// Price for the order, the price is an integer, for example `123456` is a correctly
	// formatted price of `1.23456` assuming market configured to 5 decimal places,
	// , required field for limit orders, however it is not required for market orders
	Price string `protobuf:"bytes,2,opt,name=price,proto3" json:"price,omitempty"`
	// Size for the order, for example, in a futures market the size equals the number of contracts, cannot be negative
	Size uint64 `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	// Side for the order, e.g. SIDE_BUY or SIDE_SELL, required field - See [`Side`](#vega.Side)
	Side vega.Side `protobuf:"varint,4,opt,name=side,proto3,enum=vega.Side" json:"side,omitempty"`
	// Time in force indicates how long an order will remain active before it is executed or expires, required field
	// - See [`Order.TimeInForce`](#vega.Order.TimeInForce)
	TimeInForce vega.Order_TimeInForce `protobuf:"varint,5,opt,name=time_in_force,json=timeInForce,proto3,enum=vega.Order_TimeInForce" json:"time_in_force,omitempty"`
	// Timestamp for when the order will expire, in nanoseconds since the epoch,
	// required field only for [`Order.TimeInForce`](#vega.Order.TimeInForce)`.TIME_IN_FORCE_GTT`
	// - See [`VegaTimeResponse`](#api.VegaTimeResponse).`timestamp`
	ExpiresAt int64 `protobuf:"varint,6,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	// Type for the order, required field - See [`Order.Type`](#vega.Order.Type)
	Type vega.Order_Type `protobuf:"varint,7,opt,name=type,proto3,enum=vega.Order_Type" json:"type,omitempty"`
	// Reference given for the order, this is typically used to retrieve an order submitted through consensus, currently
	// set internally by the node to return a unique reference identifier for the order submission
	Reference string `protobuf:"bytes,8,opt,name=reference,proto3" json:"reference,omitempty"`
	// Used to specify the details for a pegged order
	// - See [`PeggedOrder`](#vega.PeggedOrder)
	PeggedOrder          *vega.PeggedOrder `protobuf:"bytes,9,opt,name=pegged_order,json=peggedOrder,proto3" json:"pegged_order,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *OrderSubmission) Reset()         { *m = OrderSubmission{} }
func (m *OrderSubmission) String() string { return proto.CompactTextString(m) }
func (*OrderSubmission) ProtoMessage()    {}
func (*OrderSubmission) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c3a53c66a940c51, []int{0}
}

func (m *OrderSubmission) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderSubmission.Unmarshal(m, b)
}
func (m *OrderSubmission) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderSubmission.Marshal(b, m, deterministic)
}
func (m *OrderSubmission) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderSubmission.Merge(m, src)
}
func (m *OrderSubmission) XXX_Size() int {
	return xxx_messageInfo_OrderSubmission.Size(m)
}
func (m *OrderSubmission) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderSubmission.DiscardUnknown(m)
}

var xxx_messageInfo_OrderSubmission proto.InternalMessageInfo

func (m *OrderSubmission) GetMarketId() string {
	if m != nil {
		return m.MarketId
	}
	return ""
}

func (m *OrderSubmission) GetPrice() string {
	if m != nil {
		return m.Price
	}
	return ""
}

func (m *OrderSubmission) GetSize() uint64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *OrderSubmission) GetSide() vega.Side {
	if m != nil {
		return m.Side
	}
	return vega.Side_SIDE_UNSPECIFIED
}

func (m *OrderSubmission) GetTimeInForce() vega.Order_TimeInForce {
	if m != nil {
		return m.TimeInForce
	}
	return vega.Order_TIME_IN_FORCE_UNSPECIFIED
}

func (m *OrderSubmission) GetExpiresAt() int64 {
	if m != nil {
		return m.ExpiresAt
	}
	return 0
}

func (m *OrderSubmission) GetType() vega.Order_Type {
	if m != nil {
		return m.Type
	}
	return vega.Order_TYPE_UNSPECIFIED
}

func (m *OrderSubmission) GetReference() string {
	if m != nil {
		return m.Reference
	}
	return ""
}

func (m *OrderSubmission) GetPeggedOrder() *vega.PeggedOrder {
	if m != nil {
		return m.PeggedOrder
	}
	return nil
}

// An order cancellation is a request to cancel an existing order on Vega
type OrderCancellation struct {
	// Unique identifier for the order (set by the system after consensus), required field
	OrderId string `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	// Market identifier for the order, required field
	MarketId             string   `protobuf:"bytes,2,opt,name=market_id,json=marketId,proto3" json:"market_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrderCancellation) Reset()         { *m = OrderCancellation{} }
func (m *OrderCancellation) String() string { return proto.CompactTextString(m) }
func (*OrderCancellation) ProtoMessage()    {}
func (*OrderCancellation) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c3a53c66a940c51, []int{1}
}

func (m *OrderCancellation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderCancellation.Unmarshal(m, b)
}
func (m *OrderCancellation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderCancellation.Marshal(b, m, deterministic)
}
func (m *OrderCancellation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderCancellation.Merge(m, src)
}
func (m *OrderCancellation) XXX_Size() int {
	return xxx_messageInfo_OrderCancellation.Size(m)
}
func (m *OrderCancellation) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderCancellation.DiscardUnknown(m)
}

var xxx_messageInfo_OrderCancellation proto.InternalMessageInfo

func (m *OrderCancellation) GetOrderId() string {
	if m != nil {
		return m.OrderId
	}
	return ""
}

func (m *OrderCancellation) GetMarketId() string {
	if m != nil {
		return m.MarketId
	}
	return ""
}

// An order amendment is a request to amend or update an existing order on Vega
type OrderAmendment struct {
	// Order identifier, this is required to find the order and will not be updated, required field
	OrderId string `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	// Market identifier, this is required to find the order and will not be updated
	MarketId string `protobuf:"bytes,2,opt,name=market_id,json=marketId,proto3" json:"market_id,omitempty"`
	// Amend the price for the order, if the Price value is set, otherwise price will remain unchanged - See [`Price`](#vega.Price)
	Price *vega.Price `protobuf:"bytes,3,opt,name=price,proto3" json:"price,omitempty"`
	// Amend the size for the order by the delta specified:
	// - To reduce the size from the current value set a negative integer value
	// - To increase the size from the current value, set a positive integer value
	// - To leave the size unchanged set a value of zero
	SizeDelta int64 `protobuf:"varint,4,opt,name=size_delta,json=sizeDelta,proto3" json:"size_delta,omitempty"`
	// Amend the expiry time for the order, if the Timestamp value is set, otherwise expiry time will remain unchanged
	// - See [`VegaTimeResponse`](#api.VegaTimeResponse).`timestamp`
	ExpiresAt *vega.Timestamp `protobuf:"bytes,5,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	// Amend the time in force for the order, set to TIME_IN_FORCE_UNSPECIFIED to remain unchanged
	// - See [`TimeInForce`](#api.VegaTimeResponse).`timestamp`
	TimeInForce vega.Order_TimeInForce `protobuf:"varint,6,opt,name=time_in_force,json=timeInForce,proto3,enum=vega.Order_TimeInForce" json:"time_in_force,omitempty"`
	// Amend the pegged order offset for the order
	PeggedOffset *wrappers.Int64Value `protobuf:"bytes,7,opt,name=pegged_offset,json=peggedOffset,proto3" json:"pegged_offset,omitempty"`
	// Amend the pegged order reference for the order
	// - See [`PeggedReference`](#vega.PeggedReference)
	PeggedReference      vega.PeggedReference `protobuf:"varint,8,opt,name=pegged_reference,json=peggedReference,proto3,enum=vega.PeggedReference" json:"pegged_reference,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *OrderAmendment) Reset()         { *m = OrderAmendment{} }
func (m *OrderAmendment) String() string { return proto.CompactTextString(m) }
func (*OrderAmendment) ProtoMessage()    {}
func (*OrderAmendment) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c3a53c66a940c51, []int{2}
}

func (m *OrderAmendment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderAmendment.Unmarshal(m, b)
}
func (m *OrderAmendment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderAmendment.Marshal(b, m, deterministic)
}
func (m *OrderAmendment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderAmendment.Merge(m, src)
}
func (m *OrderAmendment) XXX_Size() int {
	return xxx_messageInfo_OrderAmendment.Size(m)
}
func (m *OrderAmendment) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderAmendment.DiscardUnknown(m)
}

var xxx_messageInfo_OrderAmendment proto.InternalMessageInfo

func (m *OrderAmendment) GetOrderId() string {
	if m != nil {
		return m.OrderId
	}
	return ""
}

func (m *OrderAmendment) GetMarketId() string {
	if m != nil {
		return m.MarketId
	}
	return ""
}

func (m *OrderAmendment) GetPrice() *vega.Price {
	if m != nil {
		return m.Price
	}
	return nil
}

func (m *OrderAmendment) GetSizeDelta() int64 {
	if m != nil {
		return m.SizeDelta
	}
	return 0
}

func (m *OrderAmendment) GetExpiresAt() *vega.Timestamp {
	if m != nil {
		return m.ExpiresAt
	}
	return nil
}

func (m *OrderAmendment) GetTimeInForce() vega.Order_TimeInForce {
	if m != nil {
		return m.TimeInForce
	}
	return vega.Order_TIME_IN_FORCE_UNSPECIFIED
}

func (m *OrderAmendment) GetPeggedOffset() *wrappers.Int64Value {
	if m != nil {
		return m.PeggedOffset
	}
	return nil
}

func (m *OrderAmendment) GetPeggedReference() vega.PeggedReference {
	if m != nil {
		return m.PeggedReference
	}
	return vega.PeggedReference_PEGGED_REFERENCE_UNSPECIFIED
}

// A liquidity provision submitted for a given market
type LiquidityProvisionSubmission struct {
	// Market identifier for the order, required field
	MarketId string `protobuf:"bytes,1,opt,name=market_id,json=marketId,proto3" json:"market_id,omitempty"`
	// Specified as a unitless number that represents the amount of settlement asset of the market
	CommitmentAmount string `protobuf:"bytes,2,opt,name=commitment_amount,json=commitmentAmount,proto3" json:"commitment_amount,omitempty"`
	// Nominated liquidity fee factor, which is an input to the calculation of taker fees on the market, as per seeting fees and rewarding liquidity providers
	Fee string `protobuf:"bytes,3,opt,name=fee,proto3" json:"fee,omitempty"`
	// A set of liquidity sell orders to meet the liquidity provision obligation
	Sells []*vega.LiquidityOrder `protobuf:"bytes,4,rep,name=sells,proto3" json:"sells,omitempty"`
	// A set of liquidity buy orders to meet the liquidity provision obligation
	Buys []*vega.LiquidityOrder `protobuf:"bytes,5,rep,name=buys,proto3" json:"buys,omitempty"`
	// A reference to be added to every order created out of this liquidityProvisionSubmission
	Reference            string   `protobuf:"bytes,6,opt,name=reference,proto3" json:"reference,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LiquidityProvisionSubmission) Reset()         { *m = LiquidityProvisionSubmission{} }
func (m *LiquidityProvisionSubmission) String() string { return proto.CompactTextString(m) }
func (*LiquidityProvisionSubmission) ProtoMessage()    {}
func (*LiquidityProvisionSubmission) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c3a53c66a940c51, []int{3}
}

func (m *LiquidityProvisionSubmission) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LiquidityProvisionSubmission.Unmarshal(m, b)
}
func (m *LiquidityProvisionSubmission) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LiquidityProvisionSubmission.Marshal(b, m, deterministic)
}
func (m *LiquidityProvisionSubmission) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LiquidityProvisionSubmission.Merge(m, src)
}
func (m *LiquidityProvisionSubmission) XXX_Size() int {
	return xxx_messageInfo_LiquidityProvisionSubmission.Size(m)
}
func (m *LiquidityProvisionSubmission) XXX_DiscardUnknown() {
	xxx_messageInfo_LiquidityProvisionSubmission.DiscardUnknown(m)
}

var xxx_messageInfo_LiquidityProvisionSubmission proto.InternalMessageInfo

func (m *LiquidityProvisionSubmission) GetMarketId() string {
	if m != nil {
		return m.MarketId
	}
	return ""
}

func (m *LiquidityProvisionSubmission) GetCommitmentAmount() string {
	if m != nil {
		return m.CommitmentAmount
	}
	return ""
}

func (m *LiquidityProvisionSubmission) GetFee() string {
	if m != nil {
		return m.Fee
	}
	return ""
}

func (m *LiquidityProvisionSubmission) GetSells() []*vega.LiquidityOrder {
	if m != nil {
		return m.Sells
	}
	return nil
}

func (m *LiquidityProvisionSubmission) GetBuys() []*vega.LiquidityOrder {
	if m != nil {
		return m.Buys
	}
	return nil
}

func (m *LiquidityProvisionSubmission) GetReference() string {
	if m != nil {
		return m.Reference
	}
	return ""
}

// Request a cancellation of liquidity provision
type LiquidityProvisionCancellation struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	MarketId             string   `protobuf:"bytes,2,opt,name=market_id,json=marketId,proto3" json:"market_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LiquidityProvisionCancellation) Reset()         { *m = LiquidityProvisionCancellation{} }
func (m *LiquidityProvisionCancellation) String() string { return proto.CompactTextString(m) }
func (*LiquidityProvisionCancellation) ProtoMessage()    {}
func (*LiquidityProvisionCancellation) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c3a53c66a940c51, []int{4}
}

func (m *LiquidityProvisionCancellation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LiquidityProvisionCancellation.Unmarshal(m, b)
}
func (m *LiquidityProvisionCancellation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LiquidityProvisionCancellation.Marshal(b, m, deterministic)
}
func (m *LiquidityProvisionCancellation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LiquidityProvisionCancellation.Merge(m, src)
}
func (m *LiquidityProvisionCancellation) XXX_Size() int {
	return xxx_messageInfo_LiquidityProvisionCancellation.Size(m)
}
func (m *LiquidityProvisionCancellation) XXX_DiscardUnknown() {
	xxx_messageInfo_LiquidityProvisionCancellation.DiscardUnknown(m)
}

var xxx_messageInfo_LiquidityProvisionCancellation proto.InternalMessageInfo

func (m *LiquidityProvisionCancellation) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *LiquidityProvisionCancellation) GetMarketId() string {
	if m != nil {
		return m.MarketId
	}
	return ""
}

// Request an amendment to a liquidity provision request
type LiquidityProvisionAmendment struct {
	Id       string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	MarketId string `protobuf:"bytes,2,opt,name=market_id,json=marketId,proto3" json:"market_id,omitempty"`
	// From here at least one of the following is required to consider the command valid
	CommitmentAmount     string                 `protobuf:"bytes,3,opt,name=commitment_amount,json=commitmentAmount,proto3" json:"commitment_amount,omitempty"`
	Fee                  string                 `protobuf:"bytes,4,opt,name=fee,proto3" json:"fee,omitempty"`
	Sells                []*vega.LiquidityOrder `protobuf:"bytes,5,rep,name=sells,proto3" json:"sells,omitempty"`
	Buys                 []*vega.LiquidityOrder `protobuf:"bytes,6,rep,name=buys,proto3" json:"buys,omitempty"`
	Reference            string                 `protobuf:"bytes,7,opt,name=reference,proto3" json:"reference,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *LiquidityProvisionAmendment) Reset()         { *m = LiquidityProvisionAmendment{} }
func (m *LiquidityProvisionAmendment) String() string { return proto.CompactTextString(m) }
func (*LiquidityProvisionAmendment) ProtoMessage()    {}
func (*LiquidityProvisionAmendment) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c3a53c66a940c51, []int{5}
}

func (m *LiquidityProvisionAmendment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LiquidityProvisionAmendment.Unmarshal(m, b)
}
func (m *LiquidityProvisionAmendment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LiquidityProvisionAmendment.Marshal(b, m, deterministic)
}
func (m *LiquidityProvisionAmendment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LiquidityProvisionAmendment.Merge(m, src)
}
func (m *LiquidityProvisionAmendment) XXX_Size() int {
	return xxx_messageInfo_LiquidityProvisionAmendment.Size(m)
}
func (m *LiquidityProvisionAmendment) XXX_DiscardUnknown() {
	xxx_messageInfo_LiquidityProvisionAmendment.DiscardUnknown(m)
}

var xxx_messageInfo_LiquidityProvisionAmendment proto.InternalMessageInfo

func (m *LiquidityProvisionAmendment) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *LiquidityProvisionAmendment) GetMarketId() string {
	if m != nil {
		return m.MarketId
	}
	return ""
}

func (m *LiquidityProvisionAmendment) GetCommitmentAmount() string {
	if m != nil {
		return m.CommitmentAmount
	}
	return ""
}

func (m *LiquidityProvisionAmendment) GetFee() string {
	if m != nil {
		return m.Fee
	}
	return ""
}

func (m *LiquidityProvisionAmendment) GetSells() []*vega.LiquidityOrder {
	if m != nil {
		return m.Sells
	}
	return nil
}

func (m *LiquidityProvisionAmendment) GetBuys() []*vega.LiquidityOrder {
	if m != nil {
		return m.Buys
	}
	return nil
}

func (m *LiquidityProvisionAmendment) GetReference() string {
	if m != nil {
		return m.Reference
	}
	return ""
}

// Represents the submission request to withdraw funds for a party on Vega
type WithdrawSubmission struct {
	// The amount to be withdrawn
	Amount string `protobuf:"bytes,1,opt,name=amount,proto3" json:"amount,omitempty"`
	// The asset we want to withdraw
	Asset string `protobuf:"bytes,2,opt,name=asset,proto3" json:"asset,omitempty"`
	// Foreign chain specifics
	Ext                  *vega.WithdrawExt `protobuf:"bytes,3,opt,name=ext,proto3" json:"ext,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *WithdrawSubmission) Reset()         { *m = WithdrawSubmission{} }
func (m *WithdrawSubmission) String() string { return proto.CompactTextString(m) }
func (*WithdrawSubmission) ProtoMessage()    {}
func (*WithdrawSubmission) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c3a53c66a940c51, []int{6}
}

func (m *WithdrawSubmission) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WithdrawSubmission.Unmarshal(m, b)
}
func (m *WithdrawSubmission) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WithdrawSubmission.Marshal(b, m, deterministic)
}
func (m *WithdrawSubmission) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WithdrawSubmission.Merge(m, src)
}
func (m *WithdrawSubmission) XXX_Size() int {
	return xxx_messageInfo_WithdrawSubmission.Size(m)
}
func (m *WithdrawSubmission) XXX_DiscardUnknown() {
	xxx_messageInfo_WithdrawSubmission.DiscardUnknown(m)
}

var xxx_messageInfo_WithdrawSubmission proto.InternalMessageInfo

func (m *WithdrawSubmission) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

func (m *WithdrawSubmission) GetAsset() string {
	if m != nil {
		return m.Asset
	}
	return ""
}

func (m *WithdrawSubmission) GetExt() *vega.WithdrawExt {
	if m != nil {
		return m.Ext
	}
	return nil
}

// A command to submit a new proposal for the
// vega network governance
type ProposalSubmission struct {
	// Proposal reference
	Reference string `protobuf:"bytes,1,opt,name=reference,proto3" json:"reference,omitempty"`
	// Proposal configuration and the actual change that is meant to be executed when proposal is enacted
	Terms                *vega.ProposalTerms `protobuf:"bytes,2,opt,name=terms,proto3" json:"terms,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *ProposalSubmission) Reset()         { *m = ProposalSubmission{} }
func (m *ProposalSubmission) String() string { return proto.CompactTextString(m) }
func (*ProposalSubmission) ProtoMessage()    {}
func (*ProposalSubmission) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c3a53c66a940c51, []int{7}
}

func (m *ProposalSubmission) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProposalSubmission.Unmarshal(m, b)
}
func (m *ProposalSubmission) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProposalSubmission.Marshal(b, m, deterministic)
}
func (m *ProposalSubmission) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProposalSubmission.Merge(m, src)
}
func (m *ProposalSubmission) XXX_Size() int {
	return xxx_messageInfo_ProposalSubmission.Size(m)
}
func (m *ProposalSubmission) XXX_DiscardUnknown() {
	xxx_messageInfo_ProposalSubmission.DiscardUnknown(m)
}

var xxx_messageInfo_ProposalSubmission proto.InternalMessageInfo

func (m *ProposalSubmission) GetReference() string {
	if m != nil {
		return m.Reference
	}
	return ""
}

func (m *ProposalSubmission) GetTerms() *vega.ProposalTerms {
	if m != nil {
		return m.Terms
	}
	return nil
}

// A command to submit a new vote for a governance
// proposal.
type VoteSubmission struct {
	// The ID of the proposal to vote for.
	ProposalId string `protobuf:"bytes,1,opt,name=proposal_id,json=proposalId,proto3" json:"proposal_id,omitempty"`
	// The actual value of the vote
	Value                vega.Vote_Value `protobuf:"varint,2,opt,name=value,proto3,enum=vega.Vote_Value" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *VoteSubmission) Reset()         { *m = VoteSubmission{} }
func (m *VoteSubmission) String() string { return proto.CompactTextString(m) }
func (*VoteSubmission) ProtoMessage()    {}
func (*VoteSubmission) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c3a53c66a940c51, []int{8}
}

func (m *VoteSubmission) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VoteSubmission.Unmarshal(m, b)
}
func (m *VoteSubmission) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VoteSubmission.Marshal(b, m, deterministic)
}
func (m *VoteSubmission) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VoteSubmission.Merge(m, src)
}
func (m *VoteSubmission) XXX_Size() int {
	return xxx_messageInfo_VoteSubmission.Size(m)
}
func (m *VoteSubmission) XXX_DiscardUnknown() {
	xxx_messageInfo_VoteSubmission.DiscardUnknown(m)
}

var xxx_messageInfo_VoteSubmission proto.InternalMessageInfo

func (m *VoteSubmission) GetProposalId() string {
	if m != nil {
		return m.ProposalId
	}
	return ""
}

func (m *VoteSubmission) GetValue() vega.Vote_Value {
	if m != nil {
		return m.Value
	}
	return vega.Vote_VALUE_UNSPECIFIED
}

// A command to submit an instruction to delegate some stake to a node
type DelegateSubmission struct {
	// The ID for the node to delegate to
	NodeId string `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	// The amount of stake to delegate
	Amount               string   `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DelegateSubmission) Reset()         { *m = DelegateSubmission{} }
func (m *DelegateSubmission) String() string { return proto.CompactTextString(m) }
func (*DelegateSubmission) ProtoMessage()    {}
func (*DelegateSubmission) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c3a53c66a940c51, []int{9}
}

func (m *DelegateSubmission) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DelegateSubmission.Unmarshal(m, b)
}
func (m *DelegateSubmission) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DelegateSubmission.Marshal(b, m, deterministic)
}
func (m *DelegateSubmission) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DelegateSubmission.Merge(m, src)
}
func (m *DelegateSubmission) XXX_Size() int {
	return xxx_messageInfo_DelegateSubmission.Size(m)
}
func (m *DelegateSubmission) XXX_DiscardUnknown() {
	xxx_messageInfo_DelegateSubmission.DiscardUnknown(m)
}

var xxx_messageInfo_DelegateSubmission proto.InternalMessageInfo

func (m *DelegateSubmission) GetNodeId() string {
	if m != nil {
		return m.NodeId
	}
	return ""
}

func (m *DelegateSubmission) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

type UndelegateSubmission struct {
	NodeId string `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	// optional, if not specified = ALL
	Amount               string                      `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Method               UndelegateSubmission_Method `protobuf:"varint,3,opt,name=method,proto3,enum=vega.commands.v1.UndelegateSubmission_Method" json:"method,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *UndelegateSubmission) Reset()         { *m = UndelegateSubmission{} }
func (m *UndelegateSubmission) String() string { return proto.CompactTextString(m) }
func (*UndelegateSubmission) ProtoMessage()    {}
func (*UndelegateSubmission) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c3a53c66a940c51, []int{10}
}

func (m *UndelegateSubmission) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UndelegateSubmission.Unmarshal(m, b)
}
func (m *UndelegateSubmission) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UndelegateSubmission.Marshal(b, m, deterministic)
}
func (m *UndelegateSubmission) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UndelegateSubmission.Merge(m, src)
}
func (m *UndelegateSubmission) XXX_Size() int {
	return xxx_messageInfo_UndelegateSubmission.Size(m)
}
func (m *UndelegateSubmission) XXX_DiscardUnknown() {
	xxx_messageInfo_UndelegateSubmission.DiscardUnknown(m)
}

var xxx_messageInfo_UndelegateSubmission proto.InternalMessageInfo

func (m *UndelegateSubmission) GetNodeId() string {
	if m != nil {
		return m.NodeId
	}
	return ""
}

func (m *UndelegateSubmission) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

func (m *UndelegateSubmission) GetMethod() UndelegateSubmission_Method {
	if m != nil {
		return m.Method
	}
	return UndelegateSubmission_METHOD_UNSPECIFIED
}

// A command that loads the state from a given checkpoint
type RestoreSnapshot struct {
	Data                 []byte   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RestoreSnapshot) Reset()         { *m = RestoreSnapshot{} }
func (m *RestoreSnapshot) String() string { return proto.CompactTextString(m) }
func (*RestoreSnapshot) ProtoMessage()    {}
func (*RestoreSnapshot) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c3a53c66a940c51, []int{11}
}

func (m *RestoreSnapshot) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RestoreSnapshot.Unmarshal(m, b)
}
func (m *RestoreSnapshot) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RestoreSnapshot.Marshal(b, m, deterministic)
}
func (m *RestoreSnapshot) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RestoreSnapshot.Merge(m, src)
}
func (m *RestoreSnapshot) XXX_Size() int {
	return xxx_messageInfo_RestoreSnapshot.Size(m)
}
func (m *RestoreSnapshot) XXX_DiscardUnknown() {
	xxx_messageInfo_RestoreSnapshot.DiscardUnknown(m)
}

var xxx_messageInfo_RestoreSnapshot proto.InternalMessageInfo

func (m *RestoreSnapshot) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterEnum("vega.commands.v1.UndelegateSubmission_Method", UndelegateSubmission_Method_name, UndelegateSubmission_Method_value)
	proto.RegisterType((*OrderSubmission)(nil), "vega.commands.v1.OrderSubmission")
	proto.RegisterType((*OrderCancellation)(nil), "vega.commands.v1.OrderCancellation")
	proto.RegisterType((*OrderAmendment)(nil), "vega.commands.v1.OrderAmendment")
	proto.RegisterType((*LiquidityProvisionSubmission)(nil), "vega.commands.v1.LiquidityProvisionSubmission")
	proto.RegisterType((*LiquidityProvisionCancellation)(nil), "vega.commands.v1.LiquidityProvisionCancellation")
	proto.RegisterType((*LiquidityProvisionAmendment)(nil), "vega.commands.v1.LiquidityProvisionAmendment")
	proto.RegisterType((*WithdrawSubmission)(nil), "vega.commands.v1.WithdrawSubmission")
	proto.RegisterType((*ProposalSubmission)(nil), "vega.commands.v1.ProposalSubmission")
	proto.RegisterType((*VoteSubmission)(nil), "vega.commands.v1.VoteSubmission")
	proto.RegisterType((*DelegateSubmission)(nil), "vega.commands.v1.DelegateSubmission")
	proto.RegisterType((*UndelegateSubmission)(nil), "vega.commands.v1.UndelegateSubmission")
	proto.RegisterType((*RestoreSnapshot)(nil), "vega.commands.v1.RestoreSnapshot")
}

func init() { proto.RegisterFile("vega/commands/v1/commands.proto", fileDescriptor_9c3a53c66a940c51) }

var fileDescriptor_9c3a53c66a940c51 = []byte{
	// 996 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x56, 0xdd, 0x4f, 0x1b, 0x47,
	0x10, 0xcf, 0xf9, 0x0b, 0x3c, 0x4e, 0x6c, 0xb3, 0x21, 0xf4, 0x0a, 0x09, 0x38, 0x97, 0x7e, 0x58,
	0x6d, 0x39, 0x0b, 0x37, 0xca, 0x4b, 0x5f, 0x42, 0xc0, 0x34, 0x56, 0x0b, 0x46, 0x07, 0x49, 0xaa,
	0xbe, 0x9c, 0x16, 0xef, 0xd8, 0xac, 0x72, 0x77, 0x7b, 0xbd, 0x5b, 0x1b, 0xe8, 0x6b, 0xff, 0xcf,
	0x56, 0xea, 0x1f, 0x51, 0xa9, 0x0f, 0x95, 0xaa, 0xdd, 0x3d, 0x1b, 0xdb, 0xa0, 0x34, 0x48, 0x7d,
	0xdb, 0xf9, 0xfa, 0xed, 0xce, 0xfc, 0x66, 0xe6, 0x0e, 0xb6, 0xc6, 0x38, 0xa4, 0xad, 0xbe, 0x08,
	0x43, 0x1a, 0xb1, 0xb4, 0x35, 0xde, 0x99, 0x9e, 0xdd, 0x38, 0x11, 0x52, 0x90, 0xba, 0x72, 0x70,
	0xa7, 0xca, 0xf1, 0xce, 0xfa, 0x23, 0x1d, 0x32, 0x14, 0x63, 0x4c, 0x22, 0x1a, 0xf5, 0xd1, 0x38,
	0xae, 0xd7, 0xb4, 0x5a, 0x7b, 0x1b, 0xc5, 0xe6, 0x50, 0x88, 0x61, 0x80, 0x2d, 0x2d, 0x9d, 0x8d,
	0x06, 0xad, 0x8b, 0x84, 0xc6, 0x31, 0x26, 0x19, 0xf2, 0xfa, 0x8b, 0x21, 0x97, 0xe7, 0xa3, 0x33,
	0x85, 0xdd, 0x0a, 0x2f, 0xb8, 0x7c, 0x2f, 0x2e, 0x5a, 0x43, 0xb1, 0xad, 0x8d, 0xdb, 0x63, 0x1a,
	0x70, 0x46, 0xa5, 0x48, 0xd2, 0xd6, 0xf4, 0x68, 0xe2, 0x9c, 0xdf, 0x73, 0x50, 0xeb, 0x25, 0x0c,
	0x93, 0x93, 0xd1, 0x59, 0xc8, 0xd3, 0x94, 0x8b, 0x88, 0x3c, 0x83, 0x72, 0x48, 0x93, 0xf7, 0x28,
	0x7d, 0xce, 0x6c, 0xab, 0x61, 0x35, 0xcb, 0xaf, 0x4a, 0x7f, 0xfe, 0xb1, 0x95, 0xfb, 0xc9, 0xf2,
	0x96, 0x8d, 0xa1, 0xcb, 0xc8, 0x2a, 0x14, 0xe3, 0x84, 0xf7, 0xd1, 0xce, 0x29, 0x07, 0xcf, 0x08,
	0x64, 0x1d, 0x0a, 0x29, 0xff, 0x15, 0xed, 0x7c, 0xc3, 0x6a, 0x16, 0x4c, 0x54, 0xfd, 0x9e, 0xa7,
	0x75, 0x64, 0x53, 0xd9, 0x18, 0xda, 0x85, 0x86, 0xd5, 0xac, 0xb6, 0xc1, 0xd5, 0xd9, 0x9d, 0x70,
	0x86, 0x9e, 0xd6, 0x93, 0xef, 0xe0, 0x81, 0xe4, 0x21, 0xfa, 0x3c, 0xf2, 0x07, 0x22, 0xe9, 0xa3,
	0x5d, 0xd4, 0x8e, 0x9f, 0x18, 0x47, 0xfd, 0x48, 0xf7, 0x94, 0x87, 0xd8, 0x8d, 0x0e, 0x94, 0xd9,
	0xab, 0xc8, 0x6b, 0x81, 0x3c, 0x01, 0xc0, 0xcb, 0x98, 0x27, 0x98, 0xfa, 0x54, 0xda, 0xa5, 0x86,
	0xd5, 0xcc, 0x7b, 0xe5, 0x4c, 0xb3, 0x2b, 0xc9, 0x67, 0x50, 0x90, 0x57, 0x31, 0xda, 0x4b, 0x1a,
	0xb2, 0x3e, 0x07, 0x79, 0x15, 0xa3, 0xa7, 0xad, 0xe4, 0x31, 0x94, 0x13, 0x1c, 0x60, 0x82, 0x51,
	0x1f, 0xed, 0x65, 0x9d, 0xd7, 0xb5, 0x82, 0x3c, 0x87, 0xfb, 0x31, 0x0e, 0x87, 0xc8, 0x7c, 0xa1,
	0x02, 0xed, 0x72, 0xc3, 0x6a, 0x56, 0xda, 0x2b, 0x06, 0xeb, 0x58, 0x5b, 0x34, 0xa2, 0x57, 0x89,
	0xaf, 0x05, 0xe7, 0x07, 0x58, 0xd1, 0x87, 0x3d, 0xc5, 0x6e, 0x10, 0x50, 0xa9, 0x2a, 0xfc, 0x29,
	0x2c, 0x6b, 0x8c, 0x69, 0x81, 0xbd, 0x25, 0x2d, 0x77, 0x19, 0xd9, 0x98, 0x2d, 0xbe, 0xa9, 0xed,
	0xb4, 0xe8, 0xce, 0x6f, 0x79, 0xa8, 0x6a, 0xb4, 0xdd, 0x10, 0x23, 0x16, 0x62, 0x24, 0xc9, 0xd3,
	0x45, 0xa8, 0x29, 0x57, 0x1f, 0x05, 0x49, 0x9e, 0x4e, 0x78, 0xcc, 0xeb, 0x74, 0x2a, 0x59, 0x3a,
	0x4a, 0x35, 0x21, 0xf5, 0x09, 0x80, 0x22, 0xd0, 0x67, 0x18, 0x48, 0xaa, 0xe9, 0xcb, 0x7b, 0x65,
	0xa5, 0xd9, 0x57, 0x0a, 0xe2, 0xce, 0x95, 0xbe, 0xa8, 0x61, 0x6a, 0x06, 0x46, 0xd1, 0x95, 0x4a,
	0x1a, 0xc6, 0xb3, 0x5c, 0xdc, 0xe0, 0xb9, 0x74, 0x07, 0x9e, 0x5f, 0xc2, 0x83, 0x09, 0x09, 0x83,
	0x41, 0x8a, 0x52, 0x33, 0x5a, 0x69, 0x6f, 0xb8, 0x66, 0x3e, 0xdc, 0xc9, 0x7c, 0xb8, 0xdd, 0x48,
	0xbe, 0x78, 0xfe, 0x96, 0x06, 0x23, 0xf4, 0x32, 0xda, 0x7a, 0x3a, 0x80, 0xbc, 0x84, 0x7a, 0x86,
	0x30, 0xcf, 0x75, 0xb5, 0xfd, 0x68, 0x96, 0x4a, 0x6f, 0x62, 0xf4, 0x6a, 0xf1, 0xbc, 0xc2, 0xf9,
	0xcb, 0x82, 0xc7, 0x3f, 0xf2, 0x5f, 0x46, 0x9c, 0x71, 0x79, 0x75, 0x9c, 0x88, 0x31, 0x57, 0x63,
	0x73, 0xd7, 0x01, 0xfa, 0x1a, 0x56, 0xd4, 0x22, 0xe0, 0x52, 0xd1, 0xe8, 0xd3, 0x50, 0x8c, 0x22,
	0x99, 0xb1, 0x53, 0xbf, 0x36, 0xec, 0x6a, 0x3d, 0xa9, 0x43, 0x7e, 0x80, 0x86, 0xa3, 0xb2, 0xa7,
	0x8e, 0xe4, 0x2b, 0x28, 0xa6, 0x18, 0x04, 0xa9, 0x5d, 0x68, 0xe4, 0x9b, 0x95, 0xf6, 0xaa, 0x79,
	0xfb, 0xf4, 0x59, 0xa6, 0x13, 0x8d, 0x0b, 0x69, 0x42, 0xe1, 0x6c, 0x74, 0x95, 0xda, 0xc5, 0x0f,
	0xb8, 0x6a, 0x8f, 0xf9, 0x09, 0x28, 0x2d, 0x4c, 0x80, 0x73, 0x08, 0x9b, 0x37, 0xf3, 0x9e, 0x6b,
	0xec, 0x2a, 0xe4, 0xa6, 0x2d, 0x9d, 0xe3, 0xff, 0xd1, 0xcd, 0xff, 0x58, 0xb0, 0x71, 0x13, 0xef,
	0xba, 0xb5, 0xef, 0x02, 0x76, 0x7b, 0x39, 0xf3, 0x1f, 0x2e, 0x67, 0xe1, 0x96, 0x72, 0x16, 0x3f,
	0xbe, 0x9c, 0xa5, 0xbb, 0x95, 0x73, 0x69, 0xb1, 0x9c, 0x43, 0x20, 0xef, 0xb8, 0x3c, 0x67, 0x09,
	0xbd, 0x98, 0x69, 0x9e, 0x35, 0x28, 0x65, 0xaf, 0x37, 0x99, 0x67, 0x92, 0x5a, 0xb8, 0x34, 0x55,
	0x1d, 0x9f, 0x2d, 0x5c, 0x2d, 0x90, 0x67, 0x90, 0xc7, 0x4b, 0x99, 0x0d, 0x6f, 0xb6, 0x8b, 0x26,
	0xa0, 0x9d, 0x4b, 0xe9, 0x29, 0xab, 0x83, 0x40, 0x8e, 0x13, 0x11, 0x8b, 0x94, 0x06, 0x33, 0x17,
	0xcd, 0x3d, 0xce, 0x5a, 0xdc, 0x76, 0x3b, 0x50, 0x94, 0x98, 0x84, 0xa9, 0xbe, 0xae, 0xd2, 0x7e,
	0x38, 0xd9, 0x0b, 0x06, 0xe6, 0x54, 0x99, 0x4c, 0x53, 0x37, 0x2c, 0xcf, 0x78, 0x3a, 0x14, 0xaa,
	0x6f, 0x85, 0xc4, 0x99, 0x2b, 0xbe, 0x84, 0x4a, 0x9c, 0x45, 0xdc, 0x1c, 0x05, 0x98, 0x98, 0xba,
	0x8c, 0x7c, 0x01, 0xc5, 0xb1, 0x9a, 0x55, 0x7d, 0xdb, 0x74, 0x41, 0x2b, 0x34, 0xd7, 0xcc, 0xb0,
	0x31, 0x3b, 0x87, 0x40, 0xf6, 0x31, 0xc0, 0x21, 0x9d, 0xbb, 0x66, 0x0b, 0x96, 0x22, 0xc1, 0xf0,
	0xe6, 0x15, 0x25, 0xa5, 0xee, 0xb2, 0x99, 0x9a, 0xe6, 0x66, 0x6b, 0xea, 0xfc, 0x6d, 0xc1, 0xea,
	0x9b, 0x88, 0xfd, 0x7f, 0x88, 0xa4, 0x03, 0xa5, 0x10, 0xe5, 0xb9, 0x60, 0x9a, 0x92, 0x6a, 0x7b,
	0xdb, 0x5d, 0xfc, 0xe4, 0xbb, 0xb7, 0x5d, 0xe8, 0x1e, 0xea, 0x20, 0x2f, 0x0b, 0x76, 0x28, 0x94,
	0x8c, 0x86, 0xac, 0x01, 0x39, 0xec, 0x9c, 0xbe, 0xee, 0xed, 0xfb, 0x6f, 0x8e, 0x4e, 0x8e, 0x3b,
	0x7b, 0xdd, 0x83, 0x6e, 0x67, 0xbf, 0x7e, 0x8f, 0x54, 0x01, 0x32, 0xfd, 0x51, 0xef, 0x5d, 0xdd,
	0x22, 0xeb, 0xb0, 0x96, 0xc9, 0xbb, 0xa7, 0x7e, 0xe7, 0x68, 0xdf, 0xef, 0x1d, 0xf8, 0x9d, 0xe3,
	0xde, 0xde, 0xeb, 0x7a, 0x8e, 0x3c, 0x84, 0x5a, 0x66, 0xeb, 0x1e, 0xf9, 0xbb, 0x47, 0xdf, 0x77,
	0xbc, 0x7a, 0xde, 0xf9, 0x1c, 0x6a, 0x1e, 0xa6, 0x52, 0x24, 0x78, 0x12, 0xd1, 0x38, 0x3d, 0x17,
	0x92, 0x10, 0x28, 0x30, 0x2a, 0xa9, 0x4e, 0xf9, 0xbe, 0xa7, 0xcf, 0xaf, 0xdc, 0x9f, 0xbf, 0xe9,
	0x0b, 0x86, 0x3a, 0x0d, 0xbd, 0x5c, 0xfb, 0x22, 0x70, 0xb9, 0x30, 0x3f, 0x22, 0x69, 0x6b, 0xf1,
	0x8f, 0xe7, 0xac, 0xa4, 0x0d, 0xdf, 0xfe, 0x1b, 0x00, 0x00, 0xff, 0xff, 0x57, 0x3b, 0xb4, 0x5d,
	0x0c, 0x09, 0x00, 0x00,
}
