// Code generated by protoc-gen-go. DO NOT EDIT.
// source: data-node/api/v2/trading_data.proto

package v2

import (
	vega "code.vegaprotocol.io/protos/vega"
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AccountField int32

const (
	AccountField_AccountID       AccountField = 0
	AccountField_AccountPartyID  AccountField = 1
	AccountField_AccountAssetID  AccountField = 2
	AccountField_AccountMarketID AccountField = 3
	AccountField_AccountType     AccountField = 4
)

var AccountField_name = map[int32]string{
	0: "AccountID",
	1: "AccountPartyID",
	2: "AccountAssetID",
	3: "AccountMarketID",
	4: "AccountType",
}

var AccountField_value = map[string]int32{
	"AccountID":       0,
	"AccountPartyID":  1,
	"AccountAssetID":  2,
	"AccountMarketID": 3,
	"AccountType":     4,
}

func (x AccountField) String() string {
	return proto.EnumName(AccountField_name, int32(x))
}

func (AccountField) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_28fa50d8f66c85e8, []int{0}
}

type BalanceQueryRequest struct {
	Filter               *AccountFilter `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
	GroupBy              []AccountField `protobuf:"varint,2,rep,packed,name=group_by,json=groupBy,proto3,enum=AccountField" json:"group_by,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *BalanceQueryRequest) Reset()         { *m = BalanceQueryRequest{} }
func (m *BalanceQueryRequest) String() string { return proto.CompactTextString(m) }
func (*BalanceQueryRequest) ProtoMessage()    {}
func (*BalanceQueryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_28fa50d8f66c85e8, []int{0}
}

func (m *BalanceQueryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BalanceQueryRequest.Unmarshal(m, b)
}
func (m *BalanceQueryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BalanceQueryRequest.Marshal(b, m, deterministic)
}
func (m *BalanceQueryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BalanceQueryRequest.Merge(m, src)
}
func (m *BalanceQueryRequest) XXX_Size() int {
	return xxx_messageInfo_BalanceQueryRequest.Size(m)
}
func (m *BalanceQueryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BalanceQueryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BalanceQueryRequest proto.InternalMessageInfo

func (m *BalanceQueryRequest) GetFilter() *AccountFilter {
	if m != nil {
		return m.Filter
	}
	return nil
}

func (m *BalanceQueryRequest) GetGroupBy() []AccountField {
	if m != nil {
		return m.GroupBy
	}
	return nil
}

type BalanceQueryResponse struct {
	Balances             []*AggregatedBalance `protobuf:"bytes,1,rep,name=balances,proto3" json:"balances,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *BalanceQueryResponse) Reset()         { *m = BalanceQueryResponse{} }
func (m *BalanceQueryResponse) String() string { return proto.CompactTextString(m) }
func (*BalanceQueryResponse) ProtoMessage()    {}
func (*BalanceQueryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_28fa50d8f66c85e8, []int{1}
}

func (m *BalanceQueryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BalanceQueryResponse.Unmarshal(m, b)
}
func (m *BalanceQueryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BalanceQueryResponse.Marshal(b, m, deterministic)
}
func (m *BalanceQueryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BalanceQueryResponse.Merge(m, src)
}
func (m *BalanceQueryResponse) XXX_Size() int {
	return xxx_messageInfo_BalanceQueryResponse.Size(m)
}
func (m *BalanceQueryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BalanceQueryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BalanceQueryResponse proto.InternalMessageInfo

func (m *BalanceQueryResponse) GetBalances() []*AggregatedBalance {
	if m != nil {
		return m.Balances
	}
	return nil
}

type AggregatedBalance struct {
	// Timestamp to of block the balance is referring to, in nanoseconds since the epoch
	Timestamp int64 `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// The balance of the set of requested accounts at the time above
	Balance string `protobuf:"bytes,2,opt,name=balance,proto3" json:"balance,omitempty"`
	// If grouping by account ID, the account ID
	AccountId *wrappers.StringValue `protobuf:"bytes,3,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	// If grouping by party, the party ID
	PartyId *wrappers.StringValue `protobuf:"bytes,4,opt,name=party_id,json=partyId,proto3" json:"party_id,omitempty"`
	// If grouping by asset, the asset ID
	AssetId *wrappers.StringValue `protobuf:"bytes,5,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"`
	// If grouping by market, the market ID
	MarketId *wrappers.StringValue `protobuf:"bytes,6,opt,name=market_id,json=marketId,proto3" json:"market_id,omitempty"`
	// If grouping by account type, the account type
	AccountType          vega.AccountType `protobuf:"varint,7,opt,name=account_type,json=accountType,proto3,enum=vega.AccountType" json:"account_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *AggregatedBalance) Reset()         { *m = AggregatedBalance{} }
func (m *AggregatedBalance) String() string { return proto.CompactTextString(m) }
func (*AggregatedBalance) ProtoMessage()    {}
func (*AggregatedBalance) Descriptor() ([]byte, []int) {
	return fileDescriptor_28fa50d8f66c85e8, []int{2}
}

func (m *AggregatedBalance) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AggregatedBalance.Unmarshal(m, b)
}
func (m *AggregatedBalance) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AggregatedBalance.Marshal(b, m, deterministic)
}
func (m *AggregatedBalance) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AggregatedBalance.Merge(m, src)
}
func (m *AggregatedBalance) XXX_Size() int {
	return xxx_messageInfo_AggregatedBalance.Size(m)
}
func (m *AggregatedBalance) XXX_DiscardUnknown() {
	xxx_messageInfo_AggregatedBalance.DiscardUnknown(m)
}

var xxx_messageInfo_AggregatedBalance proto.InternalMessageInfo

func (m *AggregatedBalance) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *AggregatedBalance) GetBalance() string {
	if m != nil {
		return m.Balance
	}
	return ""
}

func (m *AggregatedBalance) GetAccountId() *wrappers.StringValue {
	if m != nil {
		return m.AccountId
	}
	return nil
}

func (m *AggregatedBalance) GetPartyId() *wrappers.StringValue {
	if m != nil {
		return m.PartyId
	}
	return nil
}

func (m *AggregatedBalance) GetAssetId() *wrappers.StringValue {
	if m != nil {
		return m.AssetId
	}
	return nil
}

func (m *AggregatedBalance) GetMarketId() *wrappers.StringValue {
	if m != nil {
		return m.MarketId
	}
	return nil
}

func (m *AggregatedBalance) GetAccountType() vega.AccountType {
	if m != nil {
		return m.AccountType
	}
	return vega.AccountType_ACCOUNT_TYPE_UNSPECIFIED
}

type AccountFilter struct {
	AssetId              string             `protobuf:"bytes,1,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"`
	PartyIds             []string           `protobuf:"bytes,2,rep,name=party_ids,json=partyIds,proto3" json:"party_ids,omitempty"`
	MarketIds            []string           `protobuf:"bytes,3,rep,name=market_ids,json=marketIds,proto3" json:"market_ids,omitempty"`
	AccountTypes         []vega.AccountType `protobuf:"varint,4,rep,packed,name=account_types,json=accountTypes,proto3,enum=vega.AccountType" json:"account_types,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *AccountFilter) Reset()         { *m = AccountFilter{} }
func (m *AccountFilter) String() string { return proto.CompactTextString(m) }
func (*AccountFilter) ProtoMessage()    {}
func (*AccountFilter) Descriptor() ([]byte, []int) {
	return fileDescriptor_28fa50d8f66c85e8, []int{3}
}

func (m *AccountFilter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountFilter.Unmarshal(m, b)
}
func (m *AccountFilter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountFilter.Marshal(b, m, deterministic)
}
func (m *AccountFilter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountFilter.Merge(m, src)
}
func (m *AccountFilter) XXX_Size() int {
	return xxx_messageInfo_AccountFilter.Size(m)
}
func (m *AccountFilter) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountFilter.DiscardUnknown(m)
}

var xxx_messageInfo_AccountFilter proto.InternalMessageInfo

func (m *AccountFilter) GetAssetId() string {
	if m != nil {
		return m.AssetId
	}
	return ""
}

func (m *AccountFilter) GetPartyIds() []string {
	if m != nil {
		return m.PartyIds
	}
	return nil
}

func (m *AccountFilter) GetMarketIds() []string {
	if m != nil {
		return m.MarketIds
	}
	return nil
}

func (m *AccountFilter) GetAccountTypes() []vega.AccountType {
	if m != nil {
		return m.AccountTypes
	}
	return nil
}

func init() {
	proto.RegisterEnum("AccountField", AccountField_name, AccountField_value)
	proto.RegisterType((*BalanceQueryRequest)(nil), "BalanceQueryRequest")
	proto.RegisterType((*BalanceQueryResponse)(nil), "BalanceQueryResponse")
	proto.RegisterType((*AggregatedBalance)(nil), "AggregatedBalance")
	proto.RegisterType((*AccountFilter)(nil), "AccountFilter")
}

func init() {
	proto.RegisterFile("data-node/api/v2/trading_data.proto", fileDescriptor_28fa50d8f66c85e8)
}

var fileDescriptor_28fa50d8f66c85e8 = []byte{
	// 531 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x53, 0xdf, 0x8b, 0xd3, 0x40,
	0x10, 0xbe, 0x34, 0x67, 0xdb, 0x4c, 0x7f, 0xde, 0xde, 0x09, 0xf1, 0x3c, 0xa5, 0x54, 0x90, 0x20,
	0xba, 0x81, 0x28, 0x8a, 0x88, 0x0f, 0x2d, 0xe1, 0xa0, 0x0f, 0x82, 0xa6, 0x87, 0x0f, 0xbe, 0x94,
	0x6d, 0xb2, 0x17, 0xc2, 0xa5, 0xd9, 0xb8, 0xbb, 0xa9, 0xe4, 0x9f, 0xf1, 0x1f, 0xf4, 0x9f, 0x90,
	0xee, 0x26, 0xd7, 0x9c, 0xf6, 0xa1, 0x2f, 0x0b, 0x33, 0xdf, 0x7c, 0xec, 0x37, 0x33, 0xdf, 0xc0,
	0x8b, 0x88, 0x48, 0xf2, 0x26, 0x63, 0x11, 0x75, 0x49, 0x9e, 0xb8, 0x5b, 0xcf, 0x95, 0x9c, 0x44,
	0x49, 0x16, 0xaf, 0x76, 0x00, 0xce, 0x39, 0x93, 0xec, 0x72, 0xb4, 0xa5, 0x31, 0x71, 0x77, 0x4f,
	0x95, 0x78, 0x1e, 0x33, 0x16, 0xa7, 0xd4, 0x55, 0xd1, 0xba, 0xb8, 0x75, 0x7f, 0x71, 0x92, 0xe7,
	0x94, 0x0b, 0x8d, 0x4f, 0x63, 0x38, 0x9f, 0x93, 0x94, 0x64, 0x21, 0xfd, 0x56, 0x50, 0x5e, 0x06,
	0xf4, 0x67, 0x41, 0x85, 0x44, 0x2f, 0xa1, 0x7d, 0x9b, 0xa4, 0x92, 0x72, 0xdb, 0x98, 0x18, 0x4e,
	0xcf, 0x1b, 0xe2, 0x59, 0x18, 0xb2, 0x22, 0x93, 0xd7, 0x2a, 0x1b, 0x54, 0x28, 0x72, 0xa0, 0x1b,
	0x73, 0x56, 0xe4, 0xab, 0x75, 0x69, 0xb7, 0x26, 0xa6, 0x33, 0xf4, 0x06, 0xfb, 0x4a, 0x9a, 0x46,
	0x41, 0x47, 0xc1, 0xf3, 0x72, 0x7a, 0x0d, 0x17, 0x0f, 0x3f, 0x12, 0x39, 0xcb, 0x04, 0x45, 0x18,
	0xba, 0x6b, 0x9d, 0x17, 0xb6, 0x31, 0x31, 0x9d, 0x9e, 0x87, 0xf0, 0x2c, 0x8e, 0x39, 0x8d, 0x89,
	0xa4, 0x51, 0x45, 0x09, 0xee, 0x6b, 0xa6, 0x7f, 0x5a, 0x70, 0xf6, 0x1f, 0x8e, 0xae, 0xc0, 0x92,
	0xc9, 0x86, 0x0a, 0x49, 0x36, 0xb9, 0x92, 0x6c, 0x06, 0xfb, 0x04, 0xb2, 0xa1, 0x53, 0xf1, 0xed,
	0xd6, 0xc4, 0x70, 0xac, 0xa0, 0x0e, 0xd1, 0x27, 0x00, 0xa2, 0xe5, 0xae, 0x92, 0xc8, 0x36, 0x55,
	0xaf, 0x57, 0x58, 0xcf, 0x0c, 0xd7, 0x33, 0xc3, 0x4b, 0xc9, 0x93, 0x2c, 0xfe, 0x4e, 0xd2, 0x82,
	0x06, 0x56, 0x55, 0xbf, 0x88, 0xd0, 0x07, 0xe8, 0xe6, 0x84, 0xcb, 0x72, 0x47, 0x3d, 0x3d, 0x82,
	0xda, 0x51, 0xd5, 0x9a, 0x48, 0x84, 0xa0, 0xea, 0xcf, 0x47, 0xc7, 0x10, 0x55, 0xf5, 0x22, 0x42,
	0x1f, 0xc1, 0xda, 0x10, 0x7e, 0xa7, 0x99, 0xed, 0x23, 0x98, 0x5d, 0x5d, 0xbe, 0x88, 0xd0, 0x3b,
	0xe8, 0xd7, 0x9d, 0xca, 0x32, 0xa7, 0x76, 0x67, 0x62, 0x38, 0x43, 0xef, 0x0c, 0x2b, 0xaf, 0x54,
	0x2b, 0xbb, 0x29, 0x73, 0x1a, 0xf4, 0xc8, 0x3e, 0x98, 0xfe, 0x36, 0x60, 0xf0, 0x60, 0xf3, 0xe8,
	0x49, 0x43, 0xbb, 0xa1, 0x87, 0x59, 0xab, 0x7b, 0x0a, 0x56, 0x3d, 0x0f, 0xa1, 0xdc, 0x60, 0x05,
	0xdd, 0xaa, 0x65, 0x81, 0x9e, 0x01, 0xdc, 0x4b, 0x17, 0xb6, 0xa9, 0x50, 0xab, 0x56, 0x27, 0xd0,
	0x7b, 0x18, 0x34, 0xe5, 0x09, 0xfb, 0x54, 0xb9, 0xe9, 0x80, 0xbe, 0x7e, 0x43, 0x9f, 0x78, 0x75,
	0x07, 0xfd, 0xa6, 0xdf, 0xd0, 0x00, 0xac, 0x2a, 0x5e, 0xf8, 0xe3, 0x13, 0x84, 0x60, 0x58, 0x85,
	0x5f, 0x95, 0x10, 0x7f, 0x6c, 0x34, 0x72, 0x33, 0x25, 0xdc, 0x1f, 0xb7, 0xd0, 0x39, 0x8c, 0xaa,
	0xdc, 0x17, 0x2d, 0xc9, 0x1f, 0x9b, 0x68, 0x04, 0xbd, 0xc6, 0xc7, 0xe3, 0x53, 0x6f, 0x09, 0xe8,
	0x46, 0xdf, 0x9c, 0x4f, 0x24, 0x59, 0x52, 0xbe, 0x4d, 0x42, 0x8a, 0x3e, 0x43, 0xbf, 0xe9, 0x6c,
	0x74, 0x81, 0x0f, 0x5c, 0xd4, 0xe5, 0x63, 0x7c, 0xc8, 0xfe, 0xd3, 0x93, 0x39, 0xfe, 0xf1, 0x3a,
	0x64, 0x11, 0x55, 0x8d, 0xaa, 0x1d, 0x86, 0x2c, 0xc5, 0x09, 0xd3, 0x17, 0x2b, 0xdc, 0x7f, 0xaf,
	0x7e, 0xdd, 0x56, 0xc0, 0xdb, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x5f, 0x7f, 0x2b, 0xc6, 0x10,
	0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TradingDataServiceClient is the client API for TradingDataService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TradingDataServiceClient interface {
	BalanceQuery(ctx context.Context, in *BalanceQueryRequest, opts ...grpc.CallOption) (*BalanceQueryResponse, error)
}

type tradingDataServiceClient struct {
	cc *grpc.ClientConn
}

func NewTradingDataServiceClient(cc *grpc.ClientConn) TradingDataServiceClient {
	return &tradingDataServiceClient{cc}
}

func (c *tradingDataServiceClient) BalanceQuery(ctx context.Context, in *BalanceQueryRequest, opts ...grpc.CallOption) (*BalanceQueryResponse, error) {
	out := new(BalanceQueryResponse)
	err := c.cc.Invoke(ctx, "/TradingDataService/BalanceQuery", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TradingDataServiceServer is the server API for TradingDataService service.
type TradingDataServiceServer interface {
	BalanceQuery(context.Context, *BalanceQueryRequest) (*BalanceQueryResponse, error)
}

func RegisterTradingDataServiceServer(s *grpc.Server, srv TradingDataServiceServer) {
	s.RegisterService(&_TradingDataService_serviceDesc, srv)
}

func _TradingDataService_BalanceQuery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BalanceQueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradingDataServiceServer).BalanceQuery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/TradingDataService/BalanceQuery",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradingDataServiceServer).BalanceQuery(ctx, req.(*BalanceQueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _TradingDataService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "TradingDataService",
	HandlerType: (*TradingDataServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "BalanceQuery",
			Handler:    _TradingDataService_BalanceQuery_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "data-node/api/v2/trading_data.proto",
}
