// Code generated by protoc-gen-go. DO NOT EDIT.
// source: vega/api/trading.proto

package api

import (
	vega "code.vegaprotocol.io/protos/vega"
	v1 "code.vegaprotocol.io/protos/vega/commands/v1"
	v11 "code.vegaprotocol.io/protos/vega/events/v1"
	_ "code.vegaprotocol.io/protos/vega/oracles/v1"
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/mwitkow/go-proto-validators"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Blockchain transaction type
type SubmitTransactionV2Request_Type int32

const (
	SubmitTransactionV2Request_TYPE_UNSPECIFIED SubmitTransactionV2Request_Type = 0
	// The transaction will be submitted without waiting for response
	SubmitTransactionV2Request_TYPE_ASYNC SubmitTransactionV2Request_Type = 1
	// The transaction will be submitted, and blocking until the
	// tendermint mempool return a response
	SubmitTransactionV2Request_TYPE_SYNC SubmitTransactionV2Request_Type = 2
	// The transaction will submitted, and blocking until the tendermint
	// network will have committed it into a block
	SubmitTransactionV2Request_TYPE_COMMIT SubmitTransactionV2Request_Type = 3
)

var SubmitTransactionV2Request_Type_name = map[int32]string{
	0: "TYPE_UNSPECIFIED",
	1: "TYPE_ASYNC",
	2: "TYPE_SYNC",
	3: "TYPE_COMMIT",
}

var SubmitTransactionV2Request_Type_value = map[string]int32{
	"TYPE_UNSPECIFIED": 0,
	"TYPE_ASYNC":       1,
	"TYPE_SYNC":        2,
	"TYPE_COMMIT":      3,
}

func (x SubmitTransactionV2Request_Type) String() string {
	return proto.EnumName(SubmitTransactionV2Request_Type_name, int32(x))
}

func (SubmitTransactionV2Request_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_5e536cf6517e5fb7, []int{2, 0}
}

// Request for a new event sent by the blockchain queue to be propagated on Vega
type PropagateChainEventRequest struct {
	// Chain event
	Event []byte `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	// Public key
	PubKey string `protobuf:"bytes,2,opt,name=pub_key,json=pubKey,proto3" json:"pub_key,omitempty"`
	// Signature
	Signature            []byte   `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PropagateChainEventRequest) Reset()         { *m = PropagateChainEventRequest{} }
func (m *PropagateChainEventRequest) String() string { return proto.CompactTextString(m) }
func (*PropagateChainEventRequest) ProtoMessage()    {}
func (*PropagateChainEventRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5e536cf6517e5fb7, []int{0}
}

func (m *PropagateChainEventRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PropagateChainEventRequest.Unmarshal(m, b)
}
func (m *PropagateChainEventRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PropagateChainEventRequest.Marshal(b, m, deterministic)
}
func (m *PropagateChainEventRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PropagateChainEventRequest.Merge(m, src)
}
func (m *PropagateChainEventRequest) XXX_Size() int {
	return xxx_messageInfo_PropagateChainEventRequest.Size(m)
}
func (m *PropagateChainEventRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PropagateChainEventRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PropagateChainEventRequest proto.InternalMessageInfo

func (m *PropagateChainEventRequest) GetEvent() []byte {
	if m != nil {
		return m.Event
	}
	return nil
}

func (m *PropagateChainEventRequest) GetPubKey() string {
	if m != nil {
		return m.PubKey
	}
	return ""
}

func (m *PropagateChainEventRequest) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

// Response for a new event sent by the blockchain queue to be propagated on Vega
type PropagateChainEventResponse struct {
	// Success will be true if the event was accepted by the node,
	// **Important** - success does not mean that the event is confirmed by consensus
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PropagateChainEventResponse) Reset()         { *m = PropagateChainEventResponse{} }
func (m *PropagateChainEventResponse) String() string { return proto.CompactTextString(m) }
func (*PropagateChainEventResponse) ProtoMessage()    {}
func (*PropagateChainEventResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5e536cf6517e5fb7, []int{1}
}

func (m *PropagateChainEventResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PropagateChainEventResponse.Unmarshal(m, b)
}
func (m *PropagateChainEventResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PropagateChainEventResponse.Marshal(b, m, deterministic)
}
func (m *PropagateChainEventResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PropagateChainEventResponse.Merge(m, src)
}
func (m *PropagateChainEventResponse) XXX_Size() int {
	return xxx_messageInfo_PropagateChainEventResponse.Size(m)
}
func (m *PropagateChainEventResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PropagateChainEventResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PropagateChainEventResponse proto.InternalMessageInfo

func (m *PropagateChainEventResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

// Request for submitting a transaction v2 on Vega
type SubmitTransactionV2Request struct {
	// A bundle of signed payload and signature, to form a transaction that will be submitted to the Vega blockchain
	Tx *v1.Transaction `protobuf:"bytes,1,opt,name=tx,proto3" json:"tx,omitempty"`
	// Type of transaction request, for example ASYNC, meaning the transaction will be submitted and not block on a response
	Type                 SubmitTransactionV2Request_Type `protobuf:"varint,2,opt,name=type,proto3,enum=api.v1.SubmitTransactionV2Request_Type" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                        `json:"-"`
	XXX_unrecognized     []byte                          `json:"-"`
	XXX_sizecache        int32                           `json:"-"`
}

func (m *SubmitTransactionV2Request) Reset()         { *m = SubmitTransactionV2Request{} }
func (m *SubmitTransactionV2Request) String() string { return proto.CompactTextString(m) }
func (*SubmitTransactionV2Request) ProtoMessage()    {}
func (*SubmitTransactionV2Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_5e536cf6517e5fb7, []int{2}
}

func (m *SubmitTransactionV2Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubmitTransactionV2Request.Unmarshal(m, b)
}
func (m *SubmitTransactionV2Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubmitTransactionV2Request.Marshal(b, m, deterministic)
}
func (m *SubmitTransactionV2Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubmitTransactionV2Request.Merge(m, src)
}
func (m *SubmitTransactionV2Request) XXX_Size() int {
	return xxx_messageInfo_SubmitTransactionV2Request.Size(m)
}
func (m *SubmitTransactionV2Request) XXX_DiscardUnknown() {
	xxx_messageInfo_SubmitTransactionV2Request.DiscardUnknown(m)
}

var xxx_messageInfo_SubmitTransactionV2Request proto.InternalMessageInfo

func (m *SubmitTransactionV2Request) GetTx() *v1.Transaction {
	if m != nil {
		return m.Tx
	}
	return nil
}

func (m *SubmitTransactionV2Request) GetType() SubmitTransactionV2Request_Type {
	if m != nil {
		return m.Type
	}
	return SubmitTransactionV2Request_TYPE_UNSPECIFIED
}

// Response for submitting a transaction v2 on Vega
type SubmitTransactionV2Response struct {
	// Success will be true if the transaction was accepted by the node,
	// **Important** - success does not mean that the event is confirmed by consensus
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubmitTransactionV2Response) Reset()         { *m = SubmitTransactionV2Response{} }
func (m *SubmitTransactionV2Response) String() string { return proto.CompactTextString(m) }
func (*SubmitTransactionV2Response) ProtoMessage()    {}
func (*SubmitTransactionV2Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_5e536cf6517e5fb7, []int{3}
}

func (m *SubmitTransactionV2Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubmitTransactionV2Response.Unmarshal(m, b)
}
func (m *SubmitTransactionV2Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubmitTransactionV2Response.Marshal(b, m, deterministic)
}
func (m *SubmitTransactionV2Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubmitTransactionV2Response.Merge(m, src)
}
func (m *SubmitTransactionV2Response) XXX_Size() int {
	return xxx_messageInfo_SubmitTransactionV2Response.Size(m)
}
func (m *SubmitTransactionV2Response) XXX_DiscardUnknown() {
	xxx_messageInfo_SubmitTransactionV2Response.DiscardUnknown(m)
}

var xxx_messageInfo_SubmitTransactionV2Response proto.InternalMessageInfo

func (m *SubmitTransactionV2Response) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

// Request for the current time of the vega network
type GetVegaTimeRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetVegaTimeRequest) Reset()         { *m = GetVegaTimeRequest{} }
func (m *GetVegaTimeRequest) String() string { return proto.CompactTextString(m) }
func (*GetVegaTimeRequest) ProtoMessage()    {}
func (*GetVegaTimeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5e536cf6517e5fb7, []int{4}
}

func (m *GetVegaTimeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetVegaTimeRequest.Unmarshal(m, b)
}
func (m *GetVegaTimeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetVegaTimeRequest.Marshal(b, m, deterministic)
}
func (m *GetVegaTimeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetVegaTimeRequest.Merge(m, src)
}
func (m *GetVegaTimeRequest) XXX_Size() int {
	return xxx_messageInfo_GetVegaTimeRequest.Size(m)
}
func (m *GetVegaTimeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetVegaTimeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetVegaTimeRequest proto.InternalMessageInfo

// Response for the current consensus coordinated time on the Vega network, referred to as "VegaTime"
type GetVegaTimeResponse struct {
	// Timestamp representation of current VegaTime as represented in
	// Nanoseconds since the epoch, for example `1580473859111222333` corresponds to `2020-01-31T12:30:59.111222333Z`
	Timestamp            int64    `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetVegaTimeResponse) Reset()         { *m = GetVegaTimeResponse{} }
func (m *GetVegaTimeResponse) String() string { return proto.CompactTextString(m) }
func (*GetVegaTimeResponse) ProtoMessage()    {}
func (*GetVegaTimeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5e536cf6517e5fb7, []int{5}
}

func (m *GetVegaTimeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetVegaTimeResponse.Unmarshal(m, b)
}
func (m *GetVegaTimeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetVegaTimeResponse.Marshal(b, m, deterministic)
}
func (m *GetVegaTimeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetVegaTimeResponse.Merge(m, src)
}
func (m *GetVegaTimeResponse) XXX_Size() int {
	return xxx_messageInfo_GetVegaTimeResponse.Size(m)
}
func (m *GetVegaTimeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetVegaTimeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetVegaTimeResponse proto.InternalMessageInfo

func (m *GetVegaTimeResponse) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

// Request to subscribe to a stream of one or more event types from the Vega event bus
type ObserveEventBusRequest struct {
	// One or more types of event, required field
	Type []v11.BusEventType `protobuf:"varint,1,rep,packed,name=type,proto3,enum=vega.events.v1.BusEventType" json:"type,omitempty"`
	// Market identifier, optional field
	MarketId string `protobuf:"bytes,2,opt,name=market_id,json=marketId,proto3" json:"market_id,omitempty"`
	// Party identifier, optional field
	PartyId string `protobuf:"bytes,3,opt,name=party_id,json=partyId,proto3" json:"party_id,omitempty"`
	// Batch size, optional field -
	// If not specified, any events received will be sent immediately. If the client is not ready
	// for the next data-set, data may be dropped a number of times, and eventually the stream is closed.
	// if specified, the first batch will be sent when ready. To receive the next set of events, the client
	// must write an `ObserveEventBatch` message on the stream to flush the buffer.
	// If no message is received in 5 seconds, the stream is closed.
	// Default: 0, send any and all events when they are available.
	BatchSize            int64    `protobuf:"varint,4,opt,name=batch_size,json=batchSize,proto3" json:"batch_size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ObserveEventBusRequest) Reset()         { *m = ObserveEventBusRequest{} }
func (m *ObserveEventBusRequest) String() string { return proto.CompactTextString(m) }
func (*ObserveEventBusRequest) ProtoMessage()    {}
func (*ObserveEventBusRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5e536cf6517e5fb7, []int{6}
}

func (m *ObserveEventBusRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ObserveEventBusRequest.Unmarshal(m, b)
}
func (m *ObserveEventBusRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ObserveEventBusRequest.Marshal(b, m, deterministic)
}
func (m *ObserveEventBusRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ObserveEventBusRequest.Merge(m, src)
}
func (m *ObserveEventBusRequest) XXX_Size() int {
	return xxx_messageInfo_ObserveEventBusRequest.Size(m)
}
func (m *ObserveEventBusRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ObserveEventBusRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ObserveEventBusRequest proto.InternalMessageInfo

func (m *ObserveEventBusRequest) GetType() []v11.BusEventType {
	if m != nil {
		return m.Type
	}
	return nil
}

func (m *ObserveEventBusRequest) GetMarketId() string {
	if m != nil {
		return m.MarketId
	}
	return ""
}

func (m *ObserveEventBusRequest) GetPartyId() string {
	if m != nil {
		return m.PartyId
	}
	return ""
}

func (m *ObserveEventBusRequest) GetBatchSize() int64 {
	if m != nil {
		return m.BatchSize
	}
	return 0
}

// Response to a subscribed stream of events from the Vega event bus
type ObserveEventBusResponse struct {
	// One or more events
	Events               []*v11.BusEvent `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ObserveEventBusResponse) Reset()         { *m = ObserveEventBusResponse{} }
func (m *ObserveEventBusResponse) String() string { return proto.CompactTextString(m) }
func (*ObserveEventBusResponse) ProtoMessage()    {}
func (*ObserveEventBusResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5e536cf6517e5fb7, []int{7}
}

func (m *ObserveEventBusResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ObserveEventBusResponse.Unmarshal(m, b)
}
func (m *ObserveEventBusResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ObserveEventBusResponse.Marshal(b, m, deterministic)
}
func (m *ObserveEventBusResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ObserveEventBusResponse.Merge(m, src)
}
func (m *ObserveEventBusResponse) XXX_Size() int {
	return xxx_messageInfo_ObserveEventBusResponse.Size(m)
}
func (m *ObserveEventBusResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ObserveEventBusResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ObserveEventBusResponse proto.InternalMessageInfo

func (m *ObserveEventBusResponse) GetEvents() []*v11.BusEvent {
	if m != nil {
		return m.Events
	}
	return nil
}

// A a request for statistics about the Vega network
type StatisticsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StatisticsRequest) Reset()         { *m = StatisticsRequest{} }
func (m *StatisticsRequest) String() string { return proto.CompactTextString(m) }
func (*StatisticsRequest) ProtoMessage()    {}
func (*StatisticsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5e536cf6517e5fb7, []int{8}
}

func (m *StatisticsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatisticsRequest.Unmarshal(m, b)
}
func (m *StatisticsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatisticsRequest.Marshal(b, m, deterministic)
}
func (m *StatisticsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatisticsRequest.Merge(m, src)
}
func (m *StatisticsRequest) XXX_Size() int {
	return xxx_messageInfo_StatisticsRequest.Size(m)
}
func (m *StatisticsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StatisticsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StatisticsRequest proto.InternalMessageInfo

type StatisticsResponse struct {
	Statistics           *Statistics `protobuf:"bytes,1,opt,name=statistics,proto3" json:"statistics,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *StatisticsResponse) Reset()         { *m = StatisticsResponse{} }
func (m *StatisticsResponse) String() string { return proto.CompactTextString(m) }
func (*StatisticsResponse) ProtoMessage()    {}
func (*StatisticsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5e536cf6517e5fb7, []int{9}
}

func (m *StatisticsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatisticsResponse.Unmarshal(m, b)
}
func (m *StatisticsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatisticsResponse.Marshal(b, m, deterministic)
}
func (m *StatisticsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatisticsResponse.Merge(m, src)
}
func (m *StatisticsResponse) XXX_Size() int {
	return xxx_messageInfo_StatisticsResponse.Size(m)
}
func (m *StatisticsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StatisticsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StatisticsResponse proto.InternalMessageInfo

func (m *StatisticsResponse) GetStatistics() *Statistics {
	if m != nil {
		return m.Statistics
	}
	return nil
}

// Vega domain specific statistics as reported by the node the caller is connected to
type Statistics struct {
	// Current block height as reported by the Vega blockchain
	BlockHeight uint64 `protobuf:"varint,1,opt,name=block_height,json=blockHeight,proto3" json:"block_height,omitempty"`
	// Current backlog length (number of transactions) that are waiting to be included in a block
	BacklogLength uint64 `protobuf:"varint,2,opt,name=backlog_length,json=backlogLength,proto3" json:"backlog_length,omitempty"`
	// Total number of connected peers to this node
	TotalPeers uint64 `protobuf:"varint,3,opt,name=total_peers,json=totalPeers,proto3" json:"total_peers,omitempty"`
	// Genesis block date and time formatted in ISO-8601 datetime format with nanosecond precision
	GenesisTime string `protobuf:"bytes,4,opt,name=genesis_time,json=genesisTime,proto3" json:"genesis_time,omitempty"`
	// Current system date and time formatted in ISO-8601 datetime format with nanosecond precision
	CurrentTime string `protobuf:"bytes,5,opt,name=current_time,json=currentTime,proto3" json:"current_time,omitempty"`
	// Current Vega date and time formatted in ISO-8601 datetime format with nanosecond precision
	VegaTime string `protobuf:"bytes,6,opt,name=vega_time,json=vegaTime,proto3" json:"vega_time,omitempty"`
	// Status of the connection to the Vega blockchain
	// - See [`ChainStatus`](#vega.ChainStatus)
	Status vega.ChainStatus `protobuf:"varint,7,opt,name=status,proto3,enum=vega.ChainStatus" json:"status,omitempty"`
	// Transactions per block
	TxPerBlock uint64 `protobuf:"varint,8,opt,name=tx_per_block,json=txPerBlock,proto3" json:"tx_per_block,omitempty"`
	// Average transaction size in bytes
	AverageTxBytes uint64 `protobuf:"varint,9,opt,name=average_tx_bytes,json=averageTxBytes,proto3" json:"average_tx_bytes,omitempty"`
	// Average orders per block
	AverageOrdersPerBlock uint64 `protobuf:"varint,10,opt,name=average_orders_per_block,json=averageOrdersPerBlock,proto3" json:"average_orders_per_block,omitempty"`
	// Trades emitted per second
	TradesPerSecond uint64 `protobuf:"varint,11,opt,name=trades_per_second,json=tradesPerSecond,proto3" json:"trades_per_second,omitempty"`
	// Orders processed per second
	OrdersPerSecond uint64 `protobuf:"varint,12,opt,name=orders_per_second,json=ordersPerSecond,proto3" json:"orders_per_second,omitempty"`
	// Total markets on this Vega network
	TotalMarkets uint64 `protobuf:"varint,13,opt,name=total_markets,json=totalMarkets,proto3" json:"total_markets,omitempty"`
	// Total number of order amendments since genesis (on all markets)
	TotalAmendOrder uint64 `protobuf:"varint,16,opt,name=total_amend_order,json=totalAmendOrder,proto3" json:"total_amend_order,omitempty"`
	// Total number of order cancellations since genesis (on all markets)
	TotalCancelOrder uint64 `protobuf:"varint,17,opt,name=total_cancel_order,json=totalCancelOrder,proto3" json:"total_cancel_order,omitempty"`
	// Total number of order submissions since genesis (on all markets)
	TotalCreateOrder uint64 `protobuf:"varint,18,opt,name=total_create_order,json=totalCreateOrder,proto3" json:"total_create_order,omitempty"`
	// Total number of orders processed since genesis (on all markets)
	TotalOrders uint64 `protobuf:"varint,19,opt,name=total_orders,json=totalOrders,proto3" json:"total_orders,omitempty"`
	// Total number of trades emitted since genesis (on all markets)
	TotalTrades uint64 `protobuf:"varint,20,opt,name=total_trades,json=totalTrades,proto3" json:"total_trades,omitempty"`
	// Current number of stream subscribers to order data
	OrderSubscriptions uint32 `protobuf:"varint,21,opt,name=order_subscriptions,json=orderSubscriptions,proto3" json:"order_subscriptions,omitempty"`
	// Current number of stream subscribers to trade data
	TradeSubscriptions uint32 `protobuf:"varint,22,opt,name=trade_subscriptions,json=tradeSubscriptions,proto3" json:"trade_subscriptions,omitempty"`
	// Current number of stream subscribers to candle-stick data
	CandleSubscriptions uint32 `protobuf:"varint,23,opt,name=candle_subscriptions,json=candleSubscriptions,proto3" json:"candle_subscriptions,omitempty"`
	// Current number of stream subscribers to market depth data
	MarketDepthSubscriptions uint32 `protobuf:"varint,24,opt,name=market_depth_subscriptions,json=marketDepthSubscriptions,proto3" json:"market_depth_subscriptions,omitempty"`
	// Current number of stream subscribers to positions data
	PositionsSubscriptions uint32 `protobuf:"varint,25,opt,name=positions_subscriptions,json=positionsSubscriptions,proto3" json:"positions_subscriptions,omitempty"`
	// Current number of stream subscribers to account data
	AccountSubscriptions uint32 `protobuf:"varint,26,opt,name=account_subscriptions,json=accountSubscriptions,proto3" json:"account_subscriptions,omitempty"`
	// Current number of stream subscribers to market data
	MarketDataSubscriptions uint32 `protobuf:"varint,27,opt,name=market_data_subscriptions,json=marketDataSubscriptions,proto3" json:"market_data_subscriptions,omitempty"`
	// The version hash of the Vega node software
	AppVersionHash string `protobuf:"bytes,28,opt,name=app_version_hash,json=appVersionHash,proto3" json:"app_version_hash,omitempty"`
	// The version of the Vega node software
	AppVersion string `protobuf:"bytes,29,opt,name=app_version,json=appVersion,proto3" json:"app_version,omitempty"`
	// The version of the underlying Vega blockchain
	ChainVersion string `protobuf:"bytes,30,opt,name=chain_version,json=chainVersion,proto3" json:"chain_version,omitempty"`
	// Current block duration, in nanoseconds
	BlockDuration uint64 `protobuf:"varint,31,opt,name=block_duration,json=blockDuration,proto3" json:"block_duration,omitempty"`
	// Total uptime for this node formatted in ISO-8601 datetime format with nanosecond precision
	Uptime string `protobuf:"bytes,32,opt,name=uptime,proto3" json:"uptime,omitempty"`
	// Unique identifier for the underlying Vega blockchain
	ChainId string `protobuf:"bytes,33,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	// Current number of stream subscribers to market depth update data
	MarketDepthUpdatesSubscriptions uint32   `protobuf:"varint,34,opt,name=market_depth_updates_subscriptions,json=marketDepthUpdatesSubscriptions,proto3" json:"market_depth_updates_subscriptions,omitempty"`
	XXX_NoUnkeyedLiteral            struct{} `json:"-"`
	XXX_unrecognized                []byte   `json:"-"`
	XXX_sizecache                   int32    `json:"-"`
}

func (m *Statistics) Reset()         { *m = Statistics{} }
func (m *Statistics) String() string { return proto.CompactTextString(m) }
func (*Statistics) ProtoMessage()    {}
func (*Statistics) Descriptor() ([]byte, []int) {
	return fileDescriptor_5e536cf6517e5fb7, []int{10}
}

func (m *Statistics) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Statistics.Unmarshal(m, b)
}
func (m *Statistics) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Statistics.Marshal(b, m, deterministic)
}
func (m *Statistics) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Statistics.Merge(m, src)
}
func (m *Statistics) XXX_Size() int {
	return xxx_messageInfo_Statistics.Size(m)
}
func (m *Statistics) XXX_DiscardUnknown() {
	xxx_messageInfo_Statistics.DiscardUnknown(m)
}

var xxx_messageInfo_Statistics proto.InternalMessageInfo

func (m *Statistics) GetBlockHeight() uint64 {
	if m != nil {
		return m.BlockHeight
	}
	return 0
}

func (m *Statistics) GetBacklogLength() uint64 {
	if m != nil {
		return m.BacklogLength
	}
	return 0
}

func (m *Statistics) GetTotalPeers() uint64 {
	if m != nil {
		return m.TotalPeers
	}
	return 0
}

func (m *Statistics) GetGenesisTime() string {
	if m != nil {
		return m.GenesisTime
	}
	return ""
}

func (m *Statistics) GetCurrentTime() string {
	if m != nil {
		return m.CurrentTime
	}
	return ""
}

func (m *Statistics) GetVegaTime() string {
	if m != nil {
		return m.VegaTime
	}
	return ""
}

func (m *Statistics) GetStatus() vega.ChainStatus {
	if m != nil {
		return m.Status
	}
	return vega.ChainStatus_CHAIN_STATUS_UNSPECIFIED
}

func (m *Statistics) GetTxPerBlock() uint64 {
	if m != nil {
		return m.TxPerBlock
	}
	return 0
}

func (m *Statistics) GetAverageTxBytes() uint64 {
	if m != nil {
		return m.AverageTxBytes
	}
	return 0
}

func (m *Statistics) GetAverageOrdersPerBlock() uint64 {
	if m != nil {
		return m.AverageOrdersPerBlock
	}
	return 0
}

func (m *Statistics) GetTradesPerSecond() uint64 {
	if m != nil {
		return m.TradesPerSecond
	}
	return 0
}

func (m *Statistics) GetOrdersPerSecond() uint64 {
	if m != nil {
		return m.OrdersPerSecond
	}
	return 0
}

func (m *Statistics) GetTotalMarkets() uint64 {
	if m != nil {
		return m.TotalMarkets
	}
	return 0
}

func (m *Statistics) GetTotalAmendOrder() uint64 {
	if m != nil {
		return m.TotalAmendOrder
	}
	return 0
}

func (m *Statistics) GetTotalCancelOrder() uint64 {
	if m != nil {
		return m.TotalCancelOrder
	}
	return 0
}

func (m *Statistics) GetTotalCreateOrder() uint64 {
	if m != nil {
		return m.TotalCreateOrder
	}
	return 0
}

func (m *Statistics) GetTotalOrders() uint64 {
	if m != nil {
		return m.TotalOrders
	}
	return 0
}

func (m *Statistics) GetTotalTrades() uint64 {
	if m != nil {
		return m.TotalTrades
	}
	return 0
}

func (m *Statistics) GetOrderSubscriptions() uint32 {
	if m != nil {
		return m.OrderSubscriptions
	}
	return 0
}

func (m *Statistics) GetTradeSubscriptions() uint32 {
	if m != nil {
		return m.TradeSubscriptions
	}
	return 0
}

func (m *Statistics) GetCandleSubscriptions() uint32 {
	if m != nil {
		return m.CandleSubscriptions
	}
	return 0
}

func (m *Statistics) GetMarketDepthSubscriptions() uint32 {
	if m != nil {
		return m.MarketDepthSubscriptions
	}
	return 0
}

func (m *Statistics) GetPositionsSubscriptions() uint32 {
	if m != nil {
		return m.PositionsSubscriptions
	}
	return 0
}

func (m *Statistics) GetAccountSubscriptions() uint32 {
	if m != nil {
		return m.AccountSubscriptions
	}
	return 0
}

func (m *Statistics) GetMarketDataSubscriptions() uint32 {
	if m != nil {
		return m.MarketDataSubscriptions
	}
	return 0
}

func (m *Statistics) GetAppVersionHash() string {
	if m != nil {
		return m.AppVersionHash
	}
	return ""
}

func (m *Statistics) GetAppVersion() string {
	if m != nil {
		return m.AppVersion
	}
	return ""
}

func (m *Statistics) GetChainVersion() string {
	if m != nil {
		return m.ChainVersion
	}
	return ""
}

func (m *Statistics) GetBlockDuration() uint64 {
	if m != nil {
		return m.BlockDuration
	}
	return 0
}

func (m *Statistics) GetUptime() string {
	if m != nil {
		return m.Uptime
	}
	return ""
}

func (m *Statistics) GetChainId() string {
	if m != nil {
		return m.ChainId
	}
	return ""
}

func (m *Statistics) GetMarketDepthUpdatesSubscriptions() uint32 {
	if m != nil {
		return m.MarketDepthUpdatesSubscriptions
	}
	return 0
}

// A request to get the height of the very last block processed
// by tendermint
type LastBlockHeightRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LastBlockHeightRequest) Reset()         { *m = LastBlockHeightRequest{} }
func (m *LastBlockHeightRequest) String() string { return proto.CompactTextString(m) }
func (*LastBlockHeightRequest) ProtoMessage()    {}
func (*LastBlockHeightRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5e536cf6517e5fb7, []int{11}
}

func (m *LastBlockHeightRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LastBlockHeightRequest.Unmarshal(m, b)
}
func (m *LastBlockHeightRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LastBlockHeightRequest.Marshal(b, m, deterministic)
}
func (m *LastBlockHeightRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LastBlockHeightRequest.Merge(m, src)
}
func (m *LastBlockHeightRequest) XXX_Size() int {
	return xxx_messageInfo_LastBlockHeightRequest.Size(m)
}
func (m *LastBlockHeightRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LastBlockHeightRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LastBlockHeightRequest proto.InternalMessageInfo

// A response with the height of the last block processed by
// tendermint
type LastBlockHeightResponse struct {
	Height               uint64   `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LastBlockHeightResponse) Reset()         { *m = LastBlockHeightResponse{} }
func (m *LastBlockHeightResponse) String() string { return proto.CompactTextString(m) }
func (*LastBlockHeightResponse) ProtoMessage()    {}
func (*LastBlockHeightResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5e536cf6517e5fb7, []int{12}
}

func (m *LastBlockHeightResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LastBlockHeightResponse.Unmarshal(m, b)
}
func (m *LastBlockHeightResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LastBlockHeightResponse.Marshal(b, m, deterministic)
}
func (m *LastBlockHeightResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LastBlockHeightResponse.Merge(m, src)
}
func (m *LastBlockHeightResponse) XXX_Size() int {
	return xxx_messageInfo_LastBlockHeightResponse.Size(m)
}
func (m *LastBlockHeightResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LastBlockHeightResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LastBlockHeightResponse proto.InternalMessageInfo

func (m *LastBlockHeightResponse) GetHeight() uint64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func init() {
	proto.RegisterEnum("api.v1.SubmitTransactionV2Request_Type", SubmitTransactionV2Request_Type_name, SubmitTransactionV2Request_Type_value)
	proto.RegisterType((*PropagateChainEventRequest)(nil), "api.v1.PropagateChainEventRequest")
	proto.RegisterType((*PropagateChainEventResponse)(nil), "api.v1.PropagateChainEventResponse")
	proto.RegisterType((*SubmitTransactionV2Request)(nil), "api.v1.SubmitTransactionV2Request")
	proto.RegisterType((*SubmitTransactionV2Response)(nil), "api.v1.SubmitTransactionV2Response")
	proto.RegisterType((*GetVegaTimeRequest)(nil), "api.v1.GetVegaTimeRequest")
	proto.RegisterType((*GetVegaTimeResponse)(nil), "api.v1.GetVegaTimeResponse")
	proto.RegisterType((*ObserveEventBusRequest)(nil), "api.v1.ObserveEventBusRequest")
	proto.RegisterType((*ObserveEventBusResponse)(nil), "api.v1.ObserveEventBusResponse")
	proto.RegisterType((*StatisticsRequest)(nil), "api.v1.StatisticsRequest")
	proto.RegisterType((*StatisticsResponse)(nil), "api.v1.StatisticsResponse")
	proto.RegisterType((*Statistics)(nil), "api.v1.Statistics")
	proto.RegisterType((*LastBlockHeightRequest)(nil), "api.v1.LastBlockHeightRequest")
	proto.RegisterType((*LastBlockHeightResponse)(nil), "api.v1.LastBlockHeightResponse")
}

func init() { proto.RegisterFile("vega/api/trading.proto", fileDescriptor_5e536cf6517e5fb7) }

var fileDescriptor_5e536cf6517e5fb7 = []byte{
	// 1342 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x57, 0xed, 0x52, 0xdb, 0x38,
	0x17, 0x7e, 0x03, 0x69, 0x20, 0x27, 0x10, 0x82, 0x02, 0xc1, 0x04, 0x5a, 0xa8, 0xfb, 0x7e, 0xd0,
	0x77, 0xb6, 0x49, 0x49, 0x67, 0xb6, 0x33, 0xbb, 0xfb, 0xa7, 0x50, 0xba, 0x65, 0xfa, 0xc5, 0x38,
	0x29, 0x33, 0xdd, 0x1f, 0xf5, 0x28, 0xb6, 0x26, 0xd1, 0x90, 0xd8, 0x5e, 0x4b, 0x76, 0xa1, 0x77,
	0xb0, 0x97, 0xb1, 0x37, 0xb5, 0xf7, 0xb0, 0x77, 0xb1, 0xa3, 0x23, 0x39, 0x4e, 0x42, 0x68, 0xff,
	0x30, 0xd1, 0xf3, 0x71, 0x74, 0x7c, 0x24, 0x1d, 0x09, 0x68, 0xa4, 0x6c, 0x40, 0xdb, 0x34, 0xe2,
	0x6d, 0x19, 0x53, 0x9f, 0x07, 0x83, 0x56, 0x14, 0x87, 0x32, 0x24, 0x25, 0x1a, 0xf1, 0x56, 0x7a,
	0xdc, 0xdc, 0x40, 0x5e, 0xfd, 0xd1, 0x44, 0x93, 0x20, 0x30, 0xa6, 0xf1, 0x15, 0x93, 0xc2, 0x60,
	0xdb, 0x88, 0x0d, 0xc2, 0x94, 0xc5, 0x01, 0x0d, 0x3c, 0x66, 0xe0, 0x4d, 0x1d, 0x5b, 0x88, 0x5c,
	0xb9, 0x87, 0x10, 0x4b, 0x59, 0x20, 0x45, 0x3b, 0x3d, 0x36, 0xbf, 0x0c, 0xd9, 0x44, 0x32, 0x8c,
	0xa9, 0x37, 0x62, 0xc8, 0x8a, 0x88, 0x79, 0x77, 0x71, 0x3e, 0x95, 0x59, 0x4a, 0x07, 0xc8, 0x79,
	0xe1, 0x78, 0x4c, 0x03, 0x1f, 0xc9, 0xec, 0xb7, 0x11, 0xd8, 0xb7, 0x04, 0x32, 0xa6, 0x81, 0xa0,
	0x9e, 0xe4, 0x61, 0x60, 0x34, 0x8f, 0x6f, 0x69, 0x52, 0x3a, 0xe2, 0x3e, 0x95, 0x61, 0xec, 0xce,
	0x85, 0xfb, 0x71, 0xc0, 0xe5, 0x30, 0xe9, 0xb7, 0xbc, 0x70, 0xdc, 0x1e, 0x7f, 0xe1, 0xf2, 0x2a,
	0xfc, 0xd2, 0x1e, 0x84, 0x4f, 0x90, 0x7c, 0x32, 0x71, 0x89, 0x3c, 0x80, 0xf6, 0xd9, 0x1c, 0x9a,
	0x17, 0x71, 0x18, 0xd1, 0x01, 0x95, 0xec, 0x74, 0x48, 0x79, 0x70, 0xa6, 0xbe, 0xde, 0x61, 0xbf,
	0x27, 0x4c, 0x48, 0xb2, 0x05, 0xf7, 0xb0, 0x1a, 0x56, 0xe1, 0xb0, 0x70, 0xb4, 0xe6, 0xe8, 0x01,
	0xd9, 0x81, 0x95, 0x28, 0xe9, 0xbb, 0x57, 0xec, 0xc6, 0x5a, 0x3a, 0x2c, 0x1c, 0x95, 0x9d, 0x52,
	0x94, 0xf4, 0xdf, 0xb0, 0x1b, 0xb2, 0x0f, 0x65, 0xc1, 0x07, 0x01, 0x95, 0x49, 0xcc, 0xac, 0x65,
	0xb4, 0xe4, 0x80, 0xfd, 0x1c, 0xf6, 0x16, 0x4e, 0x25, 0xa2, 0x30, 0x10, 0x8c, 0x58, 0xb0, 0x22,
	0x12, 0xcf, 0x63, 0x42, 0xe0, 0x6c, 0xab, 0x4e, 0x36, 0xb4, 0xff, 0x2a, 0x40, 0xb3, 0x9b, 0xf4,
	0xc7, 0x5c, 0xf6, 0xf2, 0x12, 0x5d, 0x76, 0xb2, 0x24, 0x9f, 0xc0, 0x92, 0xbc, 0x46, 0x4f, 0xa5,
	0x73, 0xbf, 0x85, 0xdb, 0x62, 0x52, 0x9c, 0xf4, 0xb8, 0x35, 0xe5, 0x71, 0x96, 0xe4, 0x35, 0xf9,
	0x19, 0x8a, 0xf2, 0x26, 0x62, 0x98, 0x7a, 0xb5, 0xf3, 0xbf, 0x96, 0xde, 0x54, 0xad, 0xbb, 0x27,
	0x68, 0xf5, 0x6e, 0x22, 0xe6, 0xa0, 0xc9, 0x7e, 0x0b, 0x45, 0x35, 0x22, 0x5b, 0x50, 0xeb, 0x7d,
	0xba, 0x38, 0x73, 0x3f, 0xbe, 0xef, 0x5e, 0x9c, 0x9d, 0x9e, 0xbf, 0x3a, 0x3f, 0x7b, 0x59, 0xfb,
	0x17, 0xa9, 0x02, 0x20, 0xfa, 0xa2, 0xfb, 0xe9, 0xfd, 0x69, 0xad, 0x40, 0xd6, 0xa1, 0x8c, 0x63,
	0x1c, 0x2e, 0x91, 0x0d, 0xa8, 0xe0, 0xf0, 0xf4, 0xc3, 0xbb, 0x77, 0xe7, 0xbd, 0xda, 0xb2, 0xaa,
	0xc8, 0xc2, 0x69, 0xbf, 0x5b, 0x91, 0x2d, 0x20, 0xbf, 0x32, 0x79, 0xc9, 0x06, 0xb4, 0xc7, 0xc7,
	0xcc, 0xe4, 0x69, 0x3f, 0x83, 0xfa, 0x0c, 0x6a, 0xc2, 0xec, 0x43, 0x59, 0xf2, 0x31, 0x13, 0x92,
	0x8e, 0x23, 0x0c, 0xb4, 0xec, 0xe4, 0x80, 0xfd, 0x67, 0x01, 0x1a, 0x1f, 0xfa, 0x82, 0xc5, 0x29,
	0xc3, 0xf5, 0x38, 0x49, 0x44, 0x56, 0xd8, 0xa7, 0xa6, 0x52, 0x85, 0xc3, 0xe5, 0xa3, 0x6a, 0x67,
	0x5f, 0x97, 0xd6, 0x9c, 0x8e, 0xf4, 0xb8, 0x75, 0x92, 0x08, 0x74, 0xe4, 0xe5, 0x21, 0x7b, 0x50,
	0xd6, 0xa7, 0xd0, 0xe5, 0xbe, 0xd9, 0x1b, 0xab, 0x1a, 0x38, 0xf7, 0xc9, 0x2e, 0xac, 0x46, 0x34,
	0x96, 0x37, 0x8a, 0x5b, 0x46, 0x6e, 0x05, 0xc7, 0xe7, 0x3e, 0xb9, 0x0f, 0xd0, 0xa7, 0xd2, 0x1b,
	0xba, 0x82, 0x7f, 0x65, 0x56, 0x51, 0xe7, 0x88, 0x48, 0x97, 0x7f, 0x65, 0xf6, 0x1b, 0xd8, 0xb9,
	0x95, 0xa2, 0xf9, 0xb8, 0xa7, 0x50, 0xd2, 0x19, 0x61, 0x96, 0x95, 0x8e, 0x75, 0x57, 0x96, 0x8e,
	0xd1, 0xd9, 0x75, 0xd8, 0xec, 0x4a, 0x2a, 0xb9, 0x90, 0xdc, 0xcb, 0x3e, 0xd5, 0x7e, 0x0d, 0x64,
	0x1a, 0x34, 0xc1, 0x3b, 0x00, 0x62, 0x82, 0x9a, 0x1d, 0x46, 0x26, 0x1b, 0x26, 0xd7, 0x4f, 0xa9,
	0xec, 0xbf, 0x01, 0x20, 0xa7, 0xc8, 0x43, 0x58, 0xeb, 0x8f, 0x42, 0xef, 0xca, 0x1d, 0x32, 0x3e,
	0x18, 0xea, 0x83, 0x54, 0x74, 0x2a, 0x88, 0xbd, 0x46, 0x88, 0xfc, 0x07, 0xaa, 0x7d, 0xea, 0x5d,
	0x8d, 0xc2, 0x81, 0x3b, 0x62, 0xc1, 0x40, 0x0e, 0xb1, 0x72, 0x45, 0x67, 0xdd, 0xa0, 0x6f, 0x11,
	0x24, 0x07, 0x50, 0x91, 0xa1, 0xa4, 0x23, 0x37, 0x62, 0x2c, 0x16, 0x58, 0xc1, 0xa2, 0x03, 0x08,
	0x5d, 0x28, 0x44, 0x4d, 0x35, 0x60, 0x01, 0x13, 0x5c, 0xb8, 0x6a, 0x79, 0xb1, 0x8c, 0x65, 0xa7,
	0x62, 0x30, 0xb5, 0x25, 0x94, 0xc4, 0x4b, 0xe2, 0x98, 0x05, 0x52, 0x4b, 0xee, 0x69, 0x89, 0xc1,
	0x50, 0xb2, 0x07, 0x65, 0x55, 0x41, 0xcd, 0x97, 0xf4, 0x12, 0xa6, 0x66, 0x4b, 0x91, 0xc7, 0x50,
	0x52, 0x9f, 0x9a, 0x08, 0x6b, 0x05, 0x4f, 0xcf, 0xa6, 0xae, 0x36, 0x9e, 0xe6, 0x2e, 0x12, 0x8e,
	0x11, 0x90, 0x43, 0x58, 0x93, 0xd7, 0x6e, 0xc4, 0x62, 0x17, 0xbf, 0xd5, 0x5a, 0x35, 0xf9, 0x5e,
	0x5f, 0xb0, 0xf8, 0x44, 0x21, 0xe4, 0x08, 0x6a, 0x34, 0x65, 0x31, 0x1d, 0x30, 0x57, 0x5e, 0xbb,
	0xfd, 0x1b, 0xc9, 0x84, 0x55, 0x46, 0x55, 0xd5, 0xe0, 0xbd, 0xeb, 0x13, 0x85, 0x92, 0xe7, 0x60,
	0x65, 0xca, 0x30, 0xf6, 0x59, 0x2c, 0xa6, 0xe2, 0x02, 0x3a, 0xb6, 0x0d, 0xff, 0x01, 0xe9, 0xc9,
	0x14, 0xff, 0x87, 0x4d, 0x75, 0x85, 0x30, 0x6d, 0x10, 0xcc, 0x0b, 0x03, 0xdf, 0xaa, 0xa0, 0x63,
	0x43, 0x13, 0x17, 0x2c, 0xee, 0x22, 0xac, 0xb4, 0x53, 0xc1, 0x8d, 0x76, 0x4d, 0x6b, 0xc3, 0x2c,
	0xac, 0xd1, 0x3e, 0x82, 0x75, 0xbd, 0x16, 0xe6, 0xce, 0xb1, 0xd6, 0x51, 0xb7, 0x86, 0xe0, 0x3b,
	0x8d, 0xe1, 0xe4, 0x28, 0xa2, 0x63, 0x16, 0xf8, 0x3a, 0x73, 0xab, 0x66, 0x26, 0x57, 0xc4, 0x0b,
	0x85, 0x63, 0xc6, 0xe4, 0x07, 0x20, 0x5a, 0xeb, 0xa9, 0xbb, 0x6a, 0x64, 0xc4, 0x9b, 0x28, 0xae,
	0x21, 0x73, 0x8a, 0xc4, 0xbc, 0x3a, 0x66, 0x54, 0x9a, 0xa2, 0x58, 0x64, 0x5a, 0x8d, 0x84, 0x56,
	0x3f, 0x04, 0x9d, 0x97, 0xa9, 0x9d, 0x55, 0xd7, 0x5b, 0x10, 0x31, 0x5d, 0xaf, 0x5c, 0xa2, 0x8b,
	0x62, 0x6d, 0x4d, 0x49, 0x7a, 0x08, 0x91, 0x36, 0xd4, 0xd1, 0xef, 0x8a, 0xa4, 0x2f, 0xbc, 0x98,
	0x47, 0xaa, 0x59, 0x09, 0x6b, 0xfb, 0xb0, 0x70, 0xb4, 0xee, 0x10, 0xa4, 0xba, 0xd3, 0x8c, 0x32,
	0x60, 0xb4, 0x39, 0x43, 0x43, 0x1b, 0x90, 0x9a, 0x35, 0x1c, 0xc3, 0x96, 0x47, 0x03, 0x7f, 0x34,
	0xef, 0xd8, 0x41, 0x47, 0x5d, 0x73, 0xb3, 0x96, 0x5f, 0xa0, 0x69, 0xfa, 0x8d, 0xcf, 0x22, 0x39,
	0x9c, 0x33, 0x5a, 0x68, 0xb4, 0xb4, 0xe2, 0xa5, 0x12, 0xcc, 0xba, 0x9f, 0xc3, 0x4e, 0x14, 0x0a,
	0x8e, 0x83, 0x39, 0xeb, 0x2e, 0x5a, 0x1b, 0x13, 0x7a, 0xd6, 0xf8, 0x0c, 0xb6, 0xa9, 0xe7, 0x85,
	0x49, 0x20, 0xe7, 0x6c, 0x4d, 0xb4, 0x6d, 0x19, 0x72, 0xd6, 0xf4, 0x13, 0xec, 0x66, 0xb9, 0x52,
	0x49, 0xe7, 0x8c, 0x7b, 0x68, 0xdc, 0x31, 0xa9, 0x52, 0x49, 0x67, 0xbd, 0xea, 0xa8, 0x44, 0x91,
	0x9b, 0xb2, 0x58, 0xf0, 0x30, 0x70, 0x87, 0x54, 0x0c, 0xad, 0x7d, 0x3c, 0x9b, 0x55, 0x1a, 0x45,
	0x97, 0x1a, 0x7e, 0x4d, 0x05, 0x76, 0x89, 0x29, 0xa5, 0x75, 0x1f, 0x45, 0x90, 0x8b, 0xd4, 0xd6,
	0xf5, 0xd4, 0x71, 0x9d, 0x48, 0x1e, 0xa0, 0x64, 0x0d, 0xc1, 0x4c, 0xa4, 0x5a, 0x12, 0x76, 0x2d,
	0x3f, 0x89, 0xa9, 0x4a, 0xc1, 0x3a, 0x30, 0x2d, 0x49, 0xa1, 0x2f, 0x0d, 0x48, 0x1a, 0x50, 0x4a,
	0x22, 0x6c, 0x14, 0x87, 0xfa, 0x1d, 0xa0, 0x47, 0xaa, 0xd3, 0xeb, 0x39, 0xb8, 0x6f, 0x3d, 0xd4,
	0x9d, 0x1e, 0xc7, 0xe7, 0x3e, 0x79, 0x03, 0xf6, 0xcc, 0x8a, 0x25, 0x91, 0x4f, 0x25, 0x9b, 0x2f,
	0xbf, 0x8d, 0xe5, 0x38, 0x98, 0x5a, 0xb9, 0x8f, 0x5a, 0x37, 0x53, 0x16, 0xdb, 0x82, 0xc6, 0x5b,
	0x2a, 0xe4, 0x49, 0xde, 0x4c, 0xb3, 0x7e, 0x7e, 0x0c, 0x3b, 0xb7, 0x18, 0xd3, 0xd4, 0x1b, 0x50,
	0x9a, 0xe9, 0xc5, 0x66, 0xd4, 0xf9, 0xa3, 0x08, 0xd5, 0x9e, 0x7e, 0x6f, 0x76, 0x59, 0x9c, 0x72,
	0x8f, 0x91, 0xcf, 0x50, 0x5f, 0x70, 0x3f, 0x13, 0xfb, 0xfb, 0x6f, 0x86, 0xe6, 0xa3, 0x6f, 0x6a,
	0x4c, 0x2a, 0x9f, 0xa1, 0xbe, 0xe0, 0x45, 0x94, 0xc7, 0xbf, 0xfb, 0x65, 0x96, 0xc7, 0xff, 0xd6,
	0x93, 0xea, 0x74, 0xe6, 0x2a, 0xda, 0x5d, 0x70, 0x73, 0x99, 0x68, 0xcd, 0x45, 0x94, 0x09, 0xe2,
	0xc0, 0xc6, 0x5c, 0x29, 0xc9, 0x83, 0x4c, 0xbe, 0xb8, 0xfa, 0xcd, 0x83, 0x3b, 0x79, 0x13, 0xf3,
	0x15, 0x54, 0xa6, 0x5e, 0x2a, 0x64, 0x32, 0xfd, 0xed, 0x47, 0x4d, 0x73, 0x6f, 0x21, 0x67, 0xe2,
	0x5c, 0xc2, 0xc6, 0xdc, 0xc3, 0x20, 0xcf, 0x6d, 0xf1, 0xa3, 0x26, 0xcf, 0xed, 0x8e, 0x17, 0xc5,
	0x51, 0xe1, 0x69, 0xe1, 0xe4, 0xbf, 0xbf, 0xfd, 0xdb, 0x0b, 0x7d, 0x86, 0xb7, 0x1b, 0xbe, 0x93,
	0xbd, 0x70, 0xd4, 0xe2, 0x61, 0x1b, 0x7f, 0x8b, 0x76, 0xf6, 0xff, 0x49, 0xbf, 0x84, 0xc0, 0xb3,
	0x7f, 0x02, 0x00, 0x00, 0xff, 0xff, 0x91, 0x2d, 0xc0, 0xac, 0xb2, 0x0c, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TradingServiceClient is the client API for TradingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TradingServiceClient interface {
	// Submit a signed transaction (v2)
	SubmitTransactionV2(ctx context.Context, in *SubmitTransactionV2Request, opts ...grpc.CallOption) (*SubmitTransactionV2Response, error)
	// Propagate a chain event
	PropagateChainEvent(ctx context.Context, in *PropagateChainEventRequest, opts ...grpc.CallOption) (*PropagateChainEventResponse, error)
	// Get Statistics on Vega
	Statistics(ctx context.Context, in *StatisticsRequest, opts ...grpc.CallOption) (*StatisticsResponse, error)
	// Get the height of the last tendermint block
	LastBlockHeight(ctx context.Context, in *LastBlockHeightRequest, opts ...grpc.CallOption) (*LastBlockHeightResponse, error)
	// Get Time
	GetVegaTime(ctx context.Context, in *GetVegaTimeRequest, opts ...grpc.CallOption) (*GetVegaTimeResponse, error)
	// Subscribe to a stream of events from the core
	ObserveEventBus(ctx context.Context, opts ...grpc.CallOption) (TradingService_ObserveEventBusClient, error)
}

type tradingServiceClient struct {
	cc *grpc.ClientConn
}

func NewTradingServiceClient(cc *grpc.ClientConn) TradingServiceClient {
	return &tradingServiceClient{cc}
}

func (c *tradingServiceClient) SubmitTransactionV2(ctx context.Context, in *SubmitTransactionV2Request, opts ...grpc.CallOption) (*SubmitTransactionV2Response, error) {
	out := new(SubmitTransactionV2Response)
	err := c.cc.Invoke(ctx, "/api.v1.TradingService/SubmitTransactionV2", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tradingServiceClient) PropagateChainEvent(ctx context.Context, in *PropagateChainEventRequest, opts ...grpc.CallOption) (*PropagateChainEventResponse, error) {
	out := new(PropagateChainEventResponse)
	err := c.cc.Invoke(ctx, "/api.v1.TradingService/PropagateChainEvent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tradingServiceClient) Statistics(ctx context.Context, in *StatisticsRequest, opts ...grpc.CallOption) (*StatisticsResponse, error) {
	out := new(StatisticsResponse)
	err := c.cc.Invoke(ctx, "/api.v1.TradingService/Statistics", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tradingServiceClient) LastBlockHeight(ctx context.Context, in *LastBlockHeightRequest, opts ...grpc.CallOption) (*LastBlockHeightResponse, error) {
	out := new(LastBlockHeightResponse)
	err := c.cc.Invoke(ctx, "/api.v1.TradingService/LastBlockHeight", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tradingServiceClient) GetVegaTime(ctx context.Context, in *GetVegaTimeRequest, opts ...grpc.CallOption) (*GetVegaTimeResponse, error) {
	out := new(GetVegaTimeResponse)
	err := c.cc.Invoke(ctx, "/api.v1.TradingService/GetVegaTime", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tradingServiceClient) ObserveEventBus(ctx context.Context, opts ...grpc.CallOption) (TradingService_ObserveEventBusClient, error) {
	stream, err := c.cc.NewStream(ctx, &_TradingService_serviceDesc.Streams[0], "/api.v1.TradingService/ObserveEventBus", opts...)
	if err != nil {
		return nil, err
	}
	x := &tradingServiceObserveEventBusClient{stream}
	return x, nil
}

type TradingService_ObserveEventBusClient interface {
	Send(*ObserveEventBusRequest) error
	Recv() (*ObserveEventBusResponse, error)
	grpc.ClientStream
}

type tradingServiceObserveEventBusClient struct {
	grpc.ClientStream
}

func (x *tradingServiceObserveEventBusClient) Send(m *ObserveEventBusRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *tradingServiceObserveEventBusClient) Recv() (*ObserveEventBusResponse, error) {
	m := new(ObserveEventBusResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// TradingServiceServer is the server API for TradingService service.
type TradingServiceServer interface {
	// Submit a signed transaction (v2)
	SubmitTransactionV2(context.Context, *SubmitTransactionV2Request) (*SubmitTransactionV2Response, error)
	// Propagate a chain event
	PropagateChainEvent(context.Context, *PropagateChainEventRequest) (*PropagateChainEventResponse, error)
	// Get Statistics on Vega
	Statistics(context.Context, *StatisticsRequest) (*StatisticsResponse, error)
	// Get the height of the last tendermint block
	LastBlockHeight(context.Context, *LastBlockHeightRequest) (*LastBlockHeightResponse, error)
	// Get Time
	GetVegaTime(context.Context, *GetVegaTimeRequest) (*GetVegaTimeResponse, error)
	// Subscribe to a stream of events from the core
	ObserveEventBus(TradingService_ObserveEventBusServer) error
}

func RegisterTradingServiceServer(s *grpc.Server, srv TradingServiceServer) {
	s.RegisterService(&_TradingService_serviceDesc, srv)
}

func _TradingService_SubmitTransactionV2_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitTransactionV2Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradingServiceServer).SubmitTransactionV2(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.v1.TradingService/SubmitTransactionV2",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradingServiceServer).SubmitTransactionV2(ctx, req.(*SubmitTransactionV2Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _TradingService_PropagateChainEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PropagateChainEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradingServiceServer).PropagateChainEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.v1.TradingService/PropagateChainEvent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradingServiceServer).PropagateChainEvent(ctx, req.(*PropagateChainEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TradingService_Statistics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatisticsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradingServiceServer).Statistics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.v1.TradingService/Statistics",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradingServiceServer).Statistics(ctx, req.(*StatisticsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TradingService_LastBlockHeight_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LastBlockHeightRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradingServiceServer).LastBlockHeight(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.v1.TradingService/LastBlockHeight",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradingServiceServer).LastBlockHeight(ctx, req.(*LastBlockHeightRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TradingService_GetVegaTime_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVegaTimeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradingServiceServer).GetVegaTime(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.v1.TradingService/GetVegaTime",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradingServiceServer).GetVegaTime(ctx, req.(*GetVegaTimeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TradingService_ObserveEventBus_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TradingServiceServer).ObserveEventBus(&tradingServiceObserveEventBusServer{stream})
}

type TradingService_ObserveEventBusServer interface {
	Send(*ObserveEventBusResponse) error
	Recv() (*ObserveEventBusRequest, error)
	grpc.ServerStream
}

type tradingServiceObserveEventBusServer struct {
	grpc.ServerStream
}

func (x *tradingServiceObserveEventBusServer) Send(m *ObserveEventBusResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *tradingServiceObserveEventBusServer) Recv() (*ObserveEventBusRequest, error) {
	m := new(ObserveEventBusRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _TradingService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.v1.TradingService",
	HandlerType: (*TradingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitTransactionV2",
			Handler:    _TradingService_SubmitTransactionV2_Handler,
		},
		{
			MethodName: "PropagateChainEvent",
			Handler:    _TradingService_PropagateChainEvent_Handler,
		},
		{
			MethodName: "Statistics",
			Handler:    _TradingService_Statistics_Handler,
		},
		{
			MethodName: "LastBlockHeight",
			Handler:    _TradingService_LastBlockHeight_Handler,
		},
		{
			MethodName: "GetVegaTime",
			Handler:    _TradingService_GetVegaTime_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ObserveEventBus",
			Handler:       _TradingService_ObserveEventBus_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "vega/api/trading.proto",
}
