// Code generated by protoc-gen-go. DO NOT EDIT.
// source: vega/snapshot.proto

package vega

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Snapshot is the entire checkpoint serialised (basically serialised the Checkpoint message + hash)
type Snapshot struct {
	Hash                 string   `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	State                []byte   `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Snapshot) Reset()         { *m = Snapshot{} }
func (m *Snapshot) String() string { return proto.CompactTextString(m) }
func (*Snapshot) ProtoMessage()    {}
func (*Snapshot) Descriptor() ([]byte, []int) {
	return fileDescriptor_6ef1468f19ab6b2e, []int{0}
}

func (m *Snapshot) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Snapshot.Unmarshal(m, b)
}
func (m *Snapshot) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Snapshot.Marshal(b, m, deterministic)
}
func (m *Snapshot) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Snapshot.Merge(m, src)
}
func (m *Snapshot) XXX_Size() int {
	return xxx_messageInfo_Snapshot.Size(m)
}
func (m *Snapshot) XXX_DiscardUnknown() {
	xxx_messageInfo_Snapshot.DiscardUnknown(m)
}

var xxx_messageInfo_Snapshot proto.InternalMessageInfo

func (m *Snapshot) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func (m *Snapshot) GetState() []byte {
	if m != nil {
		return m.State
	}
	return nil
}

// Checkpoint aggregates the various engine snapshots
type Checkpoint struct {
	Governance           []byte   `protobuf:"bytes,1,opt,name=governance,proto3" json:"governance,omitempty"`
	Assets               []byte   `protobuf:"bytes,2,opt,name=assets,proto3" json:"assets,omitempty"`
	Collateral           []byte   `protobuf:"bytes,3,opt,name=collateral,proto3" json:"collateral,omitempty"`
	NetworkParameters    []byte   `protobuf:"bytes,4,opt,name=network_parameters,json=networkParameters,proto3" json:"network_parameters,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Checkpoint) Reset()         { *m = Checkpoint{} }
func (m *Checkpoint) String() string { return proto.CompactTextString(m) }
func (*Checkpoint) ProtoMessage()    {}
func (*Checkpoint) Descriptor() ([]byte, []int) {
	return fileDescriptor_6ef1468f19ab6b2e, []int{1}
}

func (m *Checkpoint) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Checkpoint.Unmarshal(m, b)
}
func (m *Checkpoint) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Checkpoint.Marshal(b, m, deterministic)
}
func (m *Checkpoint) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Checkpoint.Merge(m, src)
}
func (m *Checkpoint) XXX_Size() int {
	return xxx_messageInfo_Checkpoint.Size(m)
}
func (m *Checkpoint) XXX_DiscardUnknown() {
	xxx_messageInfo_Checkpoint.DiscardUnknown(m)
}

var xxx_messageInfo_Checkpoint proto.InternalMessageInfo

func (m *Checkpoint) GetGovernance() []byte {
	if m != nil {
		return m.Governance
	}
	return nil
}

func (m *Checkpoint) GetAssets() []byte {
	if m != nil {
		return m.Assets
	}
	return nil
}

func (m *Checkpoint) GetCollateral() []byte {
	if m != nil {
		return m.Collateral
	}
	return nil
}

func (m *Checkpoint) GetNetworkParameters() []byte {
	if m != nil {
		return m.NetworkParameters
	}
	return nil
}

// AssetEntrty is a single (enabled) asset
type AssetEntry struct {
	Id                   string        `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AssetDetails         *AssetDetails `protobuf:"bytes,2,opt,name=asset_details,json=assetDetails,proto3" json:"asset_details,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *AssetEntry) Reset()         { *m = AssetEntry{} }
func (m *AssetEntry) String() string { return proto.CompactTextString(m) }
func (*AssetEntry) ProtoMessage()    {}
func (*AssetEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_6ef1468f19ab6b2e, []int{2}
}

func (m *AssetEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AssetEntry.Unmarshal(m, b)
}
func (m *AssetEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AssetEntry.Marshal(b, m, deterministic)
}
func (m *AssetEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AssetEntry.Merge(m, src)
}
func (m *AssetEntry) XXX_Size() int {
	return xxx_messageInfo_AssetEntry.Size(m)
}
func (m *AssetEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_AssetEntry.DiscardUnknown(m)
}

var xxx_messageInfo_AssetEntry proto.InternalMessageInfo

func (m *AssetEntry) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *AssetEntry) GetAssetDetails() *AssetDetails {
	if m != nil {
		return m.AssetDetails
	}
	return nil
}

// Assets contains all the enabled assets as AssetEntries
type Assets struct {
	Assets               []*AssetEntry `protobuf:"bytes,1,rep,name=assets,proto3" json:"assets,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Assets) Reset()         { *m = Assets{} }
func (m *Assets) String() string { return proto.CompactTextString(m) }
func (*Assets) ProtoMessage()    {}
func (*Assets) Descriptor() ([]byte, []int) {
	return fileDescriptor_6ef1468f19ab6b2e, []int{3}
}

func (m *Assets) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Assets.Unmarshal(m, b)
}
func (m *Assets) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Assets.Marshal(b, m, deterministic)
}
func (m *Assets) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Assets.Merge(m, src)
}
func (m *Assets) XXX_Size() int {
	return xxx_messageInfo_Assets.Size(m)
}
func (m *Assets) XXX_DiscardUnknown() {
	xxx_messageInfo_Assets.DiscardUnknown(m)
}

var xxx_messageInfo_Assets proto.InternalMessageInfo

func (m *Assets) GetAssets() []*AssetEntry {
	if m != nil {
		return m.Assets
	}
	return nil
}

// AssetBalance represents the total balance of a given asset for a party
type AssetBalance struct {
	Party                string   `protobuf:"bytes,1,opt,name=party,proto3" json:"party,omitempty"`
	Asset                string   `protobuf:"bytes,2,opt,name=asset,proto3" json:"asset,omitempty"`
	Balance              string   `protobuf:"bytes,3,opt,name=balance,proto3" json:"balance,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AssetBalance) Reset()         { *m = AssetBalance{} }
func (m *AssetBalance) String() string { return proto.CompactTextString(m) }
func (*AssetBalance) ProtoMessage()    {}
func (*AssetBalance) Descriptor() ([]byte, []int) {
	return fileDescriptor_6ef1468f19ab6b2e, []int{4}
}

func (m *AssetBalance) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AssetBalance.Unmarshal(m, b)
}
func (m *AssetBalance) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AssetBalance.Marshal(b, m, deterministic)
}
func (m *AssetBalance) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AssetBalance.Merge(m, src)
}
func (m *AssetBalance) XXX_Size() int {
	return xxx_messageInfo_AssetBalance.Size(m)
}
func (m *AssetBalance) XXX_DiscardUnknown() {
	xxx_messageInfo_AssetBalance.DiscardUnknown(m)
}

var xxx_messageInfo_AssetBalance proto.InternalMessageInfo

func (m *AssetBalance) GetParty() string {
	if m != nil {
		return m.Party
	}
	return ""
}

func (m *AssetBalance) GetAsset() string {
	if m != nil {
		return m.Asset
	}
	return ""
}

func (m *AssetBalance) GetBalance() string {
	if m != nil {
		return m.Balance
	}
	return ""
}

// Collateral contains the balances per party
type Collateral struct {
	Balances             []*AssetBalance `protobuf:"bytes,1,rep,name=balances,proto3" json:"balances,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Collateral) Reset()         { *m = Collateral{} }
func (m *Collateral) String() string { return proto.CompactTextString(m) }
func (*Collateral) ProtoMessage()    {}
func (*Collateral) Descriptor() ([]byte, []int) {
	return fileDescriptor_6ef1468f19ab6b2e, []int{5}
}

func (m *Collateral) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Collateral.Unmarshal(m, b)
}
func (m *Collateral) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Collateral.Marshal(b, m, deterministic)
}
func (m *Collateral) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Collateral.Merge(m, src)
}
func (m *Collateral) XXX_Size() int {
	return xxx_messageInfo_Collateral.Size(m)
}
func (m *Collateral) XXX_DiscardUnknown() {
	xxx_messageInfo_Collateral.DiscardUnknown(m)
}

var xxx_messageInfo_Collateral proto.InternalMessageInfo

func (m *Collateral) GetBalances() []*AssetBalance {
	if m != nil {
		return m.Balances
	}
	return nil
}

// NetParams contains all network parameters
type NetParams struct {
	Params               []*NetworkParameter `protobuf:"bytes,1,rep,name=params,proto3" json:"params,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *NetParams) Reset()         { *m = NetParams{} }
func (m *NetParams) String() string { return proto.CompactTextString(m) }
func (*NetParams) ProtoMessage()    {}
func (*NetParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_6ef1468f19ab6b2e, []int{6}
}

func (m *NetParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NetParams.Unmarshal(m, b)
}
func (m *NetParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NetParams.Marshal(b, m, deterministic)
}
func (m *NetParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NetParams.Merge(m, src)
}
func (m *NetParams) XXX_Size() int {
	return xxx_messageInfo_NetParams.Size(m)
}
func (m *NetParams) XXX_DiscardUnknown() {
	xxx_messageInfo_NetParams.DiscardUnknown(m)
}

var xxx_messageInfo_NetParams proto.InternalMessageInfo

func (m *NetParams) GetParams() []*NetworkParameter {
	if m != nil {
		return m.Params
	}
	return nil
}

// Proposals will contain all accepted proposals
type Proposals struct {
	Proposals            []*Proposal `protobuf:"bytes,1,rep,name=proposals,proto3" json:"proposals,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Proposals) Reset()         { *m = Proposals{} }
func (m *Proposals) String() string { return proto.CompactTextString(m) }
func (*Proposals) ProtoMessage()    {}
func (*Proposals) Descriptor() ([]byte, []int) {
	return fileDescriptor_6ef1468f19ab6b2e, []int{7}
}

func (m *Proposals) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Proposals.Unmarshal(m, b)
}
func (m *Proposals) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Proposals.Marshal(b, m, deterministic)
}
func (m *Proposals) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Proposals.Merge(m, src)
}
func (m *Proposals) XXX_Size() int {
	return xxx_messageInfo_Proposals.Size(m)
}
func (m *Proposals) XXX_DiscardUnknown() {
	xxx_messageInfo_Proposals.DiscardUnknown(m)
}

var xxx_messageInfo_Proposals proto.InternalMessageInfo

func (m *Proposals) GetProposals() []*Proposal {
	if m != nil {
		return m.Proposals
	}
	return nil
}

func init() {
	proto.RegisterType((*Snapshot)(nil), "vega.Snapshot")
	proto.RegisterType((*Checkpoint)(nil), "vega.Checkpoint")
	proto.RegisterType((*AssetEntry)(nil), "vega.AssetEntry")
	proto.RegisterType((*Assets)(nil), "vega.Assets")
	proto.RegisterType((*AssetBalance)(nil), "vega.AssetBalance")
	proto.RegisterType((*Collateral)(nil), "vega.Collateral")
	proto.RegisterType((*NetParams)(nil), "vega.NetParams")
	proto.RegisterType((*Proposals)(nil), "vega.Proposals")
}

func init() { proto.RegisterFile("vega/snapshot.proto", fileDescriptor_6ef1468f19ab6b2e) }

var fileDescriptor_6ef1468f19ab6b2e = []byte{
	// 403 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x52, 0x4d, 0xab, 0xd3, 0x40,
	0x14, 0x25, 0x7d, 0x7d, 0xf1, 0xe5, 0x36, 0x56, 0x3b, 0xd6, 0x12, 0xba, 0x90, 0x30, 0xab, 0x2c,
	0x34, 0x85, 0x2a, 0x88, 0xe8, 0xa6, 0xad, 0x6e, 0x4b, 0x19, 0x75, 0xe3, 0xa6, 0x4c, 0x93, 0xa1,
	0x09, 0x8d, 0x99, 0x30, 0x33, 0x54, 0xfa, 0x3b, 0xfc, 0xc3, 0x92, 0x3b, 0x93, 0x26, 0xb8, 0x09,
	0x39, 0xe7, 0x9e, 0x73, 0x3f, 0x0e, 0x03, 0xaf, 0xae, 0xe2, 0xcc, 0x57, 0xba, 0xe6, 0x8d, 0x2e,
	0xa4, 0x49, 0x1b, 0x25, 0x8d, 0x24, 0xe3, 0x96, 0x5c, 0xbe, 0xc0, 0x52, 0xfb, 0xb1, 0xf4, 0x72,
	0x86, 0x04, 0xd7, 0x5a, 0x18, 0xed, 0xa8, 0xd7, 0x48, 0x9d, 0xe5, 0x55, 0xa8, 0x9a, 0xd7, 0x99,
	0xb0, 0x34, 0xfd, 0x00, 0x4f, 0xdf, 0x5d, 0x4b, 0x42, 0x60, 0x5c, 0x70, 0x5d, 0x44, 0x5e, 0xec,
	0x25, 0x01, 0xc3, 0x7f, 0x32, 0x87, 0x47, 0x6d, 0xb8, 0x11, 0xd1, 0x28, 0xf6, 0x92, 0x90, 0x59,
	0x40, 0xff, 0x7a, 0x00, 0xbb, 0x42, 0x64, 0x97, 0x46, 0x96, 0xb5, 0x21, 0x6f, 0x00, 0xfa, 0xc6,
	0x68, 0x0f, 0xd9, 0x80, 0x21, 0x0b, 0xf0, 0xed, 0x2e, 0xae, 0x8b, 0x43, 0xad, 0x2f, 0x93, 0x55,
	0xc5, 0x8d, 0x50, 0xbc, 0x8a, 0x1e, 0xac, 0xaf, 0x67, 0xc8, 0x3b, 0x20, 0xb5, 0x30, 0x7f, 0xa4,
	0xba, 0x1c, 0x1b, 0xae, 0xf8, 0x6f, 0x61, 0x84, 0xd2, 0xd1, 0x18, 0x75, 0x33, 0x57, 0x39, 0xdc,
	0x0b, 0xf4, 0x27, 0xc0, 0xa6, 0x6d, 0xfc, 0xad, 0x36, 0xea, 0x46, 0xa6, 0x30, 0x2a, 0x73, 0x77,
	0xcb, 0xa8, 0xcc, 0xc9, 0x47, 0x78, 0x8e, 0x63, 0x8f, 0xb9, 0x30, 0xbc, 0xac, 0xec, 0x2e, 0x93,
	0x35, 0x49, 0x31, 0x37, 0x34, 0x7e, 0xb5, 0x15, 0x16, 0xf2, 0x01, 0xa2, 0x6b, 0xf0, 0x37, 0x76,
	0xdf, 0xe4, 0x7e, 0x87, 0x17, 0x3f, 0x24, 0x93, 0xf5, 0xcb, 0x81, 0x17, 0x87, 0x76, 0x97, 0xd1,
	0x1f, 0x10, 0x22, 0xbb, 0xe5, 0x15, 0x26, 0x30, 0x87, 0xc7, 0x86, 0x2b, 0x73, 0x73, 0xfb, 0x58,
	0xd0, 0xb2, 0xa8, 0xc7, 0x55, 0x02, 0x66, 0x01, 0x89, 0xe0, 0xd9, 0xc9, 0xda, 0x30, 0x92, 0x80,
	0x75, 0x90, 0x7e, 0x01, 0xd8, 0xf5, 0xe9, 0xa4, 0xf0, 0xe4, 0x0a, 0xdd, 0x3e, 0xc3, 0x5b, 0xdc,
	0x64, 0x76, 0xd7, 0xd0, 0xcf, 0x10, 0xec, 0x85, 0xc1, 0xbc, 0x34, 0x49, 0xc1, 0xc7, 0x48, 0x3b,
	0xeb, 0xc2, 0x5a, 0xf7, 0xff, 0x85, 0xca, 0x9c, 0x8a, 0x7e, 0x82, 0xe0, 0xa0, 0x64, 0x23, 0x35,
	0xaf, 0x34, 0x79, 0x0b, 0x41, 0xd3, 0x01, 0xe7, 0x9f, 0x5a, 0x7f, 0xa7, 0x61, 0xbd, 0x60, 0x4b,
	0x7f, 0xc5, 0x99, 0xcc, 0x05, 0x0a, 0xf0, 0xd1, 0x65, 0xb2, 0x4a, 0x4b, 0xb9, 0xc2, 0x7f, 0x8d,
	0xcf, 0xf6, 0xe4, 0x23, 0x78, 0xff, 0x2f, 0x00, 0x00, 0xff, 0xff, 0x15, 0x80, 0x66, 0x70, 0xe5,
	0x02, 0x00, 0x00,
}
