// Code generated by protoc-gen-go. DO NOT EDIT.
// source: vega/events/v1/events.proto

package v1

import (
	vega "code.vegaprotocol.io/protos/vega"
	v1 "code.vegaprotocol.io/protos/vega/commands/v1"
	v11 "code.vegaprotocol.io/protos/vega/oracles/v1"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// An (event) bus event type is used to specify a type of event
// It has 2 styles of event:
// Single values (e.g. BUS_EVENT_TYPE_ORDER) where they represent one data item
// Group values (e.g. BUS_EVENT_TYPE_AUCTION) where they represent a group of data items
type BusEventType int32

const (
	// Default value, always invalid
	BusEventType_BUS_EVENT_TYPE_UNSPECIFIED BusEventType = 0
	// Events of ALL event types, used when filtering stream from event bus
	BusEventType_BUS_EVENT_TYPE_ALL BusEventType = 1
	// Event for blockchain time updates
	BusEventType_BUS_EVENT_TYPE_TIME_UPDATE BusEventType = 2
	// Event for when a transfer happens internally, contains the transfer information
	BusEventType_BUS_EVENT_TYPE_TRANSFER_RESPONSES BusEventType = 3
	// Event indicating position resolution has occurred
	BusEventType_BUS_EVENT_TYPE_POSITION_RESOLUTION BusEventType = 4
	// Event for order updates, both new and existing orders
	BusEventType_BUS_EVENT_TYPE_ORDER BusEventType = 5
	// Event for account updates
	BusEventType_BUS_EVENT_TYPE_ACCOUNT BusEventType = 6
	// Event for party updates
	BusEventType_BUS_EVENT_TYPE_PARTY BusEventType = 7
	// Event indicating a new trade has occurred
	BusEventType_BUS_EVENT_TYPE_TRADE BusEventType = 8
	// Event indicating margin levels have changed for a party
	BusEventType_BUS_EVENT_TYPE_MARGIN_LEVELS BusEventType = 9
	// Event for proposal updates (for governance)
	BusEventType_BUS_EVENT_TYPE_PROPOSAL BusEventType = 10
	// Event indicating a new vote has occurred (for governance)
	BusEventType_BUS_EVENT_TYPE_VOTE BusEventType = 11
	// Event for market data updates
	BusEventType_BUS_EVENT_TYPE_MARKET_DATA BusEventType = 12
	// Event for a new signature for a Vega node
	BusEventType_BUS_EVENT_TYPE_NODE_SIGNATURE BusEventType = 13
	// Event indicating loss socialisation occurred for a party
	BusEventType_BUS_EVENT_TYPE_LOSS_SOCIALIZATION BusEventType = 14
	// Event for when a position is being settled
	BusEventType_BUS_EVENT_TYPE_SETTLE_POSITION BusEventType = 15
	// Event for when a position is distressed
	BusEventType_BUS_EVENT_TYPE_SETTLE_DISTRESSED BusEventType = 16
	// Event indicating a new market was created
	BusEventType_BUS_EVENT_TYPE_MARKET_CREATED BusEventType = 17
	// Event for when an asset is added to Vega
	BusEventType_BUS_EVENT_TYPE_ASSET BusEventType = 18
	// Event indicating a market tick event
	BusEventType_BUS_EVENT_TYPE_MARKET_TICK BusEventType = 19
	// Event for when a withdrawal occurs
	BusEventType_BUS_EVENT_TYPE_WITHDRAWAL BusEventType = 20
	// Event for when a deposit occurs
	BusEventType_BUS_EVENT_TYPE_DEPOSIT BusEventType = 21
	// Event indicating a change in auction state, for example starting or ending an auction
	BusEventType_BUS_EVENT_TYPE_AUCTION BusEventType = 22
	// Event indicating a risk factor has been updated
	BusEventType_BUS_EVENT_TYPE_RISK_FACTOR BusEventType = 23
	// Event indicating a network parameter has been added or updated
	BusEventType_BUS_EVENT_TYPE_NETWORK_PARAMETER BusEventType = 24
	// Event indicating a liquidity provision has been created or updated
	BusEventType_BUS_EVENT_TYPE_LIQUIDITY_PROVISION BusEventType = 25
	// Event indicating a new market was created
	BusEventType_BUS_EVENT_TYPE_MARKET_UPDATED BusEventType = 26
	// Event indicating an oracle spec has been created or updated
	BusEventType_BUS_EVENT_TYPE_ORACLE_SPEC BusEventType = 27
	// Event indicating that an oracle data has been broadcast
	BusEventType_BUS_EVENT_TYPE_ORACLE_DATA BusEventType = 28
	// Event indicating that an delegation balance of a party to a node for current epoch has changed
	BusEventType_BUS_EVENT_TYPE_DELEGATION_BALANCE BusEventType = 29
	// Event indicating the validator score for the given epoch
	BusEventType_BUS_EVENT_TYPE_VALIDATOR_SCORE BusEventType = 30
	// Event indicating the start or end of an epoch
	BusEventType_BUS_EVENT_TYPE_EPOCH_UPDATE BusEventType = 31
	// Event indicating that validator node has been updated
	BusEventType_BUS_EVENT_TYPE_VALIDATOR_UPDATE BusEventType = 32
	// Event indicating a new staking event have been processed by the network
	BusEventType_BUS_EVENT_TYPE_STAKE_LINKING BusEventType = 33
	// Event indicating the payout of a reward has been initiated
	BusEventType_BUS_EVENT_TYPE_REWARD_PAYOUT_EVENT BusEventType = 34
	// Event indicating a new checkpoint was created
	BusEventType_BUS_EVENT_TYPE_CHECKPOINT BusEventType = 35
	// Event indicating stream is starting
	BusEventType_BUS_EVENT_TYPE_STREAM_START BusEventType = 36
	// Event indicating key rotation took place
	BusEventType_BUS_EVENT_TYPE_KEY_ROTATION BusEventType = 37
	// Event indicating a market related event, for example when a market opens
	BusEventType_BUS_EVENT_TYPE_MARKET BusEventType = 101
	// Event used to report failed transactions back to a user, this is excluded from the ALL type
	BusEventType_BUS_EVENT_TYPE_TX_ERROR BusEventType = 201
)

var BusEventType_name = map[int32]string{
	0:   "BUS_EVENT_TYPE_UNSPECIFIED",
	1:   "BUS_EVENT_TYPE_ALL",
	2:   "BUS_EVENT_TYPE_TIME_UPDATE",
	3:   "BUS_EVENT_TYPE_TRANSFER_RESPONSES",
	4:   "BUS_EVENT_TYPE_POSITION_RESOLUTION",
	5:   "BUS_EVENT_TYPE_ORDER",
	6:   "BUS_EVENT_TYPE_ACCOUNT",
	7:   "BUS_EVENT_TYPE_PARTY",
	8:   "BUS_EVENT_TYPE_TRADE",
	9:   "BUS_EVENT_TYPE_MARGIN_LEVELS",
	10:  "BUS_EVENT_TYPE_PROPOSAL",
	11:  "BUS_EVENT_TYPE_VOTE",
	12:  "BUS_EVENT_TYPE_MARKET_DATA",
	13:  "BUS_EVENT_TYPE_NODE_SIGNATURE",
	14:  "BUS_EVENT_TYPE_LOSS_SOCIALIZATION",
	15:  "BUS_EVENT_TYPE_SETTLE_POSITION",
	16:  "BUS_EVENT_TYPE_SETTLE_DISTRESSED",
	17:  "BUS_EVENT_TYPE_MARKET_CREATED",
	18:  "BUS_EVENT_TYPE_ASSET",
	19:  "BUS_EVENT_TYPE_MARKET_TICK",
	20:  "BUS_EVENT_TYPE_WITHDRAWAL",
	21:  "BUS_EVENT_TYPE_DEPOSIT",
	22:  "BUS_EVENT_TYPE_AUCTION",
	23:  "BUS_EVENT_TYPE_RISK_FACTOR",
	24:  "BUS_EVENT_TYPE_NETWORK_PARAMETER",
	25:  "BUS_EVENT_TYPE_LIQUIDITY_PROVISION",
	26:  "BUS_EVENT_TYPE_MARKET_UPDATED",
	27:  "BUS_EVENT_TYPE_ORACLE_SPEC",
	28:  "BUS_EVENT_TYPE_ORACLE_DATA",
	29:  "BUS_EVENT_TYPE_DELEGATION_BALANCE",
	30:  "BUS_EVENT_TYPE_VALIDATOR_SCORE",
	31:  "BUS_EVENT_TYPE_EPOCH_UPDATE",
	32:  "BUS_EVENT_TYPE_VALIDATOR_UPDATE",
	33:  "BUS_EVENT_TYPE_STAKE_LINKING",
	34:  "BUS_EVENT_TYPE_REWARD_PAYOUT_EVENT",
	35:  "BUS_EVENT_TYPE_CHECKPOINT",
	36:  "BUS_EVENT_TYPE_STREAM_START",
	37:  "BUS_EVENT_TYPE_KEY_ROTATION",
	101: "BUS_EVENT_TYPE_MARKET",
	201: "BUS_EVENT_TYPE_TX_ERROR",
}

var BusEventType_value = map[string]int32{
	"BUS_EVENT_TYPE_UNSPECIFIED":         0,
	"BUS_EVENT_TYPE_ALL":                 1,
	"BUS_EVENT_TYPE_TIME_UPDATE":         2,
	"BUS_EVENT_TYPE_TRANSFER_RESPONSES":  3,
	"BUS_EVENT_TYPE_POSITION_RESOLUTION": 4,
	"BUS_EVENT_TYPE_ORDER":               5,
	"BUS_EVENT_TYPE_ACCOUNT":             6,
	"BUS_EVENT_TYPE_PARTY":               7,
	"BUS_EVENT_TYPE_TRADE":               8,
	"BUS_EVENT_TYPE_MARGIN_LEVELS":       9,
	"BUS_EVENT_TYPE_PROPOSAL":            10,
	"BUS_EVENT_TYPE_VOTE":                11,
	"BUS_EVENT_TYPE_MARKET_DATA":         12,
	"BUS_EVENT_TYPE_NODE_SIGNATURE":      13,
	"BUS_EVENT_TYPE_LOSS_SOCIALIZATION":  14,
	"BUS_EVENT_TYPE_SETTLE_POSITION":     15,
	"BUS_EVENT_TYPE_SETTLE_DISTRESSED":   16,
	"BUS_EVENT_TYPE_MARKET_CREATED":      17,
	"BUS_EVENT_TYPE_ASSET":               18,
	"BUS_EVENT_TYPE_MARKET_TICK":         19,
	"BUS_EVENT_TYPE_WITHDRAWAL":          20,
	"BUS_EVENT_TYPE_DEPOSIT":             21,
	"BUS_EVENT_TYPE_AUCTION":             22,
	"BUS_EVENT_TYPE_RISK_FACTOR":         23,
	"BUS_EVENT_TYPE_NETWORK_PARAMETER":   24,
	"BUS_EVENT_TYPE_LIQUIDITY_PROVISION": 25,
	"BUS_EVENT_TYPE_MARKET_UPDATED":      26,
	"BUS_EVENT_TYPE_ORACLE_SPEC":         27,
	"BUS_EVENT_TYPE_ORACLE_DATA":         28,
	"BUS_EVENT_TYPE_DELEGATION_BALANCE":  29,
	"BUS_EVENT_TYPE_VALIDATOR_SCORE":     30,
	"BUS_EVENT_TYPE_EPOCH_UPDATE":        31,
	"BUS_EVENT_TYPE_VALIDATOR_UPDATE":    32,
	"BUS_EVENT_TYPE_STAKE_LINKING":       33,
	"BUS_EVENT_TYPE_REWARD_PAYOUT_EVENT": 34,
	"BUS_EVENT_TYPE_CHECKPOINT":          35,
	"BUS_EVENT_TYPE_STREAM_START":        36,
	"BUS_EVENT_TYPE_KEY_ROTATION":        37,
	"BUS_EVENT_TYPE_MARKET":              101,
	"BUS_EVENT_TYPE_TX_ERROR":            201,
}

func (x BusEventType) String() string {
	return proto.EnumName(BusEventType_name, int32(x))
}

func (BusEventType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_2565b4e8491d341a, []int{0}
}

type StakeLinking_Type int32

const (
	// Default value
	StakeLinking_TYPE_UNSPECIFIED StakeLinking_Type = 0
	// Indicate of a stake deposit instruction
	StakeLinking_TYPE_LINK StakeLinking_Type = 1
	// Indicate of a stake remove instruction
	StakeLinking_TYPE_UNLINK StakeLinking_Type = 2
)

var StakeLinking_Type_name = map[int32]string{
	0: "TYPE_UNSPECIFIED",
	1: "TYPE_LINK",
	2: "TYPE_UNLINK",
}

var StakeLinking_Type_value = map[string]int32{
	"TYPE_UNSPECIFIED": 0,
	"TYPE_LINK":        1,
	"TYPE_UNLINK":      2,
}

func (x StakeLinking_Type) String() string {
	return proto.EnumName(StakeLinking_Type_name, int32(x))
}

func (StakeLinking_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_2565b4e8491d341a, []int{0, 0}
}

type StakeLinking_Status int32

const (
	// Default value
	StakeLinking_STATUS_UNSPECIFIED StakeLinking_Status = 0
	// Indicate an event waiting for confirmation from the vega network
	StakeLinking_STATUS_PENDING StakeLinking_Status = 1
	// Indicate of an event accepted by the vega network
	StakeLinking_STATUS_ACCEPTED StakeLinking_Status = 2
	// Indaicate of an event rejected by the vega network
	StakeLinking_STATUS_REJECTED StakeLinking_Status = 3
)

var StakeLinking_Status_name = map[int32]string{
	0: "STATUS_UNSPECIFIED",
	1: "STATUS_PENDING",
	2: "STATUS_ACCEPTED",
	3: "STATUS_REJECTED",
}

var StakeLinking_Status_value = map[string]int32{
	"STATUS_UNSPECIFIED": 0,
	"STATUS_PENDING":     1,
	"STATUS_ACCEPTED":    2,
	"STATUS_REJECTED":    3,
}

func (x StakeLinking_Status) String() string {
	return proto.EnumName(StakeLinking_Status_name, int32(x))
}

func (StakeLinking_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_2565b4e8491d341a, []int{0, 1}
}

// StakeLinking - an event notifying of stake being deposited or removed for a given party
// These events are emitted for every Staking deposit or removed accepted by the network
type StakeLinking struct {
	// The internal ID for this staking event
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// The type of event
	Type StakeLinking_Type `protobuf:"varint,2,opt,name=type,proto3,enum=vega.events.v1.StakeLinking_Type" json:"type,omitempty"`
	// The timestamps at which the event was emitted by ethereum
	Ts int64 `protobuf:"varint,3,opt,name=ts,proto3" json:"ts,omitempty"`
	// The party to whom the event is directed at.
	Party string `protobuf:"bytes,4,opt,name=party,proto3" json:"party,omitempty"`
	// The amount of stake deposited or removed
	Amount string `protobuf:"bytes,5,opt,name=amount,proto3" json:"amount,omitempty"`
	// The status of the event
	Status StakeLinking_Status `protobuf:"varint,6,opt,name=status,proto3,enum=vega.events.v1.StakeLinking_Status" json:"status,omitempty"`
	// The time at which the vega network finalized the state of the event
	FinalizedAt int64 `protobuf:"varint,7,opt,name=finalized_at,json=finalizedAt,proto3" json:"finalized_at,omitempty"`
	// The hash of the transaction from which the events happen
	TxHash               string   `protobuf:"bytes,8,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StakeLinking) Reset()         { *m = StakeLinking{} }
func (m *StakeLinking) String() string { return proto.CompactTextString(m) }
func (*StakeLinking) ProtoMessage()    {}
func (*StakeLinking) Descriptor() ([]byte, []int) {
	return fileDescriptor_2565b4e8491d341a, []int{0}
}

func (m *StakeLinking) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StakeLinking.Unmarshal(m, b)
}
func (m *StakeLinking) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StakeLinking.Marshal(b, m, deterministic)
}
func (m *StakeLinking) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StakeLinking.Merge(m, src)
}
func (m *StakeLinking) XXX_Size() int {
	return xxx_messageInfo_StakeLinking.Size(m)
}
func (m *StakeLinking) XXX_DiscardUnknown() {
	xxx_messageInfo_StakeLinking.DiscardUnknown(m)
}

var xxx_messageInfo_StakeLinking proto.InternalMessageInfo

func (m *StakeLinking) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *StakeLinking) GetType() StakeLinking_Type {
	if m != nil {
		return m.Type
	}
	return StakeLinking_TYPE_UNSPECIFIED
}

func (m *StakeLinking) GetTs() int64 {
	if m != nil {
		return m.Ts
	}
	return 0
}

func (m *StakeLinking) GetParty() string {
	if m != nil {
		return m.Party
	}
	return ""
}

func (m *StakeLinking) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

func (m *StakeLinking) GetStatus() StakeLinking_Status {
	if m != nil {
		return m.Status
	}
	return StakeLinking_STATUS_UNSPECIFIED
}

func (m *StakeLinking) GetFinalizedAt() int64 {
	if m != nil {
		return m.FinalizedAt
	}
	return 0
}

func (m *StakeLinking) GetTxHash() string {
	if m != nil {
		return m.TxHash
	}
	return ""
}

type CheckpointEvent struct {
	Hash                 string   `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	BlockHash            string   `protobuf:"bytes,2,opt,name=block_hash,json=blockHash,proto3" json:"block_hash,omitempty"`
	BlockHeight          uint64   `protobuf:"varint,3,opt,name=block_height,json=blockHeight,proto3" json:"block_height,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckpointEvent) Reset()         { *m = CheckpointEvent{} }
func (m *CheckpointEvent) String() string { return proto.CompactTextString(m) }
func (*CheckpointEvent) ProtoMessage()    {}
func (*CheckpointEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_2565b4e8491d341a, []int{1}
}

func (m *CheckpointEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckpointEvent.Unmarshal(m, b)
}
func (m *CheckpointEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckpointEvent.Marshal(b, m, deterministic)
}
func (m *CheckpointEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckpointEvent.Merge(m, src)
}
func (m *CheckpointEvent) XXX_Size() int {
	return xxx_messageInfo_CheckpointEvent.Size(m)
}
func (m *CheckpointEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckpointEvent.DiscardUnknown(m)
}

var xxx_messageInfo_CheckpointEvent proto.InternalMessageInfo

func (m *CheckpointEvent) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func (m *CheckpointEvent) GetBlockHash() string {
	if m != nil {
		return m.BlockHash
	}
	return ""
}

func (m *CheckpointEvent) GetBlockHeight() uint64 {
	if m != nil {
		return m.BlockHeight
	}
	return 0
}

type StreamStartEvent struct {
	ChainId              string   `protobuf:"bytes,1,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StreamStartEvent) Reset()         { *m = StreamStartEvent{} }
func (m *StreamStartEvent) String() string { return proto.CompactTextString(m) }
func (*StreamStartEvent) ProtoMessage()    {}
func (*StreamStartEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_2565b4e8491d341a, []int{2}
}

func (m *StreamStartEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamStartEvent.Unmarshal(m, b)
}
func (m *StreamStartEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamStartEvent.Marshal(b, m, deterministic)
}
func (m *StreamStartEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamStartEvent.Merge(m, src)
}
func (m *StreamStartEvent) XXX_Size() int {
	return xxx_messageInfo_StreamStartEvent.Size(m)
}
func (m *StreamStartEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamStartEvent.DiscardUnknown(m)
}

var xxx_messageInfo_StreamStartEvent proto.InternalMessageInfo

func (m *StreamStartEvent) GetChainId() string {
	if m != nil {
		return m.ChainId
	}
	return ""
}

type RewardPayoutEvent struct {
	Party                string   `protobuf:"bytes,1,opt,name=party,proto3" json:"party,omitempty"`
	EpochSeq             string   `protobuf:"bytes,2,opt,name=epoch_seq,json=epochSeq,proto3" json:"epoch_seq,omitempty"`
	Asset                string   `protobuf:"bytes,3,opt,name=asset,proto3" json:"asset,omitempty"`
	Amount               string   `protobuf:"bytes,4,opt,name=amount,proto3" json:"amount,omitempty"`
	PercentOfTotalReward string   `protobuf:"bytes,5,opt,name=percent_of_total_reward,json=percentOfTotalReward,proto3" json:"percent_of_total_reward,omitempty"`
	Timestamp            int64    `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RewardPayoutEvent) Reset()         { *m = RewardPayoutEvent{} }
func (m *RewardPayoutEvent) String() string { return proto.CompactTextString(m) }
func (*RewardPayoutEvent) ProtoMessage()    {}
func (*RewardPayoutEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_2565b4e8491d341a, []int{3}
}

func (m *RewardPayoutEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RewardPayoutEvent.Unmarshal(m, b)
}
func (m *RewardPayoutEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RewardPayoutEvent.Marshal(b, m, deterministic)
}
func (m *RewardPayoutEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RewardPayoutEvent.Merge(m, src)
}
func (m *RewardPayoutEvent) XXX_Size() int {
	return xxx_messageInfo_RewardPayoutEvent.Size(m)
}
func (m *RewardPayoutEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_RewardPayoutEvent.DiscardUnknown(m)
}

var xxx_messageInfo_RewardPayoutEvent proto.InternalMessageInfo

func (m *RewardPayoutEvent) GetParty() string {
	if m != nil {
		return m.Party
	}
	return ""
}

func (m *RewardPayoutEvent) GetEpochSeq() string {
	if m != nil {
		return m.EpochSeq
	}
	return ""
}

func (m *RewardPayoutEvent) GetAsset() string {
	if m != nil {
		return m.Asset
	}
	return ""
}

func (m *RewardPayoutEvent) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

func (m *RewardPayoutEvent) GetPercentOfTotalReward() string {
	if m != nil {
		return m.PercentOfTotalReward
	}
	return ""
}

func (m *RewardPayoutEvent) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

//ValidatorScoreEvent is the score a validator gets for a given epoch
type ValidatorScoreEvent struct {
	NodeId               string   `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	EpochSeq             string   `protobuf:"bytes,2,opt,name=epoch_seq,json=epochSeq,proto3" json:"epoch_seq,omitempty"`
	ValidatorScore       string   `protobuf:"bytes,3,opt,name=validator_score,json=validatorScore,proto3" json:"validator_score,omitempty"`
	NormalisedScore      string   `protobuf:"bytes,4,opt,name=normalised_score,json=normalisedScore,proto3" json:"normalised_score,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ValidatorScoreEvent) Reset()         { *m = ValidatorScoreEvent{} }
func (m *ValidatorScoreEvent) String() string { return proto.CompactTextString(m) }
func (*ValidatorScoreEvent) ProtoMessage()    {}
func (*ValidatorScoreEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_2565b4e8491d341a, []int{4}
}

func (m *ValidatorScoreEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValidatorScoreEvent.Unmarshal(m, b)
}
func (m *ValidatorScoreEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValidatorScoreEvent.Marshal(b, m, deterministic)
}
func (m *ValidatorScoreEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidatorScoreEvent.Merge(m, src)
}
func (m *ValidatorScoreEvent) XXX_Size() int {
	return xxx_messageInfo_ValidatorScoreEvent.Size(m)
}
func (m *ValidatorScoreEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidatorScoreEvent.DiscardUnknown(m)
}

var xxx_messageInfo_ValidatorScoreEvent proto.InternalMessageInfo

func (m *ValidatorScoreEvent) GetNodeId() string {
	if m != nil {
		return m.NodeId
	}
	return ""
}

func (m *ValidatorScoreEvent) GetEpochSeq() string {
	if m != nil {
		return m.EpochSeq
	}
	return ""
}

func (m *ValidatorScoreEvent) GetValidatorScore() string {
	if m != nil {
		return m.ValidatorScore
	}
	return ""
}

func (m *ValidatorScoreEvent) GetNormalisedScore() string {
	if m != nil {
		return m.NormalisedScore
	}
	return ""
}

//DelegationBalanceEvent - updates on the delegation balance of a party to a node in the current epoch in effect
type DelegationBalanceEvent struct {
	Party                string   `protobuf:"bytes,1,opt,name=party,proto3" json:"party,omitempty"`
	NodeId               string   `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Amount               string   `protobuf:"bytes,3,opt,name=amount,proto3" json:"amount,omitempty"`
	EpochSeq             string   `protobuf:"bytes,4,opt,name=epoch_seq,json=epochSeq,proto3" json:"epoch_seq,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DelegationBalanceEvent) Reset()         { *m = DelegationBalanceEvent{} }
func (m *DelegationBalanceEvent) String() string { return proto.CompactTextString(m) }
func (*DelegationBalanceEvent) ProtoMessage()    {}
func (*DelegationBalanceEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_2565b4e8491d341a, []int{5}
}

func (m *DelegationBalanceEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DelegationBalanceEvent.Unmarshal(m, b)
}
func (m *DelegationBalanceEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DelegationBalanceEvent.Marshal(b, m, deterministic)
}
func (m *DelegationBalanceEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DelegationBalanceEvent.Merge(m, src)
}
func (m *DelegationBalanceEvent) XXX_Size() int {
	return xxx_messageInfo_DelegationBalanceEvent.Size(m)
}
func (m *DelegationBalanceEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_DelegationBalanceEvent.DiscardUnknown(m)
}

var xxx_messageInfo_DelegationBalanceEvent proto.InternalMessageInfo

func (m *DelegationBalanceEvent) GetParty() string {
	if m != nil {
		return m.Party
	}
	return ""
}

func (m *DelegationBalanceEvent) GetNodeId() string {
	if m != nil {
		return m.NodeId
	}
	return ""
}

func (m *DelegationBalanceEvent) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

func (m *DelegationBalanceEvent) GetEpochSeq() string {
	if m != nil {
		return m.EpochSeq
	}
	return ""
}

// MarketEvent - the common denominator for all market events
// interface has a method to return a string for logging
type MarketEvent struct {
	// Market identifier for the event
	MarketId string `protobuf:"bytes,1,opt,name=market_id,json=marketId,proto3" json:"market_id,omitempty"`
	// Payload is a unique information string
	Payload              string   `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MarketEvent) Reset()         { *m = MarketEvent{} }
func (m *MarketEvent) String() string { return proto.CompactTextString(m) }
func (*MarketEvent) ProtoMessage()    {}
func (*MarketEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_2565b4e8491d341a, []int{6}
}

func (m *MarketEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MarketEvent.Unmarshal(m, b)
}
func (m *MarketEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MarketEvent.Marshal(b, m, deterministic)
}
func (m *MarketEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MarketEvent.Merge(m, src)
}
func (m *MarketEvent) XXX_Size() int {
	return xxx_messageInfo_MarketEvent.Size(m)
}
func (m *MarketEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_MarketEvent.DiscardUnknown(m)
}

var xxx_messageInfo_MarketEvent proto.InternalMessageInfo

func (m *MarketEvent) GetMarketId() string {
	if m != nil {
		return m.MarketId
	}
	return ""
}

func (m *MarketEvent) GetPayload() string {
	if m != nil {
		return m.Payload
	}
	return ""
}

type TxErrorEvent struct {
	// Unique party identifier for the related party
	PartyId string `protobuf:"bytes,1,opt,name=party_id,json=partyId,proto3" json:"party_id,omitempty"`
	// An error message describing what went wrong
	ErrMsg string `protobuf:"bytes,2,opt,name=err_msg,json=errMsg,proto3" json:"err_msg,omitempty"`
	// The transaction that failed
	//
	// Types that are valid to be assigned to Transaction:
	//	*TxErrorEvent_OrderSubmission
	//	*TxErrorEvent_OrderAmendment
	//	*TxErrorEvent_OrderCancellation
	//	*TxErrorEvent_Proposal
	//	*TxErrorEvent_VoteSubmission
	//	*TxErrorEvent_LiquidityProvisionSubmission
	//	*TxErrorEvent_WithdrawSubmission
	//	*TxErrorEvent_DelegateSubmission
	//	*TxErrorEvent_UndelegateSubmission
	//	*TxErrorEvent_RestoreSnapshot
	Transaction          isTxErrorEvent_Transaction `protobuf_oneof:"transaction"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *TxErrorEvent) Reset()         { *m = TxErrorEvent{} }
func (m *TxErrorEvent) String() string { return proto.CompactTextString(m) }
func (*TxErrorEvent) ProtoMessage()    {}
func (*TxErrorEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_2565b4e8491d341a, []int{7}
}

func (m *TxErrorEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TxErrorEvent.Unmarshal(m, b)
}
func (m *TxErrorEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TxErrorEvent.Marshal(b, m, deterministic)
}
func (m *TxErrorEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TxErrorEvent.Merge(m, src)
}
func (m *TxErrorEvent) XXX_Size() int {
	return xxx_messageInfo_TxErrorEvent.Size(m)
}
func (m *TxErrorEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_TxErrorEvent.DiscardUnknown(m)
}

var xxx_messageInfo_TxErrorEvent proto.InternalMessageInfo

func (m *TxErrorEvent) GetPartyId() string {
	if m != nil {
		return m.PartyId
	}
	return ""
}

func (m *TxErrorEvent) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

type isTxErrorEvent_Transaction interface {
	isTxErrorEvent_Transaction()
}

type TxErrorEvent_OrderSubmission struct {
	OrderSubmission *v1.OrderSubmission `protobuf:"bytes,101,opt,name=order_submission,json=orderSubmission,proto3,oneof"`
}

type TxErrorEvent_OrderAmendment struct {
	OrderAmendment *v1.OrderAmendment `protobuf:"bytes,102,opt,name=order_amendment,json=orderAmendment,proto3,oneof"`
}

type TxErrorEvent_OrderCancellation struct {
	OrderCancellation *v1.OrderCancellation `protobuf:"bytes,103,opt,name=order_cancellation,json=orderCancellation,proto3,oneof"`
}

type TxErrorEvent_Proposal struct {
	Proposal *v1.ProposalSubmission `protobuf:"bytes,104,opt,name=proposal,proto3,oneof"`
}

type TxErrorEvent_VoteSubmission struct {
	VoteSubmission *v1.VoteSubmission `protobuf:"bytes,105,opt,name=vote_submission,json=voteSubmission,proto3,oneof"`
}

type TxErrorEvent_LiquidityProvisionSubmission struct {
	LiquidityProvisionSubmission *v1.LiquidityProvisionSubmission `protobuf:"bytes,106,opt,name=liquidity_provision_submission,json=liquidityProvisionSubmission,proto3,oneof"`
}

type TxErrorEvent_WithdrawSubmission struct {
	WithdrawSubmission *v1.WithdrawSubmission `protobuf:"bytes,107,opt,name=withdraw_submission,json=withdrawSubmission,proto3,oneof"`
}

type TxErrorEvent_DelegateSubmission struct {
	DelegateSubmission *v1.DelegateSubmission `protobuf:"bytes,108,opt,name=delegate_submission,json=delegateSubmission,proto3,oneof"`
}

type TxErrorEvent_UndelegateSubmission struct {
	UndelegateSubmission *v1.UndelegateSubmission `protobuf:"bytes,109,opt,name=undelegate_submission,json=undelegateSubmission,proto3,oneof"`
}

type TxErrorEvent_RestoreSnapshot struct {
	RestoreSnapshot *v1.RestoreSnapshot `protobuf:"bytes,110,opt,name=restore_snapshot,json=restoreSnapshot,proto3,oneof"`
}

func (*TxErrorEvent_OrderSubmission) isTxErrorEvent_Transaction() {}

func (*TxErrorEvent_OrderAmendment) isTxErrorEvent_Transaction() {}

func (*TxErrorEvent_OrderCancellation) isTxErrorEvent_Transaction() {}

func (*TxErrorEvent_Proposal) isTxErrorEvent_Transaction() {}

func (*TxErrorEvent_VoteSubmission) isTxErrorEvent_Transaction() {}

func (*TxErrorEvent_LiquidityProvisionSubmission) isTxErrorEvent_Transaction() {}

func (*TxErrorEvent_WithdrawSubmission) isTxErrorEvent_Transaction() {}

func (*TxErrorEvent_DelegateSubmission) isTxErrorEvent_Transaction() {}

func (*TxErrorEvent_UndelegateSubmission) isTxErrorEvent_Transaction() {}

func (*TxErrorEvent_RestoreSnapshot) isTxErrorEvent_Transaction() {}

func (m *TxErrorEvent) GetTransaction() isTxErrorEvent_Transaction {
	if m != nil {
		return m.Transaction
	}
	return nil
}

func (m *TxErrorEvent) GetOrderSubmission() *v1.OrderSubmission {
	if x, ok := m.GetTransaction().(*TxErrorEvent_OrderSubmission); ok {
		return x.OrderSubmission
	}
	return nil
}

func (m *TxErrorEvent) GetOrderAmendment() *v1.OrderAmendment {
	if x, ok := m.GetTransaction().(*TxErrorEvent_OrderAmendment); ok {
		return x.OrderAmendment
	}
	return nil
}

func (m *TxErrorEvent) GetOrderCancellation() *v1.OrderCancellation {
	if x, ok := m.GetTransaction().(*TxErrorEvent_OrderCancellation); ok {
		return x.OrderCancellation
	}
	return nil
}

func (m *TxErrorEvent) GetProposal() *v1.ProposalSubmission {
	if x, ok := m.GetTransaction().(*TxErrorEvent_Proposal); ok {
		return x.Proposal
	}
	return nil
}

func (m *TxErrorEvent) GetVoteSubmission() *v1.VoteSubmission {
	if x, ok := m.GetTransaction().(*TxErrorEvent_VoteSubmission); ok {
		return x.VoteSubmission
	}
	return nil
}

func (m *TxErrorEvent) GetLiquidityProvisionSubmission() *v1.LiquidityProvisionSubmission {
	if x, ok := m.GetTransaction().(*TxErrorEvent_LiquidityProvisionSubmission); ok {
		return x.LiquidityProvisionSubmission
	}
	return nil
}

func (m *TxErrorEvent) GetWithdrawSubmission() *v1.WithdrawSubmission {
	if x, ok := m.GetTransaction().(*TxErrorEvent_WithdrawSubmission); ok {
		return x.WithdrawSubmission
	}
	return nil
}

func (m *TxErrorEvent) GetDelegateSubmission() *v1.DelegateSubmission {
	if x, ok := m.GetTransaction().(*TxErrorEvent_DelegateSubmission); ok {
		return x.DelegateSubmission
	}
	return nil
}

func (m *TxErrorEvent) GetUndelegateSubmission() *v1.UndelegateSubmission {
	if x, ok := m.GetTransaction().(*TxErrorEvent_UndelegateSubmission); ok {
		return x.UndelegateSubmission
	}
	return nil
}

func (m *TxErrorEvent) GetRestoreSnapshot() *v1.RestoreSnapshot {
	if x, ok := m.GetTransaction().(*TxErrorEvent_RestoreSnapshot); ok {
		return x.RestoreSnapshot
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*TxErrorEvent) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*TxErrorEvent_OrderSubmission)(nil),
		(*TxErrorEvent_OrderAmendment)(nil),
		(*TxErrorEvent_OrderCancellation)(nil),
		(*TxErrorEvent_Proposal)(nil),
		(*TxErrorEvent_VoteSubmission)(nil),
		(*TxErrorEvent_LiquidityProvisionSubmission)(nil),
		(*TxErrorEvent_WithdrawSubmission)(nil),
		(*TxErrorEvent_DelegateSubmission)(nil),
		(*TxErrorEvent_UndelegateSubmission)(nil),
		(*TxErrorEvent_RestoreSnapshot)(nil),
	}
}

// A time update event contains the latest time update from Vega blockchain
type TimeUpdate struct {
	// Timestamp containing latest update from Vega blockchain aka Vega-time
	Timestamp            int64    `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TimeUpdate) Reset()         { *m = TimeUpdate{} }
func (m *TimeUpdate) String() string { return proto.CompactTextString(m) }
func (*TimeUpdate) ProtoMessage()    {}
func (*TimeUpdate) Descriptor() ([]byte, []int) {
	return fileDescriptor_2565b4e8491d341a, []int{8}
}

func (m *TimeUpdate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TimeUpdate.Unmarshal(m, b)
}
func (m *TimeUpdate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TimeUpdate.Marshal(b, m, deterministic)
}
func (m *TimeUpdate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TimeUpdate.Merge(m, src)
}
func (m *TimeUpdate) XXX_Size() int {
	return xxx_messageInfo_TimeUpdate.Size(m)
}
func (m *TimeUpdate) XXX_DiscardUnknown() {
	xxx_messageInfo_TimeUpdate.DiscardUnknown(m)
}

var xxx_messageInfo_TimeUpdate proto.InternalMessageInfo

func (m *TimeUpdate) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

// Epoch details
type EpochEvent struct {
	// Sequence number that increases by one each epoch
	Seq uint64 `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`
	// Action tells us what action is taking place
	Action vega.EpochAction `protobuf:"varint,2,opt,name=action,proto3,enum=vega.EpochAction" json:"action,omitempty"`
	// What time did this epoch start
	StartTime int64 `protobuf:"varint,3,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	// What time should this epoch end
	ExpireTime int64 `protobuf:"varint,4,opt,name=expire_time,json=expireTime,proto3" json:"expire_time,omitempty"`
	// What time did it actually end
	EndTime              int64    `protobuf:"varint,5,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EpochEvent) Reset()         { *m = EpochEvent{} }
func (m *EpochEvent) String() string { return proto.CompactTextString(m) }
func (*EpochEvent) ProtoMessage()    {}
func (*EpochEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_2565b4e8491d341a, []int{9}
}

func (m *EpochEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EpochEvent.Unmarshal(m, b)
}
func (m *EpochEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EpochEvent.Marshal(b, m, deterministic)
}
func (m *EpochEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EpochEvent.Merge(m, src)
}
func (m *EpochEvent) XXX_Size() int {
	return xxx_messageInfo_EpochEvent.Size(m)
}
func (m *EpochEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_EpochEvent.DiscardUnknown(m)
}

var xxx_messageInfo_EpochEvent proto.InternalMessageInfo

func (m *EpochEvent) GetSeq() uint64 {
	if m != nil {
		return m.Seq
	}
	return 0
}

func (m *EpochEvent) GetAction() vega.EpochAction {
	if m != nil {
		return m.Action
	}
	return vega.EpochAction_EPOCH_ACTION_UNSPECIFIED
}

func (m *EpochEvent) GetStartTime() int64 {
	if m != nil {
		return m.StartTime
	}
	return 0
}

func (m *EpochEvent) GetExpireTime() int64 {
	if m != nil {
		return m.ExpireTime
	}
	return 0
}

func (m *EpochEvent) GetEndTime() int64 {
	if m != nil {
		return m.EndTime
	}
	return 0
}

// A transfer responses event contains a collection of transfer information
type TransferResponses struct {
	// One or more entries containing internal transfer information
	Responses            []*vega.TransferResponse `protobuf:"bytes,1,rep,name=responses,proto3" json:"responses,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *TransferResponses) Reset()         { *m = TransferResponses{} }
func (m *TransferResponses) String() string { return proto.CompactTextString(m) }
func (*TransferResponses) ProtoMessage()    {}
func (*TransferResponses) Descriptor() ([]byte, []int) {
	return fileDescriptor_2565b4e8491d341a, []int{10}
}

func (m *TransferResponses) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransferResponses.Unmarshal(m, b)
}
func (m *TransferResponses) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransferResponses.Marshal(b, m, deterministic)
}
func (m *TransferResponses) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransferResponses.Merge(m, src)
}
func (m *TransferResponses) XXX_Size() int {
	return xxx_messageInfo_TransferResponses.Size(m)
}
func (m *TransferResponses) XXX_DiscardUnknown() {
	xxx_messageInfo_TransferResponses.DiscardUnknown(m)
}

var xxx_messageInfo_TransferResponses proto.InternalMessageInfo

func (m *TransferResponses) GetResponses() []*vega.TransferResponse {
	if m != nil {
		return m.Responses
	}
	return nil
}

// A position resolution event contains information on distressed trades
type PositionResolution struct {
	// Market identifier for the event
	MarketId string `protobuf:"bytes,1,opt,name=market_id,json=marketId,proto3" json:"market_id,omitempty"`
	// Number of distressed traders
	Distressed int64 `protobuf:"varint,2,opt,name=distressed,proto3" json:"distressed,omitempty"`
	// Number of close outs
	Closed int64 `protobuf:"varint,3,opt,name=closed,proto3" json:"closed,omitempty"`
	// Mark price as a string representing a scaled price
	MarkPrice            string   `protobuf:"bytes,4,opt,name=mark_price,json=markPrice,proto3" json:"mark_price,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PositionResolution) Reset()         { *m = PositionResolution{} }
func (m *PositionResolution) String() string { return proto.CompactTextString(m) }
func (*PositionResolution) ProtoMessage()    {}
func (*PositionResolution) Descriptor() ([]byte, []int) {
	return fileDescriptor_2565b4e8491d341a, []int{11}
}

func (m *PositionResolution) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PositionResolution.Unmarshal(m, b)
}
func (m *PositionResolution) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PositionResolution.Marshal(b, m, deterministic)
}
func (m *PositionResolution) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PositionResolution.Merge(m, src)
}
func (m *PositionResolution) XXX_Size() int {
	return xxx_messageInfo_PositionResolution.Size(m)
}
func (m *PositionResolution) XXX_DiscardUnknown() {
	xxx_messageInfo_PositionResolution.DiscardUnknown(m)
}

var xxx_messageInfo_PositionResolution proto.InternalMessageInfo

func (m *PositionResolution) GetMarketId() string {
	if m != nil {
		return m.MarketId
	}
	return ""
}

func (m *PositionResolution) GetDistressed() int64 {
	if m != nil {
		return m.Distressed
	}
	return 0
}

func (m *PositionResolution) GetClosed() int64 {
	if m != nil {
		return m.Closed
	}
	return 0
}

func (m *PositionResolution) GetMarkPrice() string {
	if m != nil {
		return m.MarkPrice
	}
	return ""
}

// A loss socialization event contains details on the amount of wins unable to be distributed
type LossSocialization struct {
	// Market identifier for the event
	MarketId string `protobuf:"bytes,1,opt,name=market_id,json=marketId,proto3" json:"market_id,omitempty"`
	// Party identifier (public key) for the event
	PartyId string `protobuf:"bytes,2,opt,name=party_id,json=partyId,proto3" json:"party_id,omitempty"`
	// Amount distributed
	Amount               string   `protobuf:"bytes,3,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LossSocialization) Reset()         { *m = LossSocialization{} }
func (m *LossSocialization) String() string { return proto.CompactTextString(m) }
func (*LossSocialization) ProtoMessage()    {}
func (*LossSocialization) Descriptor() ([]byte, []int) {
	return fileDescriptor_2565b4e8491d341a, []int{12}
}

func (m *LossSocialization) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LossSocialization.Unmarshal(m, b)
}
func (m *LossSocialization) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LossSocialization.Marshal(b, m, deterministic)
}
func (m *LossSocialization) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LossSocialization.Merge(m, src)
}
func (m *LossSocialization) XXX_Size() int {
	return xxx_messageInfo_LossSocialization.Size(m)
}
func (m *LossSocialization) XXX_DiscardUnknown() {
	xxx_messageInfo_LossSocialization.DiscardUnknown(m)
}

var xxx_messageInfo_LossSocialization proto.InternalMessageInfo

func (m *LossSocialization) GetMarketId() string {
	if m != nil {
		return m.MarketId
	}
	return ""
}

func (m *LossSocialization) GetPartyId() string {
	if m != nil {
		return m.PartyId
	}
	return ""
}

func (m *LossSocialization) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

// A trade settlement is part of the settle position event
type TradeSettlement struct {
	// Size of trade settlement
	Size int64 `protobuf:"varint,1,opt,name=size,proto3" json:"size,omitempty"`
	// Price of settlement as string
	Price                string   `protobuf:"bytes,2,opt,name=price,proto3" json:"price,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TradeSettlement) Reset()         { *m = TradeSettlement{} }
func (m *TradeSettlement) String() string { return proto.CompactTextString(m) }
func (*TradeSettlement) ProtoMessage()    {}
func (*TradeSettlement) Descriptor() ([]byte, []int) {
	return fileDescriptor_2565b4e8491d341a, []int{13}
}

func (m *TradeSettlement) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TradeSettlement.Unmarshal(m, b)
}
func (m *TradeSettlement) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TradeSettlement.Marshal(b, m, deterministic)
}
func (m *TradeSettlement) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TradeSettlement.Merge(m, src)
}
func (m *TradeSettlement) XXX_Size() int {
	return xxx_messageInfo_TradeSettlement.Size(m)
}
func (m *TradeSettlement) XXX_DiscardUnknown() {
	xxx_messageInfo_TradeSettlement.DiscardUnknown(m)
}

var xxx_messageInfo_TradeSettlement proto.InternalMessageInfo

func (m *TradeSettlement) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *TradeSettlement) GetPrice() string {
	if m != nil {
		return m.Price
	}
	return ""
}

// A settle position event contains position settlement information for a party
type SettlePosition struct {
	// Market identifier for the event
	MarketId string `protobuf:"bytes,1,opt,name=market_id,json=marketId,proto3" json:"market_id,omitempty"`
	// Party identifier (public key) for the event
	PartyId string `protobuf:"bytes,2,opt,name=party_id,json=partyId,proto3" json:"party_id,omitempty"`
	// Price of settlement as a string
	Price string `protobuf:"bytes,3,opt,name=price,proto3" json:"price,omitempty"`
	// A collection of 1 or more trade settlements
	TradeSettlements     []*TradeSettlement `protobuf:"bytes,4,rep,name=trade_settlements,json=tradeSettlements,proto3" json:"trade_settlements,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *SettlePosition) Reset()         { *m = SettlePosition{} }
func (m *SettlePosition) String() string { return proto.CompactTextString(m) }
func (*SettlePosition) ProtoMessage()    {}
func (*SettlePosition) Descriptor() ([]byte, []int) {
	return fileDescriptor_2565b4e8491d341a, []int{14}
}

func (m *SettlePosition) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SettlePosition.Unmarshal(m, b)
}
func (m *SettlePosition) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SettlePosition.Marshal(b, m, deterministic)
}
func (m *SettlePosition) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SettlePosition.Merge(m, src)
}
func (m *SettlePosition) XXX_Size() int {
	return xxx_messageInfo_SettlePosition.Size(m)
}
func (m *SettlePosition) XXX_DiscardUnknown() {
	xxx_messageInfo_SettlePosition.DiscardUnknown(m)
}

var xxx_messageInfo_SettlePosition proto.InternalMessageInfo

func (m *SettlePosition) GetMarketId() string {
	if m != nil {
		return m.MarketId
	}
	return ""
}

func (m *SettlePosition) GetPartyId() string {
	if m != nil {
		return m.PartyId
	}
	return ""
}

func (m *SettlePosition) GetPrice() string {
	if m != nil {
		return m.Price
	}
	return ""
}

func (m *SettlePosition) GetTradeSettlements() []*TradeSettlement {
	if m != nil {
		return m.TradeSettlements
	}
	return nil
}

// A settle distressed event contains information on distressed trading parties who are closed out
type SettleDistressed struct {
	// Market identifier for the event
	MarketId string `protobuf:"bytes,1,opt,name=market_id,json=marketId,proto3" json:"market_id,omitempty"`
	// Party identifier (public key) for the event
	PartyId string `protobuf:"bytes,2,opt,name=party_id,json=partyId,proto3" json:"party_id,omitempty"`
	// Margin value as an integer, for example `123456` is a correctly
	// formatted price of `1.23456` assuming market configured to 5 decimal places
	Margin string `protobuf:"bytes,3,opt,name=margin,proto3" json:"margin,omitempty"`
	// Price as an integer, for example `123456` is a correctly
	// formatted price of `1.23456` assuming market configured to 5 decimal places
	Price                string   `protobuf:"bytes,4,opt,name=price,proto3" json:"price,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SettleDistressed) Reset()         { *m = SettleDistressed{} }
func (m *SettleDistressed) String() string { return proto.CompactTextString(m) }
func (*SettleDistressed) ProtoMessage()    {}
func (*SettleDistressed) Descriptor() ([]byte, []int) {
	return fileDescriptor_2565b4e8491d341a, []int{15}
}

func (m *SettleDistressed) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SettleDistressed.Unmarshal(m, b)
}
func (m *SettleDistressed) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SettleDistressed.Marshal(b, m, deterministic)
}
func (m *SettleDistressed) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SettleDistressed.Merge(m, src)
}
func (m *SettleDistressed) XXX_Size() int {
	return xxx_messageInfo_SettleDistressed.Size(m)
}
func (m *SettleDistressed) XXX_DiscardUnknown() {
	xxx_messageInfo_SettleDistressed.DiscardUnknown(m)
}

var xxx_messageInfo_SettleDistressed proto.InternalMessageInfo

func (m *SettleDistressed) GetMarketId() string {
	if m != nil {
		return m.MarketId
	}
	return ""
}

func (m *SettleDistressed) GetPartyId() string {
	if m != nil {
		return m.PartyId
	}
	return ""
}

func (m *SettleDistressed) GetMargin() string {
	if m != nil {
		return m.Margin
	}
	return ""
}

func (m *SettleDistressed) GetPrice() string {
	if m != nil {
		return m.Price
	}
	return ""
}

// A market ticket event contains the time value for when a particular market was last processed on Vega
type MarketTick struct {
	// Market identifier for the event
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Timestamp containing latest update from Vega blockchain aka Vega-time
	Time                 int64    `protobuf:"varint,2,opt,name=time,proto3" json:"time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MarketTick) Reset()         { *m = MarketTick{} }
func (m *MarketTick) String() string { return proto.CompactTextString(m) }
func (*MarketTick) ProtoMessage()    {}
func (*MarketTick) Descriptor() ([]byte, []int) {
	return fileDescriptor_2565b4e8491d341a, []int{16}
}

func (m *MarketTick) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MarketTick.Unmarshal(m, b)
}
func (m *MarketTick) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MarketTick.Marshal(b, m, deterministic)
}
func (m *MarketTick) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MarketTick.Merge(m, src)
}
func (m *MarketTick) XXX_Size() int {
	return xxx_messageInfo_MarketTick.Size(m)
}
func (m *MarketTick) XXX_DiscardUnknown() {
	xxx_messageInfo_MarketTick.DiscardUnknown(m)
}

var xxx_messageInfo_MarketTick proto.InternalMessageInfo

func (m *MarketTick) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *MarketTick) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

// An auction event indicating a change in auction state, for example starting or ending an auction
type AuctionEvent struct {
	// Market identifier for the event
	MarketId string `protobuf:"bytes,1,opt,name=market_id,json=marketId,proto3" json:"market_id,omitempty"`
	// True if the event indicates an auction opening and False otherwise
	OpeningAuction bool `protobuf:"varint,2,opt,name=opening_auction,json=openingAuction,proto3" json:"opening_auction,omitempty"`
	// True if the event indicates leaving auction mode and False otherwise
	Leave bool `protobuf:"varint,3,opt,name=leave,proto3" json:"leave,omitempty"`
	// Timestamp containing the start time for an auction
	Start int64 `protobuf:"varint,4,opt,name=start,proto3" json:"start,omitempty"`
	// Timestamp containing the end time for an auction
	End int64 `protobuf:"varint,5,opt,name=end,proto3" json:"end,omitempty"`
	// the reason this market is/was in auction
	Trigger vega.AuctionTrigger `protobuf:"varint,6,opt,name=trigger,proto3,enum=vega.AuctionTrigger" json:"trigger,omitempty"`
	// If an auction was ongoing, but was extended for whatever reason, this field will
	// be set to the trigger type indicating which component extended the auction
	ExtensionTrigger     vega.AuctionTrigger `protobuf:"varint,7,opt,name=extension_trigger,json=extensionTrigger,proto3,enum=vega.AuctionTrigger" json:"extension_trigger,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *AuctionEvent) Reset()         { *m = AuctionEvent{} }
func (m *AuctionEvent) String() string { return proto.CompactTextString(m) }
func (*AuctionEvent) ProtoMessage()    {}
func (*AuctionEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_2565b4e8491d341a, []int{17}
}

func (m *AuctionEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuctionEvent.Unmarshal(m, b)
}
func (m *AuctionEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuctionEvent.Marshal(b, m, deterministic)
}
func (m *AuctionEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuctionEvent.Merge(m, src)
}
func (m *AuctionEvent) XXX_Size() int {
	return xxx_messageInfo_AuctionEvent.Size(m)
}
func (m *AuctionEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_AuctionEvent.DiscardUnknown(m)
}

var xxx_messageInfo_AuctionEvent proto.InternalMessageInfo

func (m *AuctionEvent) GetMarketId() string {
	if m != nil {
		return m.MarketId
	}
	return ""
}

func (m *AuctionEvent) GetOpeningAuction() bool {
	if m != nil {
		return m.OpeningAuction
	}
	return false
}

func (m *AuctionEvent) GetLeave() bool {
	if m != nil {
		return m.Leave
	}
	return false
}

func (m *AuctionEvent) GetStart() int64 {
	if m != nil {
		return m.Start
	}
	return 0
}

func (m *AuctionEvent) GetEnd() int64 {
	if m != nil {
		return m.End
	}
	return 0
}

func (m *AuctionEvent) GetTrigger() vega.AuctionTrigger {
	if m != nil {
		return m.Trigger
	}
	return vega.AuctionTrigger_AUCTION_TRIGGER_UNSPECIFIED
}

func (m *AuctionEvent) GetExtensionTrigger() vega.AuctionTrigger {
	if m != nil {
		return m.ExtensionTrigger
	}
	return vega.AuctionTrigger_AUCTION_TRIGGER_UNSPECIFIED
}

// A validator update event contains information about validator node
type ValidatorUpdate struct {
	// Node id of the node
	NodeId string `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	// Vega public key of validator node
	VegaPubKey string `protobuf:"bytes,2,opt,name=vega_pub_key,json=vegaPubKey,proto3" json:"vega_pub_key,omitempty"`
	// Ethereum public key of validator node
	EthereumAddress string `protobuf:"bytes,3,opt,name=ethereum_address,json=ethereumAddress,proto3" json:"ethereum_address,omitempty"`
	// Public key of Tendermint
	TmPubKey string `protobuf:"bytes,4,opt,name=tm_pub_key,json=tmPubKey,proto3" json:"tm_pub_key,omitempty"`
	// URL with more info on the node
	InfoUrl string `protobuf:"bytes,5,opt,name=info_url,json=infoUrl,proto3" json:"info_url,omitempty"`
	// Country code (ISO 3166-1 alpha-2) for the location of the node
	Country string `protobuf:"bytes,6,opt,name=country,proto3" json:"country,omitempty"`
	// Name of the validator
	Name string `protobuf:"bytes,7,opt,name=name,proto3" json:"name,omitempty"`
	// AvatarURL of the validator
	AvatarUrl string `protobuf:"bytes,8,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	// Vega public key derviation index
	VegaPubKeyNumber     uint32   `protobuf:"varint,9,opt,name=vega_pub_key_number,json=vegaPubKeyNumber,proto3" json:"vega_pub_key_number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ValidatorUpdate) Reset()         { *m = ValidatorUpdate{} }
func (m *ValidatorUpdate) String() string { return proto.CompactTextString(m) }
func (*ValidatorUpdate) ProtoMessage()    {}
func (*ValidatorUpdate) Descriptor() ([]byte, []int) {
	return fileDescriptor_2565b4e8491d341a, []int{18}
}

func (m *ValidatorUpdate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ValidatorUpdate.Unmarshal(m, b)
}
func (m *ValidatorUpdate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ValidatorUpdate.Marshal(b, m, deterministic)
}
func (m *ValidatorUpdate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidatorUpdate.Merge(m, src)
}
func (m *ValidatorUpdate) XXX_Size() int {
	return xxx_messageInfo_ValidatorUpdate.Size(m)
}
func (m *ValidatorUpdate) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidatorUpdate.DiscardUnknown(m)
}

var xxx_messageInfo_ValidatorUpdate proto.InternalMessageInfo

func (m *ValidatorUpdate) GetNodeId() string {
	if m != nil {
		return m.NodeId
	}
	return ""
}

func (m *ValidatorUpdate) GetVegaPubKey() string {
	if m != nil {
		return m.VegaPubKey
	}
	return ""
}

func (m *ValidatorUpdate) GetEthereumAddress() string {
	if m != nil {
		return m.EthereumAddress
	}
	return ""
}

func (m *ValidatorUpdate) GetTmPubKey() string {
	if m != nil {
		return m.TmPubKey
	}
	return ""
}

func (m *ValidatorUpdate) GetInfoUrl() string {
	if m != nil {
		return m.InfoUrl
	}
	return ""
}

func (m *ValidatorUpdate) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

func (m *ValidatorUpdate) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ValidatorUpdate) GetAvatarUrl() string {
	if m != nil {
		return m.AvatarUrl
	}
	return ""
}

func (m *ValidatorUpdate) GetVegaPubKeyNumber() uint32 {
	if m != nil {
		return m.VegaPubKeyNumber
	}
	return 0
}

// A key rotation events contains information about Vega key rotation
type KeyRotation struct {
	// Node id of the node
	NodeId string `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	// Old Vega public key of validator node
	OldPubKey string `protobuf:"bytes,2,opt,name=old_pub_key,json=oldPubKey,proto3" json:"old_pub_key,omitempty"`
	// New Vega public key of validator node
	NewPubKey string `protobuf:"bytes,3,opt,name=new_pub_key,json=newPubKey,proto3" json:"new_pub_key,omitempty"`
	// Height of the block where key rotation took effect
	BlockHeight          uint64   `protobuf:"varint,4,opt,name=block_height,json=blockHeight,proto3" json:"block_height,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KeyRotation) Reset()         { *m = KeyRotation{} }
func (m *KeyRotation) String() string { return proto.CompactTextString(m) }
func (*KeyRotation) ProtoMessage()    {}
func (*KeyRotation) Descriptor() ([]byte, []int) {
	return fileDescriptor_2565b4e8491d341a, []int{19}
}

func (m *KeyRotation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeyRotation.Unmarshal(m, b)
}
func (m *KeyRotation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeyRotation.Marshal(b, m, deterministic)
}
func (m *KeyRotation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeyRotation.Merge(m, src)
}
func (m *KeyRotation) XXX_Size() int {
	return xxx_messageInfo_KeyRotation.Size(m)
}
func (m *KeyRotation) XXX_DiscardUnknown() {
	xxx_messageInfo_KeyRotation.DiscardUnknown(m)
}

var xxx_messageInfo_KeyRotation proto.InternalMessageInfo

func (m *KeyRotation) GetNodeId() string {
	if m != nil {
		return m.NodeId
	}
	return ""
}

func (m *KeyRotation) GetOldPubKey() string {
	if m != nil {
		return m.OldPubKey
	}
	return ""
}

func (m *KeyRotation) GetNewPubKey() string {
	if m != nil {
		return m.NewPubKey
	}
	return ""
}

func (m *KeyRotation) GetBlockHeight() uint64 {
	if m != nil {
		return m.BlockHeight
	}
	return 0
}

// A bus event is a container for event bus events emitted by Vega
type BusEvent struct {
	// A unique event identifier for the message
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// The batch (or block) of transactions that the events relate to
	Block string `protobuf:"bytes,2,opt,name=block,proto3" json:"block,omitempty"`
	// The type of bus event (one of the list below)
	Type BusEventType `protobuf:"varint,3,opt,name=type,proto3,enum=vega.events.v1.BusEventType" json:"type,omitempty"`
	// Types that are valid to be assigned to Event:
	//	*BusEvent_TimeUpdate
	//	*BusEvent_TransferResponses
	//	*BusEvent_PositionResolution
	//	*BusEvent_Order
	//	*BusEvent_Account
	//	*BusEvent_Party
	//	*BusEvent_Trade
	//	*BusEvent_MarginLevels
	//	*BusEvent_Proposal
	//	*BusEvent_Vote
	//	*BusEvent_MarketData
	//	*BusEvent_NodeSignature
	//	*BusEvent_LossSocialization
	//	*BusEvent_SettlePosition
	//	*BusEvent_SettleDistressed
	//	*BusEvent_MarketCreated
	//	*BusEvent_Asset
	//	*BusEvent_MarketTick
	//	*BusEvent_Withdrawal
	//	*BusEvent_Deposit
	//	*BusEvent_Auction
	//	*BusEvent_RiskFactor
	//	*BusEvent_NetworkParameter
	//	*BusEvent_LiquidityProvision
	//	*BusEvent_MarketUpdated
	//	*BusEvent_OracleSpec
	//	*BusEvent_OracleData
	//	*BusEvent_DelegationBalance
	//	*BusEvent_ValidatorScore
	//	*BusEvent_EpochEvent
	//	*BusEvent_ValidatorUpdate
	//	*BusEvent_StakeLinking
	//	*BusEvent_RewardPayout
	//	*BusEvent_Checkpoint
	//	*BusEvent_KeyRotation
	//	*BusEvent_Market
	//	*BusEvent_TxErrEvent
	Event isBusEvent_Event `protobuf_oneof:"event"`
	// Version of bus event
	Version              uint32   `protobuf:"varint,4,opt,name=version,proto3" json:"version,omitempty"`
	ChainId              string   `protobuf:"bytes,5,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BusEvent) Reset()         { *m = BusEvent{} }
func (m *BusEvent) String() string { return proto.CompactTextString(m) }
func (*BusEvent) ProtoMessage()    {}
func (*BusEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_2565b4e8491d341a, []int{20}
}

func (m *BusEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BusEvent.Unmarshal(m, b)
}
func (m *BusEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BusEvent.Marshal(b, m, deterministic)
}
func (m *BusEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BusEvent.Merge(m, src)
}
func (m *BusEvent) XXX_Size() int {
	return xxx_messageInfo_BusEvent.Size(m)
}
func (m *BusEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_BusEvent.DiscardUnknown(m)
}

var xxx_messageInfo_BusEvent proto.InternalMessageInfo

func (m *BusEvent) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *BusEvent) GetBlock() string {
	if m != nil {
		return m.Block
	}
	return ""
}

func (m *BusEvent) GetType() BusEventType {
	if m != nil {
		return m.Type
	}
	return BusEventType_BUS_EVENT_TYPE_UNSPECIFIED
}

type isBusEvent_Event interface {
	isBusEvent_Event()
}

type BusEvent_TimeUpdate struct {
	TimeUpdate *TimeUpdate `protobuf:"bytes,101,opt,name=time_update,json=timeUpdate,proto3,oneof"`
}

type BusEvent_TransferResponses struct {
	TransferResponses *TransferResponses `protobuf:"bytes,102,opt,name=transfer_responses,json=transferResponses,proto3,oneof"`
}

type BusEvent_PositionResolution struct {
	PositionResolution *PositionResolution `protobuf:"bytes,103,opt,name=position_resolution,json=positionResolution,proto3,oneof"`
}

type BusEvent_Order struct {
	Order *vega.Order `protobuf:"bytes,104,opt,name=order,proto3,oneof"`
}

type BusEvent_Account struct {
	Account *vega.Account `protobuf:"bytes,105,opt,name=account,proto3,oneof"`
}

type BusEvent_Party struct {
	Party *vega.Party `protobuf:"bytes,106,opt,name=party,proto3,oneof"`
}

type BusEvent_Trade struct {
	Trade *vega.Trade `protobuf:"bytes,107,opt,name=trade,proto3,oneof"`
}

type BusEvent_MarginLevels struct {
	MarginLevels *vega.MarginLevels `protobuf:"bytes,108,opt,name=margin_levels,json=marginLevels,proto3,oneof"`
}

type BusEvent_Proposal struct {
	Proposal *vega.Proposal `protobuf:"bytes,109,opt,name=proposal,proto3,oneof"`
}

type BusEvent_Vote struct {
	Vote *vega.Vote `protobuf:"bytes,110,opt,name=vote,proto3,oneof"`
}

type BusEvent_MarketData struct {
	MarketData *vega.MarketData `protobuf:"bytes,111,opt,name=market_data,json=marketData,proto3,oneof"`
}

type BusEvent_NodeSignature struct {
	NodeSignature *v1.NodeSignature `protobuf:"bytes,112,opt,name=node_signature,json=nodeSignature,proto3,oneof"`
}

type BusEvent_LossSocialization struct {
	LossSocialization *LossSocialization `protobuf:"bytes,113,opt,name=loss_socialization,json=lossSocialization,proto3,oneof"`
}

type BusEvent_SettlePosition struct {
	SettlePosition *SettlePosition `protobuf:"bytes,114,opt,name=settle_position,json=settlePosition,proto3,oneof"`
}

type BusEvent_SettleDistressed struct {
	SettleDistressed *SettleDistressed `protobuf:"bytes,115,opt,name=settle_distressed,json=settleDistressed,proto3,oneof"`
}

type BusEvent_MarketCreated struct {
	MarketCreated *vega.Market `protobuf:"bytes,116,opt,name=market_created,json=marketCreated,proto3,oneof"`
}

type BusEvent_Asset struct {
	Asset *vega.Asset `protobuf:"bytes,117,opt,name=asset,proto3,oneof"`
}

type BusEvent_MarketTick struct {
	MarketTick *MarketTick `protobuf:"bytes,118,opt,name=market_tick,json=marketTick,proto3,oneof"`
}

type BusEvent_Withdrawal struct {
	Withdrawal *vega.Withdrawal `protobuf:"bytes,119,opt,name=withdrawal,proto3,oneof"`
}

type BusEvent_Deposit struct {
	Deposit *vega.Deposit `protobuf:"bytes,120,opt,name=deposit,proto3,oneof"`
}

type BusEvent_Auction struct {
	Auction *AuctionEvent `protobuf:"bytes,121,opt,name=auction,proto3,oneof"`
}

type BusEvent_RiskFactor struct {
	RiskFactor *vega.RiskFactor `protobuf:"bytes,122,opt,name=risk_factor,json=riskFactor,proto3,oneof"`
}

type BusEvent_NetworkParameter struct {
	NetworkParameter *vega.NetworkParameter `protobuf:"bytes,123,opt,name=network_parameter,json=networkParameter,proto3,oneof"`
}

type BusEvent_LiquidityProvision struct {
	LiquidityProvision *vega.LiquidityProvision `protobuf:"bytes,124,opt,name=liquidity_provision,json=liquidityProvision,proto3,oneof"`
}

type BusEvent_MarketUpdated struct {
	MarketUpdated *vega.Market `protobuf:"bytes,125,opt,name=market_updated,json=marketUpdated,proto3,oneof"`
}

type BusEvent_OracleSpec struct {
	OracleSpec *v11.OracleSpec `protobuf:"bytes,126,opt,name=oracle_spec,json=oracleSpec,proto3,oneof"`
}

type BusEvent_OracleData struct {
	OracleData *v11.OracleData `protobuf:"bytes,127,opt,name=oracle_data,json=oracleData,proto3,oneof"`
}

type BusEvent_DelegationBalance struct {
	DelegationBalance *DelegationBalanceEvent `protobuf:"bytes,129,opt,name=delegation_balance,json=delegationBalance,proto3,oneof"`
}

type BusEvent_ValidatorScore struct {
	ValidatorScore *ValidatorScoreEvent `protobuf:"bytes,130,opt,name=validator_score,json=validatorScore,proto3,oneof"`
}

type BusEvent_EpochEvent struct {
	EpochEvent *EpochEvent `protobuf:"bytes,131,opt,name=epoch_event,json=epochEvent,proto3,oneof"`
}

type BusEvent_ValidatorUpdate struct {
	ValidatorUpdate *ValidatorUpdate `protobuf:"bytes,132,opt,name=validator_update,json=validatorUpdate,proto3,oneof"`
}

type BusEvent_StakeLinking struct {
	StakeLinking *StakeLinking `protobuf:"bytes,133,opt,name=stake_linking,json=stakeLinking,proto3,oneof"`
}

type BusEvent_RewardPayout struct {
	RewardPayout *RewardPayoutEvent `protobuf:"bytes,134,opt,name=reward_payout,json=rewardPayout,proto3,oneof"`
}

type BusEvent_Checkpoint struct {
	Checkpoint *CheckpointEvent `protobuf:"bytes,135,opt,name=checkpoint,proto3,oneof"`
}

type BusEvent_KeyRotation struct {
	KeyRotation *KeyRotation `protobuf:"bytes,136,opt,name=key_rotation,json=keyRotation,proto3,oneof"`
}

type BusEvent_Market struct {
	Market *MarketEvent `protobuf:"bytes,1001,opt,name=market,proto3,oneof"`
}

type BusEvent_TxErrEvent struct {
	TxErrEvent *TxErrorEvent `protobuf:"bytes,2001,opt,name=tx_err_event,json=txErrEvent,proto3,oneof"`
}

func (*BusEvent_TimeUpdate) isBusEvent_Event() {}

func (*BusEvent_TransferResponses) isBusEvent_Event() {}

func (*BusEvent_PositionResolution) isBusEvent_Event() {}

func (*BusEvent_Order) isBusEvent_Event() {}

func (*BusEvent_Account) isBusEvent_Event() {}

func (*BusEvent_Party) isBusEvent_Event() {}

func (*BusEvent_Trade) isBusEvent_Event() {}

func (*BusEvent_MarginLevels) isBusEvent_Event() {}

func (*BusEvent_Proposal) isBusEvent_Event() {}

func (*BusEvent_Vote) isBusEvent_Event() {}

func (*BusEvent_MarketData) isBusEvent_Event() {}

func (*BusEvent_NodeSignature) isBusEvent_Event() {}

func (*BusEvent_LossSocialization) isBusEvent_Event() {}

func (*BusEvent_SettlePosition) isBusEvent_Event() {}

func (*BusEvent_SettleDistressed) isBusEvent_Event() {}

func (*BusEvent_MarketCreated) isBusEvent_Event() {}

func (*BusEvent_Asset) isBusEvent_Event() {}

func (*BusEvent_MarketTick) isBusEvent_Event() {}

func (*BusEvent_Withdrawal) isBusEvent_Event() {}

func (*BusEvent_Deposit) isBusEvent_Event() {}

func (*BusEvent_Auction) isBusEvent_Event() {}

func (*BusEvent_RiskFactor) isBusEvent_Event() {}

func (*BusEvent_NetworkParameter) isBusEvent_Event() {}

func (*BusEvent_LiquidityProvision) isBusEvent_Event() {}

func (*BusEvent_MarketUpdated) isBusEvent_Event() {}

func (*BusEvent_OracleSpec) isBusEvent_Event() {}

func (*BusEvent_OracleData) isBusEvent_Event() {}

func (*BusEvent_DelegationBalance) isBusEvent_Event() {}

func (*BusEvent_ValidatorScore) isBusEvent_Event() {}

func (*BusEvent_EpochEvent) isBusEvent_Event() {}

func (*BusEvent_ValidatorUpdate) isBusEvent_Event() {}

func (*BusEvent_StakeLinking) isBusEvent_Event() {}

func (*BusEvent_RewardPayout) isBusEvent_Event() {}

func (*BusEvent_Checkpoint) isBusEvent_Event() {}

func (*BusEvent_KeyRotation) isBusEvent_Event() {}

func (*BusEvent_Market) isBusEvent_Event() {}

func (*BusEvent_TxErrEvent) isBusEvent_Event() {}

func (m *BusEvent) GetEvent() isBusEvent_Event {
	if m != nil {
		return m.Event
	}
	return nil
}

func (m *BusEvent) GetTimeUpdate() *TimeUpdate {
	if x, ok := m.GetEvent().(*BusEvent_TimeUpdate); ok {
		return x.TimeUpdate
	}
	return nil
}

func (m *BusEvent) GetTransferResponses() *TransferResponses {
	if x, ok := m.GetEvent().(*BusEvent_TransferResponses); ok {
		return x.TransferResponses
	}
	return nil
}

func (m *BusEvent) GetPositionResolution() *PositionResolution {
	if x, ok := m.GetEvent().(*BusEvent_PositionResolution); ok {
		return x.PositionResolution
	}
	return nil
}

func (m *BusEvent) GetOrder() *vega.Order {
	if x, ok := m.GetEvent().(*BusEvent_Order); ok {
		return x.Order
	}
	return nil
}

func (m *BusEvent) GetAccount() *vega.Account {
	if x, ok := m.GetEvent().(*BusEvent_Account); ok {
		return x.Account
	}
	return nil
}

func (m *BusEvent) GetParty() *vega.Party {
	if x, ok := m.GetEvent().(*BusEvent_Party); ok {
		return x.Party
	}
	return nil
}

func (m *BusEvent) GetTrade() *vega.Trade {
	if x, ok := m.GetEvent().(*BusEvent_Trade); ok {
		return x.Trade
	}
	return nil
}

func (m *BusEvent) GetMarginLevels() *vega.MarginLevels {
	if x, ok := m.GetEvent().(*BusEvent_MarginLevels); ok {
		return x.MarginLevels
	}
	return nil
}

func (m *BusEvent) GetProposal() *vega.Proposal {
	if x, ok := m.GetEvent().(*BusEvent_Proposal); ok {
		return x.Proposal
	}
	return nil
}

func (m *BusEvent) GetVote() *vega.Vote {
	if x, ok := m.GetEvent().(*BusEvent_Vote); ok {
		return x.Vote
	}
	return nil
}

func (m *BusEvent) GetMarketData() *vega.MarketData {
	if x, ok := m.GetEvent().(*BusEvent_MarketData); ok {
		return x.MarketData
	}
	return nil
}

func (m *BusEvent) GetNodeSignature() *v1.NodeSignature {
	if x, ok := m.GetEvent().(*BusEvent_NodeSignature); ok {
		return x.NodeSignature
	}
	return nil
}

func (m *BusEvent) GetLossSocialization() *LossSocialization {
	if x, ok := m.GetEvent().(*BusEvent_LossSocialization); ok {
		return x.LossSocialization
	}
	return nil
}

func (m *BusEvent) GetSettlePosition() *SettlePosition {
	if x, ok := m.GetEvent().(*BusEvent_SettlePosition); ok {
		return x.SettlePosition
	}
	return nil
}

func (m *BusEvent) GetSettleDistressed() *SettleDistressed {
	if x, ok := m.GetEvent().(*BusEvent_SettleDistressed); ok {
		return x.SettleDistressed
	}
	return nil
}

func (m *BusEvent) GetMarketCreated() *vega.Market {
	if x, ok := m.GetEvent().(*BusEvent_MarketCreated); ok {
		return x.MarketCreated
	}
	return nil
}

func (m *BusEvent) GetAsset() *vega.Asset {
	if x, ok := m.GetEvent().(*BusEvent_Asset); ok {
		return x.Asset
	}
	return nil
}

func (m *BusEvent) GetMarketTick() *MarketTick {
	if x, ok := m.GetEvent().(*BusEvent_MarketTick); ok {
		return x.MarketTick
	}
	return nil
}

func (m *BusEvent) GetWithdrawal() *vega.Withdrawal {
	if x, ok := m.GetEvent().(*BusEvent_Withdrawal); ok {
		return x.Withdrawal
	}
	return nil
}

func (m *BusEvent) GetDeposit() *vega.Deposit {
	if x, ok := m.GetEvent().(*BusEvent_Deposit); ok {
		return x.Deposit
	}
	return nil
}

func (m *BusEvent) GetAuction() *AuctionEvent {
	if x, ok := m.GetEvent().(*BusEvent_Auction); ok {
		return x.Auction
	}
	return nil
}

func (m *BusEvent) GetRiskFactor() *vega.RiskFactor {
	if x, ok := m.GetEvent().(*BusEvent_RiskFactor); ok {
		return x.RiskFactor
	}
	return nil
}

func (m *BusEvent) GetNetworkParameter() *vega.NetworkParameter {
	if x, ok := m.GetEvent().(*BusEvent_NetworkParameter); ok {
		return x.NetworkParameter
	}
	return nil
}

func (m *BusEvent) GetLiquidityProvision() *vega.LiquidityProvision {
	if x, ok := m.GetEvent().(*BusEvent_LiquidityProvision); ok {
		return x.LiquidityProvision
	}
	return nil
}

func (m *BusEvent) GetMarketUpdated() *vega.Market {
	if x, ok := m.GetEvent().(*BusEvent_MarketUpdated); ok {
		return x.MarketUpdated
	}
	return nil
}

func (m *BusEvent) GetOracleSpec() *v11.OracleSpec {
	if x, ok := m.GetEvent().(*BusEvent_OracleSpec); ok {
		return x.OracleSpec
	}
	return nil
}

func (m *BusEvent) GetOracleData() *v11.OracleData {
	if x, ok := m.GetEvent().(*BusEvent_OracleData); ok {
		return x.OracleData
	}
	return nil
}

func (m *BusEvent) GetDelegationBalance() *DelegationBalanceEvent {
	if x, ok := m.GetEvent().(*BusEvent_DelegationBalance); ok {
		return x.DelegationBalance
	}
	return nil
}

func (m *BusEvent) GetValidatorScore() *ValidatorScoreEvent {
	if x, ok := m.GetEvent().(*BusEvent_ValidatorScore); ok {
		return x.ValidatorScore
	}
	return nil
}

func (m *BusEvent) GetEpochEvent() *EpochEvent {
	if x, ok := m.GetEvent().(*BusEvent_EpochEvent); ok {
		return x.EpochEvent
	}
	return nil
}

func (m *BusEvent) GetValidatorUpdate() *ValidatorUpdate {
	if x, ok := m.GetEvent().(*BusEvent_ValidatorUpdate); ok {
		return x.ValidatorUpdate
	}
	return nil
}

func (m *BusEvent) GetStakeLinking() *StakeLinking {
	if x, ok := m.GetEvent().(*BusEvent_StakeLinking); ok {
		return x.StakeLinking
	}
	return nil
}

func (m *BusEvent) GetRewardPayout() *RewardPayoutEvent {
	if x, ok := m.GetEvent().(*BusEvent_RewardPayout); ok {
		return x.RewardPayout
	}
	return nil
}

func (m *BusEvent) GetCheckpoint() *CheckpointEvent {
	if x, ok := m.GetEvent().(*BusEvent_Checkpoint); ok {
		return x.Checkpoint
	}
	return nil
}

func (m *BusEvent) GetKeyRotation() *KeyRotation {
	if x, ok := m.GetEvent().(*BusEvent_KeyRotation); ok {
		return x.KeyRotation
	}
	return nil
}

func (m *BusEvent) GetMarket() *MarketEvent {
	if x, ok := m.GetEvent().(*BusEvent_Market); ok {
		return x.Market
	}
	return nil
}

func (m *BusEvent) GetTxErrEvent() *TxErrorEvent {
	if x, ok := m.GetEvent().(*BusEvent_TxErrEvent); ok {
		return x.TxErrEvent
	}
	return nil
}

func (m *BusEvent) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *BusEvent) GetChainId() string {
	if m != nil {
		return m.ChainId
	}
	return ""
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*BusEvent) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*BusEvent_TimeUpdate)(nil),
		(*BusEvent_TransferResponses)(nil),
		(*BusEvent_PositionResolution)(nil),
		(*BusEvent_Order)(nil),
		(*BusEvent_Account)(nil),
		(*BusEvent_Party)(nil),
		(*BusEvent_Trade)(nil),
		(*BusEvent_MarginLevels)(nil),
		(*BusEvent_Proposal)(nil),
		(*BusEvent_Vote)(nil),
		(*BusEvent_MarketData)(nil),
		(*BusEvent_NodeSignature)(nil),
		(*BusEvent_LossSocialization)(nil),
		(*BusEvent_SettlePosition)(nil),
		(*BusEvent_SettleDistressed)(nil),
		(*BusEvent_MarketCreated)(nil),
		(*BusEvent_Asset)(nil),
		(*BusEvent_MarketTick)(nil),
		(*BusEvent_Withdrawal)(nil),
		(*BusEvent_Deposit)(nil),
		(*BusEvent_Auction)(nil),
		(*BusEvent_RiskFactor)(nil),
		(*BusEvent_NetworkParameter)(nil),
		(*BusEvent_LiquidityProvision)(nil),
		(*BusEvent_MarketUpdated)(nil),
		(*BusEvent_OracleSpec)(nil),
		(*BusEvent_OracleData)(nil),
		(*BusEvent_DelegationBalance)(nil),
		(*BusEvent_ValidatorScore)(nil),
		(*BusEvent_EpochEvent)(nil),
		(*BusEvent_ValidatorUpdate)(nil),
		(*BusEvent_StakeLinking)(nil),
		(*BusEvent_RewardPayout)(nil),
		(*BusEvent_Checkpoint)(nil),
		(*BusEvent_KeyRotation)(nil),
		(*BusEvent_Market)(nil),
		(*BusEvent_TxErrEvent)(nil),
	}
}

func init() {
	proto.RegisterEnum("vega.events.v1.BusEventType", BusEventType_name, BusEventType_value)
	proto.RegisterEnum("vega.events.v1.StakeLinking_Type", StakeLinking_Type_name, StakeLinking_Type_value)
	proto.RegisterEnum("vega.events.v1.StakeLinking_Status", StakeLinking_Status_name, StakeLinking_Status_value)
	proto.RegisterType((*StakeLinking)(nil), "vega.events.v1.StakeLinking")
	proto.RegisterType((*CheckpointEvent)(nil), "vega.events.v1.CheckpointEvent")
	proto.RegisterType((*StreamStartEvent)(nil), "vega.events.v1.StreamStartEvent")
	proto.RegisterType((*RewardPayoutEvent)(nil), "vega.events.v1.RewardPayoutEvent")
	proto.RegisterType((*ValidatorScoreEvent)(nil), "vega.events.v1.ValidatorScoreEvent")
	proto.RegisterType((*DelegationBalanceEvent)(nil), "vega.events.v1.DelegationBalanceEvent")
	proto.RegisterType((*MarketEvent)(nil), "vega.events.v1.MarketEvent")
	proto.RegisterType((*TxErrorEvent)(nil), "vega.events.v1.TxErrorEvent")
	proto.RegisterType((*TimeUpdate)(nil), "vega.events.v1.TimeUpdate")
	proto.RegisterType((*EpochEvent)(nil), "vega.events.v1.EpochEvent")
	proto.RegisterType((*TransferResponses)(nil), "vega.events.v1.TransferResponses")
	proto.RegisterType((*PositionResolution)(nil), "vega.events.v1.PositionResolution")
	proto.RegisterType((*LossSocialization)(nil), "vega.events.v1.LossSocialization")
	proto.RegisterType((*TradeSettlement)(nil), "vega.events.v1.TradeSettlement")
	proto.RegisterType((*SettlePosition)(nil), "vega.events.v1.SettlePosition")
	proto.RegisterType((*SettleDistressed)(nil), "vega.events.v1.SettleDistressed")
	proto.RegisterType((*MarketTick)(nil), "vega.events.v1.MarketTick")
	proto.RegisterType((*AuctionEvent)(nil), "vega.events.v1.AuctionEvent")
	proto.RegisterType((*ValidatorUpdate)(nil), "vega.events.v1.ValidatorUpdate")
	proto.RegisterType((*KeyRotation)(nil), "vega.events.v1.KeyRotation")
	proto.RegisterType((*BusEvent)(nil), "vega.events.v1.BusEvent")
}

func init() { proto.RegisterFile("vega/events/v1/events.proto", fileDescriptor_2565b4e8491d341a) }

var fileDescriptor_2565b4e8491d341a = []byte{
	// 3025 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x59, 0x5b, 0x73, 0xdb, 0xc6,
	0xf5, 0x17, 0x75, 0xa3, 0x78, 0xa8, 0x0b, 0xb4, 0x92, 0x6d, 0xf8, 0x26, 0xcb, 0x74, 0x2e, 0x76,
	0x26, 0x91, 0x73, 0xf9, 0xe7, 0x3f, 0xcd, 0xa4, 0xe9, 0x0c, 0x44, 0xc2, 0x26, 0x2b, 0x8a, 0x64,
	0x17, 0x90, 0x1d, 0x67, 0xa6, 0xc5, 0xac, 0x89, 0x95, 0x84, 0x10, 0x04, 0x68, 0x60, 0x49, 0x49,
	0x69, 0xda, 0x4e, 0x2f, 0x69, 0xd3, 0x0f, 0xd0, 0xe7, 0xbe, 0xb4, 0x2f, 0x9d, 0x4c, 0xbf, 0x47,
	0x1e, 0xfb, 0x31, 0xfa, 0x2d, 0x3a, 0x7b, 0x01, 0x09, 0x90, 0xa0, 0xdb, 0x69, 0xdf, 0xb0, 0xbf,
	0x73, 0xf6, 0xec, 0xd9, 0xb3, 0xe7, 0xb6, 0x0b, 0xb8, 0x3d, 0xa2, 0x67, 0xe4, 0x31, 0x1d, 0xd1,
	0x80, 0xc5, 0x8f, 0x47, 0x1f, 0xa8, 0xaf, 0x83, 0x41, 0x14, 0xb2, 0x10, 0x6d, 0x72, 0xe2, 0x81,
	0x82, 0x46, 0x1f, 0xdc, 0x42, 0x82, 0xb9, 0x4f, 0xa2, 0x1e, 0x4d, 0x78, 0x6e, 0x6d, 0x0b, 0x8c,
	0xc4, 0xf1, 0x04, 0xba, 0x26, 0xa0, 0xb3, 0x70, 0x44, 0xa3, 0x80, 0x04, 0x5d, 0xaa, 0xe0, 0x2d,
	0x01, 0x0b, 0x91, 0x12, 0xb8, 0x25, 0x80, 0x30, 0x22, 0x5d, 0x9f, 0x8a, 0xc5, 0xe3, 0x01, 0xed,
	0xce, 0xa3, 0xb9, 0x84, 0x25, 0xf3, 0xee, 0x09, 0x5a, 0x37, 0xec, 0xf7, 0x49, 0xe0, 0x0a, 0x62,
	0xf2, 0xad, 0x18, 0x1e, 0xcd, 0x30, 0x8c, 0x88, 0xef, 0xb9, 0x84, 0x85, 0x91, 0x93, 0x65, 0xad,
	0xfc, 0x6d, 0x09, 0xd6, 0x2d, 0x46, 0x7a, 0xb4, 0xe9, 0x05, 0x3d, 0x2f, 0x38, 0x43, 0x9b, 0xb0,
	0xe8, 0xb9, 0x7a, 0x61, 0xbf, 0xf0, 0xb0, 0x84, 0x17, 0x3d, 0x17, 0x7d, 0x0c, 0xcb, 0xec, 0x6a,
	0x40, 0xf5, 0xc5, 0xfd, 0xc2, 0xc3, 0xcd, 0x0f, 0xef, 0x1f, 0x64, 0x4d, 0x72, 0x90, 0x9e, 0x7b,
	0x60, 0x5f, 0x0d, 0x28, 0x16, 0xec, 0x5c, 0x0c, 0x8b, 0xf5, 0xa5, 0xfd, 0xc2, 0xc3, 0x25, 0xbc,
	0xc8, 0x62, 0xb4, 0x0b, 0x2b, 0x03, 0x12, 0xb1, 0x2b, 0x7d, 0x59, 0x48, 0x96, 0x03, 0x74, 0x1d,
	0x56, 0x49, 0x3f, 0x1c, 0x06, 0x4c, 0x5f, 0x11, 0xb0, 0x1a, 0xa1, 0x4f, 0x61, 0x35, 0x66, 0x84,
	0x0d, 0x63, 0x7d, 0x55, 0x2c, 0xfb, 0xe0, 0xb5, 0xcb, 0x5a, 0x82, 0x15, 0xab, 0x29, 0xe8, 0x3e,
	0xac, 0x9f, 0x7a, 0x01, 0xf1, 0xbd, 0xaf, 0xa8, 0xeb, 0x10, 0xa6, 0x17, 0x85, 0x12, 0xe5, 0x31,
	0x66, 0x30, 0x74, 0x03, 0x8a, 0xec, 0xd2, 0x39, 0x27, 0xf1, 0xb9, 0xbe, 0x26, 0x17, 0x66, 0x97,
	0x75, 0x12, 0x9f, 0x57, 0x7e, 0x08, 0xcb, 0x7c, 0x13, 0x68, 0x17, 0x34, 0xfb, 0x45, 0xc7, 0x74,
	0x4e, 0x5a, 0x56, 0xc7, 0xac, 0x36, 0x9e, 0x34, 0xcc, 0x9a, 0xb6, 0x80, 0x36, 0xa0, 0x24, 0xd0,
	0x66, 0xa3, 0x75, 0xa4, 0x15, 0xd0, 0x16, 0x94, 0x15, 0x93, 0x00, 0x16, 0x2b, 0x3f, 0x83, 0x55,
	0xa9, 0x0b, 0xba, 0x0e, 0xc8, 0xb2, 0x0d, 0xfb, 0xc4, 0x9a, 0x92, 0x80, 0x60, 0x53, 0xe1, 0x1d,
	0xb3, 0x55, 0x6b, 0xb4, 0x9e, 0x6a, 0x05, 0xb4, 0x03, 0x5b, 0x0a, 0x33, 0xaa, 0x55, 0xb3, 0x63,
	0x9b, 0x35, 0x6d, 0x31, 0x05, 0x62, 0xf3, 0xc7, 0x66, 0x95, 0x83, 0x4b, 0x95, 0x33, 0xd8, 0xaa,
	0x9e, 0xd3, 0x6e, 0x6f, 0x10, 0x7a, 0x01, 0x33, 0xb9, 0x31, 0x10, 0x82, 0x65, 0xb1, 0x0d, 0x79,
	0x60, 0xe2, 0x1b, 0xdd, 0x05, 0x78, 0xe9, 0x87, 0xdd, 0x9e, 0xdc, 0xe0, 0xa2, 0xa0, 0x94, 0x04,
	0xc2, 0xf7, 0xc8, 0xed, 0xa3, 0xc8, 0xd4, 0x3b, 0x3b, 0x67, 0xe2, 0x90, 0x96, 0x71, 0x59, 0x32,
	0x08, 0xa8, 0xf2, 0x1e, 0x68, 0x16, 0x8b, 0x28, 0xe9, 0x5b, 0x8c, 0x44, 0x6a, 0xa5, 0x9b, 0xb0,
	0xd6, 0x3d, 0x27, 0x5e, 0xe0, 0x8c, 0xdd, 0xa3, 0x28, 0xc6, 0x0d, 0xb7, 0xf2, 0x7d, 0x01, 0xb6,
	0x31, 0xbd, 0x20, 0x91, 0xdb, 0x21, 0x57, 0xe1, 0x50, 0x4d, 0x18, 0x1f, 0x79, 0x21, 0x7d, 0xe4,
	0xb7, 0xa1, 0x44, 0x07, 0x61, 0xf7, 0xdc, 0x89, 0xe9, 0x2b, 0xa5, 0xdb, 0x9a, 0x00, 0x2c, 0xfa,
	0x8a, 0x4f, 0x11, 0x91, 0x24, 0x74, 0x2a, 0x61, 0x39, 0x48, 0x79, 0xc9, 0x72, 0xc6, 0x4b, 0x3e,
	0x86, 0x1b, 0x03, 0x1a, 0x75, 0x69, 0xc0, 0x9c, 0xf0, 0xd4, 0x61, 0x21, 0x23, 0xbe, 0x13, 0x09,
	0x35, 0x94, 0x3b, 0xed, 0x2a, 0x72, 0xfb, 0xd4, 0xe6, 0x44, 0xa9, 0x22, 0xba, 0x03, 0x25, 0xe6,
	0xf5, 0x69, 0xcc, 0x48, 0x7f, 0x20, 0xfc, 0x6b, 0x09, 0x4f, 0x80, 0xca, 0x9f, 0x0b, 0xb0, 0xf3,
	0x2c, 0x89, 0x16, 0xab, 0x1b, 0x46, 0x54, 0xee, 0xe6, 0x06, 0x14, 0x83, 0xd0, 0xa5, 0x93, 0xdd,
	0xaf, 0xf2, 0x61, 0xc3, 0x7d, 0xfd, 0x86, 0xde, 0x86, 0xad, 0x49, 0xe8, 0xc5, 0x5c, 0x9a, 0xda,
	0xda, 0xe6, 0x28, 0xb3, 0x06, 0x7a, 0x04, 0x5a, 0x10, 0x46, 0x7d, 0xe2, 0x7b, 0x31, 0x75, 0x15,
	0xa7, 0xdc, 0xed, 0xd6, 0x04, 0x17, 0xac, 0x95, 0xaf, 0xe1, 0x7a, 0x8d, 0xfa, 0xf4, 0x8c, 0x30,
	0x2f, 0x0c, 0x0e, 0x89, 0xcf, 0x53, 0xcc, 0xeb, 0x2c, 0x9e, 0xd2, 0x7c, 0x31, 0xa3, 0xf9, 0xc4,
	0xae, 0x4b, 0x19, 0xbb, 0x66, 0x76, 0xb4, 0x9c, 0xdd, 0x51, 0xa5, 0x06, 0xe5, 0x63, 0x91, 0x00,
	0xe5, 0x92, 0xb7, 0xa1, 0x24, 0xf3, 0xe1, 0xc4, 0x30, 0x6b, 0x12, 0x68, 0xb8, 0x48, 0x87, 0xe2,
	0x80, 0x5c, 0xf9, 0x21, 0x49, 0x56, 0x4e, 0x86, 0x95, 0xbf, 0x17, 0x61, 0xdd, 0xbe, 0x34, 0xa3,
	0x28, 0x8c, 0xc6, 0xde, 0x25, 0xb4, 0x4d, 0x79, 0x97, 0x18, 0x37, 0x5c, 0xae, 0x3f, 0x8d, 0x22,
	0xa7, 0x1f, 0x9f, 0x25, 0xfa, 0xd3, 0x28, 0x3a, 0x8e, 0xcf, 0x50, 0x0b, 0xb4, 0x30, 0x72, 0x69,
	0xe4, 0xc4, 0xc3, 0x97, 0x7d, 0x2f, 0x8e, 0xbd, 0x30, 0xd0, 0xe9, 0x7e, 0xe1, 0x61, 0x39, 0x49,
	0x53, 0xe3, 0x5c, 0x37, 0xfa, 0xe0, 0xa0, 0xcd, 0x39, 0xad, 0x31, 0x63, 0x7d, 0x01, 0x6f, 0x85,
	0x59, 0x08, 0x1d, 0x81, 0x84, 0x1c, 0xd2, 0xa7, 0x81, 0xdb, 0xa7, 0x01, 0xd3, 0x4f, 0x85, 0xb8,
	0xfd, 0x39, 0xe2, 0x8c, 0x84, 0xaf, 0xbe, 0x80, 0x37, 0xc3, 0x0c, 0x82, 0x6c, 0x40, 0x52, 0x58,
	0x97, 0x9f, 0x8f, 0xef, 0x8b, 0xd3, 0xd2, 0xcf, 0x84, 0xbc, 0x07, 0x73, 0xe4, 0x55, 0x53, 0xac,
	0xf5, 0x05, 0xbc, 0x1d, 0x4e, 0x83, 0xe8, 0x10, 0xd6, 0x06, 0x51, 0x38, 0x08, 0x63, 0xe2, 0xeb,
	0xe7, 0x42, 0xd6, 0x1b, 0xb3, 0xb2, 0x3a, 0x8a, 0x23, 0xb3, 0xdb, 0xf1, 0x3c, 0xbe, 0xcd, 0x51,
	0xc8, 0x68, 0xda, 0x6a, 0xde, 0xbc, 0x6d, 0x3e, 0x0b, 0x19, 0xcd, 0x88, 0xd9, 0x1c, 0x65, 0x10,
	0x34, 0x82, 0x3d, 0xdf, 0x7b, 0x35, 0xf4, 0x5c, 0x8f, 0x5d, 0x39, 0x83, 0x28, 0x1c, 0x79, 0x1c,
	0x4e, 0xcb, 0xfe, 0x52, 0xc8, 0x3e, 0x98, 0x95, 0xdd, 0x4c, 0xe6, 0x75, 0x92, 0x69, 0x99, 0x95,
	0xee, 0xf8, 0xaf, 0xa1, 0xa3, 0xe7, 0xb0, 0x73, 0xe1, 0xb1, 0x73, 0x37, 0x22, 0x17, 0xe9, 0xc5,
	0x7a, 0xf3, 0x6c, 0xf2, 0x5c, 0x31, 0x67, 0x96, 0x40, 0x17, 0x33, 0x28, 0x17, 0xec, 0xca, 0xe8,
	0xca, 0x58, 0xc8, 0x9f, 0x27, 0x58, 0x85, 0x62, 0xd6, 0x4a, 0xc8, 0x9d, 0x41, 0xd1, 0x4f, 0xe1,
	0xda, 0x30, 0xc8, 0x13, 0xdd, 0x17, 0xa2, 0xdf, 0x9a, 0x15, 0x7d, 0x12, 0xb8, 0x79, 0xc2, 0x77,
	0x87, 0x39, 0x38, 0x0f, 0x86, 0x88, 0xc6, 0x2c, 0x8c, 0xa8, 0x13, 0x07, 0x64, 0x10, 0x9f, 0x87,
	0x4c, 0x0f, 0xe6, 0x05, 0x03, 0x96, 0x9c, 0x96, 0x62, 0xe4, 0xc1, 0x10, 0x65, 0xa1, 0xc3, 0x0d,
	0x28, 0xb3, 0x88, 0x04, 0x31, 0xe9, 0x72, 0xc7, 0xab, 0xbc, 0x03, 0x60, 0x7b, 0x7d, 0x7a, 0x32,
	0x70, 0x09, 0xa3, 0xd9, 0x14, 0x5a, 0x98, 0x4e, 0xa1, 0x7f, 0x29, 0x00, 0x98, 0x3c, 0x5f, 0xc8,
	0xd0, 0xd6, 0x60, 0x89, 0x27, 0x92, 0x82, 0x28, 0x33, 0xfc, 0x13, 0x3d, 0x82, 0x55, 0x29, 0x56,
	0x75, 0x15, 0xdb, 0x52, 0x43, 0x31, 0xc7, 0x10, 0x04, 0xac, 0x18, 0x78, 0x2d, 0x8b, 0x79, 0x0d,
	0x72, 0xb8, 0x78, 0xd5, 0x4f, 0x94, 0x04, 0xc2, 0xd5, 0x41, 0xf7, 0xa0, 0x4c, 0x2f, 0x07, 0x5e,
	0x44, 0x25, 0x7d, 0x59, 0xd0, 0x41, 0x42, 0x82, 0xe1, 0x26, 0xac, 0xd1, 0xc0, 0x95, 0xd4, 0x15,
	0x41, 0x2d, 0xd2, 0xc0, 0xe5, 0xa4, 0x4a, 0x03, 0xb6, 0x6d, 0xbe, 0xc3, 0x53, 0x1a, 0x61, 0x1a,
	0x0f, 0xc2, 0x20, 0xa6, 0x31, 0xfa, 0x3f, 0x28, 0x45, 0xc9, 0x40, 0x2f, 0xec, 0x2f, 0x3d, 0x2c,
	0x7f, 0x78, 0x5d, 0x6a, 0x37, 0xcd, 0x8b, 0x27, 0x8c, 0x95, 0x6f, 0x0b, 0x80, 0x3a, 0x61, 0xec,
	0x09, 0xd5, 0x69, 0x1c, 0xfa, 0x43, 0xa1, 0xfc, 0x6b, 0x93, 0xe3, 0x1e, 0x80, 0xeb, 0xc5, 0x2c,
	0xa2, 0x71, 0x4c, 0x65, 0x7e, 0x5c, 0xc2, 0x29, 0x84, 0x67, 0xe7, 0xae, 0x1f, 0x72, 0x9a, 0xdc,
	0xb5, 0x1a, 0x71, 0x8b, 0x70, 0x19, 0xce, 0x20, 0xf2, 0xba, 0x49, 0x8d, 0x10, 0xcb, 0x74, 0x38,
	0x50, 0xe9, 0xc2, 0x76, 0x33, 0x8c, 0x63, 0x2b, 0xec, 0x7a, 0xbc, 0xdd, 0x21, 0xff, 0x5e, 0x91,
	0x74, 0xea, 0x5d, 0xcc, 0xa6, 0xde, 0x39, 0x15, 0xa2, 0xf2, 0x29, 0x6c, 0xd9, 0x11, 0x71, 0xa9,
	0x45, 0x19, 0xf3, 0x69, 0x5f, 0x35, 0x22, 0xb1, 0xf7, 0x15, 0x55, 0xde, 0x20, 0xbe, 0x45, 0x3d,
	0x12, 0x5a, 0x2e, 0xaa, 0x7a, 0x24, 0x34, 0xfc, 0xae, 0x00, 0x9b, 0x72, 0x62, 0x62, 0xb2, 0xff,
	0x5a, 0xbf, 0xf1, 0x02, 0x4b, 0xa9, 0x05, 0x50, 0x13, 0xb6, 0x19, 0xd7, 0xce, 0x89, 0xc7, 0xea,
	0xc5, 0xfa, 0xb2, 0x38, 0xcb, 0x7b, 0xd3, 0x8d, 0xe4, 0xd4, 0x36, 0xb0, 0xc6, 0xb2, 0x40, 0x5c,
	0xb9, 0x04, 0x4d, 0x0e, 0x6b, 0x93, 0xb3, 0xf9, 0x1f, 0xec, 0xd9, 0x27, 0xd1, 0x99, 0x17, 0x24,
	0xf6, 0x94, 0xa3, 0xc9, 0x3e, 0x96, 0xd3, 0x86, 0x7a, 0x1f, 0x40, 0x96, 0x5a, 0xdb, 0xeb, 0xf6,
	0x66, 0x1a, 0x73, 0x04, 0xcb, 0xc2, 0xab, 0xa5, 0xe7, 0x88, 0xef, 0xca, 0x37, 0x8b, 0xb0, 0x6e,
	0x0c, 0x45, 0xe4, 0xfc, 0x07, 0xe5, 0xf9, 0x6d, 0xd8, 0x0a, 0x07, 0x34, 0xf0, 0x82, 0x33, 0x87,
	0x0c, 0x27, 0xf1, 0xb8, 0x86, 0x37, 0x15, 0xac, 0x44, 0x71, 0xf5, 0x7c, 0x4a, 0x46, 0xd2, 0xcc,
	0x6b, 0x58, 0x0e, 0x38, 0x2a, 0x02, 0x51, 0x45, 0x9d, 0x1c, 0xf0, 0x68, 0xa7, 0x81, 0xab, 0x62,
	0x8d, 0x7f, 0xa2, 0x03, 0x28, 0xb2, 0xc8, 0x3b, 0x3b, 0xa3, 0x91, 0xea, 0xe6, 0x77, 0xe5, 0x21,
	0x28, 0xe9, 0xb6, 0xa4, 0xe1, 0x84, 0x09, 0x19, 0xb0, 0x4d, 0x2f, 0x19, 0x0d, 0x44, 0x21, 0x49,
	0x66, 0x16, 0x5f, 0x33, 0x53, 0x1b, 0xb3, 0x2b, 0xa4, 0xf2, 0xdd, 0x22, 0x6c, 0x8d, 0x9b, 0x38,
	0x95, 0xb3, 0xe6, 0x36, 0x70, 0xfb, 0xb0, 0xce, 0xa5, 0x3a, 0x83, 0xe1, 0x4b, 0xa7, 0x47, 0xaf,
	0xd4, 0x99, 0x01, 0xc7, 0x3a, 0xc3, 0x97, 0x47, 0xf4, 0x8a, 0x37, 0x67, 0x94, 0x9d, 0xd3, 0x88,
	0x0e, 0xfb, 0x0e, 0x71, 0x5d, 0xee, 0x04, 0xea, 0x00, 0xb7, 0x12, 0xdc, 0x90, 0x30, 0xba, 0x03,
	0xc0, 0xfa, 0x63, 0x51, 0xaa, 0x79, 0x62, 0x7d, 0x25, 0xe8, 0x26, 0xac, 0x79, 0xc1, 0x69, 0xe8,
	0x0c, 0x23, 0x5f, 0xb5, 0xa8, 0x45, 0x3e, 0x3e, 0x89, 0x7c, 0xde, 0x2b, 0x75, 0x79, 0x6c, 0x45,
	0x57, 0xc2, 0x4a, 0xbc, 0xbb, 0x96, 0x43, 0x7e, 0xd0, 0x01, 0xe9, 0x53, 0x61, 0x82, 0x12, 0x16,
	0xdf, 0x3c, 0x09, 0x90, 0x11, 0x61, 0x24, 0x12, 0xa2, 0xe4, 0x1d, 0xa6, 0x24, 0x11, 0x2e, 0xec,
	0x3d, 0xd8, 0x49, 0x6f, 0xc9, 0x09, 0x86, 0xfd, 0x97, 0x34, 0xd2, 0x4b, 0xfb, 0x85, 0x87, 0x1b,
	0x58, 0x9b, 0xec, 0xac, 0x25, 0xf0, 0xca, 0x1f, 0x0b, 0x50, 0x3e, 0xa2, 0x57, 0x38, 0x64, 0x32,
	0x5d, 0xcc, 0x35, 0xd5, 0x1e, 0x94, 0x43, 0xdf, 0x9d, 0xb2, 0x54, 0x29, 0xf4, 0x5d, 0xb5, 0xbf,
	0x3d, 0x28, 0x07, 0xf4, 0x62, 0x4c, 0x97, 0x36, 0x2a, 0x05, 0xf4, 0x42, 0xd1, 0xa7, 0xaf, 0x1e,
	0xcb, 0xb3, 0x57, 0x8f, 0x3f, 0xed, 0xc0, 0xda, 0xe1, 0x30, 0x96, 0xee, 0x3b, 0xed, 0xf3, 0xbb,
	0xb0, 0x22, 0x78, 0x93, 0x84, 0x22, 0x06, 0xe8, 0x7d, 0x75, 0x45, 0x5d, 0x12, 0x3e, 0x72, 0x67,
	0x3a, 0xc4, 0x13, 0x69, 0xa9, 0xdb, 0xe9, 0x67, 0x50, 0xe6, 0xf1, 0xe2, 0x0c, 0x85, 0x6b, 0xa8,
	0xa6, 0xf1, 0xd6, 0x4c, 0x6e, 0x18, 0x17, 0xbc, 0xfa, 0x02, 0x06, 0x36, 0x29, 0x7f, 0x18, 0x10,
	0x53, 0xd5, 0xc0, 0x99, 0x54, 0x8b, 0xd3, 0x74, 0xb5, 0xcd, 0x64, 0x98, 0x6c, 0x8d, 0xe1, 0x9d,
	0x1d, 0x9b, 0x29, 0x3c, 0x27, 0xb0, 0x33, 0x50, 0xe9, 0x90, 0xcb, 0x54, 0x25, 0x44, 0x35, 0x8c,
	0x95, 0x69, 0xa1, 0xb3, 0xc5, 0x86, 0x77, 0x1d, 0x83, 0xd9, 0x12, 0xf4, 0x00, 0x56, 0x44, 0x17,
	0xa9, 0xba, 0xc5, 0xb2, 0x14, 0x24, 0xba, 0xcd, 0xfa, 0x02, 0x96, 0x34, 0xf4, 0x08, 0x8a, 0xa4,
	0x2b, 0xdc, 0x4d, 0x75, 0x82, 0x1b, 0x2a, 0xce, 0x24, 0x58, 0x5f, 0xc0, 0x09, 0x9d, 0xcb, 0x93,
	0x57, 0x8c, 0x2f, 0xd3, 0xf2, 0x3a, 0x1c, 0xe2, 0xf2, 0xe4, 0x8d, 0xe3, 0x01, 0xac, 0x88, 0x34,
	0xaa, 0xda, 0xb1, 0xf2, 0xb8, 0x80, 0xba, 0xdc, 0x92, 0x92, 0x86, 0x3e, 0x81, 0x0d, 0x99, 0xfd,
	0x1c, 0x9f, 0x8e, 0xa8, 0x1f, 0xab, 0x16, 0x0b, 0x49, 0xe6, 0x63, 0x41, 0x6a, 0x0a, 0x4a, 0x7d,
	0x01, 0xaf, 0xf7, 0x53, 0x63, 0xf4, 0x6e, 0xaa, 0x0b, 0x96, 0xdd, 0xd3, 0xa6, 0xd2, 0x43, 0xa1,
	0x99, 0x7e, 0x77, 0x1f, 0x96, 0x79, 0xd3, 0xaa, 0xba, 0x21, 0x90, 0x9c, 0xbc, 0xb1, 0xad, 0x2f,
	0x60, 0x41, 0x41, 0x1f, 0x41, 0x59, 0x65, 0x49, 0x97, 0x30, 0xa2, 0x87, 0x82, 0x51, 0x1b, 0x2b,
	0xd2, 0xa3, 0xac, 0x46, 0x18, 0xe1, 0x4e, 0xd0, 0x1f, 0x8f, 0x50, 0x1d, 0x36, 0x45, 0x90, 0xc4,
	0xde, 0x59, 0x40, 0xd8, 0x30, 0xa2, 0xfa, 0x40, 0xcc, 0xbb, 0x37, 0xdb, 0x6e, 0xb5, 0x42, 0x97,
	0x5a, 0x09, 0x5b, 0x7d, 0x01, 0x6f, 0x04, 0x69, 0x80, 0xbb, 0x93, 0x1f, 0xc6, 0xb1, 0x13, 0xa7,
	0x6b, 0xb6, 0xfe, 0x2a, 0xdf, 0x9d, 0x66, 0x8a, 0x3b, 0x77, 0x27, 0x7f, 0xa6, 0xe2, 0x37, 0x60,
	0x4b, 0x56, 0x3f, 0x27, 0x71, 0x0a, 0x3d, 0x12, 0x02, 0xf7, 0x66, 0x9e, 0x52, 0x32, 0xa5, 0x98,
	0xb7, 0xf8, 0x71, 0xb6, 0x38, 0xb7, 0x61, 0x5b, 0x89, 0x4a, 0xf5, 0x2b, 0x71, 0xfa, 0xc6, 0x30,
	0x2d, 0x6c, 0x52, 0x29, 0xeb, 0x0b, 0x58, 0x8b, 0xa7, 0xab, 0xe7, 0xc7, 0xb0, 0xa9, 0xcc, 0xdd,
	0x8d, 0x28, 0x61, 0xd4, 0xd5, 0x99, 0x90, 0xb6, 0x9e, 0xb6, 0x38, 0x37, 0x93, 0xe4, 0xaa, 0x4a,
	0x26, 0xee, 0x55, 0xf2, 0x71, 0x60, 0x98, 0xf6, 0x2a, 0x83, 0x43, 0xdc, 0xab, 0xe4, 0x5b, 0xc1,
	0x67, 0xe3, 0xa3, 0x64, 0x5e, 0xb7, 0xa7, 0x8f, 0xf2, 0x23, 0x7b, 0x52, 0x56, 0x27, 0x87, 0x2a,
	0x8a, 0xec, 0x87, 0x00, 0xc9, 0x9d, 0x80, 0xf8, 0xfa, 0x45, 0xda, 0x11, 0x9e, 0x8f, 0x71, 0x3e,
	0x67, 0xc2, 0xc5, 0xa3, 0xc7, 0xa5, 0xc2, 0xca, 0xfa, 0x65, 0x3a, 0x7a, 0x6a, 0x12, 0xe4, 0xd1,
	0xa3, 0xe8, 0xe8, 0x07, 0x50, 0x4c, 0x2a, 0xed, 0x95, 0x60, 0x9d, 0x49, 0x56, 0xe9, 0xea, 0x2d,
	0xe2, 0x4e, 0x95, 0xe0, 0x8f, 0xa0, 0x1c, 0x79, 0x71, 0xcf, 0x39, 0x25, 0x5d, 0x16, 0x46, 0xfa,
	0x57, 0x69, 0xcd, 0xb0, 0x17, 0xf7, 0x9e, 0x08, 0x9c, 0x6b, 0x16, 0x8d, 0x47, 0xc8, 0x84, 0xed,
	0x80, 0xb2, 0x8b, 0x90, 0x77, 0x8b, 0x24, 0x22, 0x7d, 0xca, 0x68, 0xa4, 0xff, 0x5c, 0x4c, 0x55,
	0x4d, 0x6d, 0x4b, 0x92, 0x3b, 0x09, 0x95, 0x9f, 0x57, 0x30, 0x85, 0xa1, 0x23, 0xd8, 0xc9, 0xb9,
	0xe3, 0xe9, 0x5f, 0x0b, 0x41, 0xba, 0x14, 0x34, 0x7b, 0x99, 0xe3, 0x09, 0x69, 0xf6, 0x0a, 0x97,
	0x3a, 0x7c, 0x99, 0x7c, 0x5d, 0xfd, 0x17, 0xaf, 0x3b, 0x7c, 0x99, 0x71, 0x5d, 0xf4, 0x09, 0x94,
	0xe5, 0x63, 0xa8, 0x13, 0x0f, 0x68, 0x57, 0xff, 0xa5, 0xda, 0x84, 0x7a, 0x20, 0x95, 0x37, 0x68,
	0xfe, 0x69, 0x0d, 0x68, 0x97, 0x5b, 0x21, 0x1c, 0x8f, 0x52, 0x53, 0x45, 0x74, 0xff, 0x6a, 0xde,
	0xd4, 0x24, 0xc6, 0xc3, 0xf1, 0x08, 0x7d, 0x0e, 0xc9, 0x4d, 0x8e, 0xa7, 0xe5, 0x97, 0xf2, 0xad,
	0x45, 0xff, 0x75, 0x21, 0x7d, 0x63, 0x9b, 0x9c, 0x5d, 0xfe, 0xab, 0x0c, 0x8f, 0x4f, 0x77, 0x9a,
	0x82, 0xda, 0xb3, 0x0f, 0x43, 0xbf, 0x29, 0xa4, 0x1f, 0x07, 0x26, 0x62, 0x73, 0x5e, 0xa3, 0xc4,
	0x45, 0x3c, 0xfb, 0x80, 0xf4, 0x23, 0x28, 0xcb, 0x47, 0x1b, 0x31, 0x51, 0xff, 0x6d, 0x21, 0xdf,
	0xf3, 0x27, 0xf7, 0x32, 0xbe, 0x55, 0x3a, 0xb9, 0xa5, 0x1d, 0x83, 0x36, 0x51, 0x48, 0xd5, 0xc5,
	0xdf, 0x15, 0xd2, 0x19, 0x2d, 0x47, 0xa3, 0x71, 0x75, 0x9c, 0x6c, 0x46, 0x95, 0xc8, 0x1a, 0x6c,
	0xc4, 0x8c, 0xf4, 0xa8, 0xe3, 0xcb, 0x47, 0x5a, 0xfd, 0x9b, 0x42, 0xbe, 0xc3, 0xa7, 0x5f, 0x72,
	0x79, 0xa2, 0x8f, 0xd3, 0x8f, 0xd1, 0x0d, 0xd8, 0x90, 0x0f, 0x7a, 0xce, 0x40, 0x3c, 0x2c, 0xea,
	0xbf, 0x2f, 0xe4, 0x67, 0xc5, 0x99, 0xd7, 0x47, 0x2e, 0x2a, 0x4a, 0x81, 0xe8, 0x10, 0xa0, 0x3b,
	0x7e, 0x3b, 0xd5, 0xff, 0x30, 0x67, 0x67, 0x53, 0xcf, 0xab, 0xdc, 0x46, 0x93, 0x59, 0xc8, 0x80,
	0x75, 0xde, 0x4d, 0x45, 0xaa, 0x4f, 0xd2, 0xbf, 0x95, 0x52, 0x6e, 0x4f, 0x4b, 0x49, 0xf5, 0x52,
	0xf5, 0x05, 0x5c, 0xee, 0xa5, 0x5a, 0xab, 0xff, 0x17, 0x37, 0x80, 0x1e, 0x65, 0xfa, 0x3f, 0x8b,
	0xf9, 0x93, 0x53, 0xaf, 0x6b, 0xf5, 0x05, 0xac, 0xb8, 0xf9, 0xd2, 0xec, 0xd2, 0xa1, 0x51, 0xa4,
	0xce, 0xf7, 0x1f, 0x5b, 0xf9, 0xe6, 0x4c, 0x3f, 0xaa, 0x89, 0xae, 0x85, 0x8f, 0xe5, 0x09, 0xeb,
	0x50, 0x1c, 0xd1, 0x48, 0x84, 0xee, 0xb2, 0x68, 0x04, 0x93, 0x61, 0xe6, 0x69, 0x77, 0x25, 0xf3,
	0xb4, 0x7b, 0x58, 0x84, 0x15, 0x21, 0xfc, 0x9d, 0xbf, 0x02, 0xac, 0xa7, 0x3b, 0x29, 0xb4, 0x07,
	0xb7, 0x0e, 0x4f, 0x2c, 0xc7, 0x7c, 0x66, 0xb6, 0x6c, 0x27, 0xe7, 0xb1, 0xfc, 0x3a, 0xa0, 0x29,
	0xba, 0xd1, 0x6c, 0x6a, 0x85, 0x9c, 0x79, 0x76, 0xe3, 0xd8, 0x74, 0x4e, 0x3a, 0x35, 0xc3, 0x36,
	0xb5, 0x45, 0xf4, 0x26, 0xdc, 0x9f, 0xa6, 0x63, 0xa3, 0x65, 0x3d, 0x31, 0xb1, 0x83, 0x4d, 0xab,
	0xd3, 0x6e, 0x59, 0xa6, 0xa5, 0x2d, 0xa1, 0xb7, 0xa0, 0x32, 0xc5, 0xd6, 0x69, 0x5b, 0x0d, 0xbb,
	0xd1, 0x6e, 0x71, 0xb6, 0x76, 0xf3, 0x84, 0x7f, 0x6a, 0xcb, 0x48, 0x87, 0xdd, 0x29, 0xbe, 0x36,
	0xae, 0x99, 0x58, 0x5b, 0x41, 0xb7, 0xe0, 0xfa, 0xb4, 0x82, 0xd5, 0x6a, 0xfb, 0xa4, 0x65, 0x6b,
	0xab, 0x39, 0xb3, 0x3a, 0x06, 0xb6, 0x5f, 0x68, 0xc5, 0x1c, 0x8a, 0x8d, 0x8d, 0x9a, 0xa9, 0xad,
	0xa1, 0x7d, 0xb8, 0x33, 0x45, 0x39, 0x36, 0xf0, 0xd3, 0x46, 0xcb, 0x69, 0x9a, 0xcf, 0xcc, 0xa6,
	0xa5, 0x95, 0xd0, 0x6d, 0xb8, 0x31, 0x2d, 0x15, 0xb7, 0x3b, 0x6d, 0xcb, 0x68, 0x6a, 0x80, 0x6e,
	0xc0, 0xce, 0x14, 0xf1, 0x59, 0xdb, 0x36, 0xb5, 0x72, 0x8e, 0xc1, 0x8e, 0x0d, 0x7c, 0x64, 0xda,
	0x4e, 0xcd, 0xb0, 0x0d, 0x6d, 0x1d, 0xdd, 0x87, 0xbb, 0x53, 0xf4, 0x56, 0xbb, 0x66, 0x3a, 0x56,
	0xe3, 0x69, 0xcb, 0xb0, 0x4f, 0xb0, 0xa9, 0x6d, 0xe4, 0xd8, 0xb4, 0xd9, 0xb6, 0x2c, 0xc7, 0x6a,
	0x57, 0x1b, 0x46, 0xb3, 0xf1, 0x85, 0x21, 0x6c, 0xb5, 0x89, 0x2a, 0xb0, 0x37, 0xc5, 0x66, 0x99,
	0xb6, 0xdd, 0x9c, 0x98, 0x56, 0xdb, 0x42, 0x6f, 0xc0, 0x7e, 0x3e, 0x4f, 0xad, 0x61, 0xd9, 0xd8,
	0xb4, 0x2c, 0xb3, 0xa6, 0x69, 0x39, 0x3a, 0x29, 0x9d, 0xab, 0xd8, 0x34, 0x6c, 0xb3, 0xa6, 0x6d,
	0xe7, 0x18, 0xd2, 0xb0, 0x2c, 0xd3, 0xd6, 0xd0, 0xfc, 0x0d, 0xdb, 0x8d, 0xea, 0x91, 0xb6, 0x83,
	0xee, 0xc2, 0xcd, 0x29, 0xfa, 0xf3, 0x86, 0x5d, 0xaf, 0x61, 0xe3, 0xb9, 0xd1, 0xd4, 0x76, 0x73,
	0xce, 0xb5, 0x66, 0x8a, 0x0d, 0x68, 0xd7, 0xf2, 0xce, 0xfc, 0xa4, 0x2a, 0x76, 0x76, 0x3d, 0x67,
	0x59, 0xdc, 0xb0, 0x8e, 0x9c, 0x27, 0x46, 0xd5, 0x6e, 0x63, 0xed, 0x46, 0xce, 0xce, 0x5b, 0xa6,
	0xfd, 0xbc, 0x8d, 0x8f, 0xb8, 0x6f, 0x18, 0xc7, 0xa6, 0x6d, 0x62, 0x4d, 0xcf, 0xf1, 0xcb, 0x66,
	0xe3, 0x27, 0x27, 0x8d, 0x5a, 0xc3, 0x7e, 0xc1, 0x4f, 0xfb, 0x59, 0xc3, 0xe2, 0xab, 0xdd, 0x9c,
	0x6f, 0x21, 0x19, 0x08, 0x35, 0xed, 0x56, 0x8e, 0x42, 0x6d, 0x6c, 0x54, 0x9b, 0xa6, 0xc3, 0xc3,
	0x4c, 0xbb, 0x3d, 0x9f, 0x2e, 0x1c, 0xe3, 0x4e, 0xce, 0xa9, 0xd7, 0xcc, 0xa6, 0xf9, 0x54, 0x9c,
	0xb6, 0x73, 0x68, 0x34, 0x8d, 0x56, 0xd5, 0xd4, 0xee, 0xe6, 0x9c, 0xfa, 0x33, 0xa3, 0xd9, 0xa8,
	0x19, 0x76, 0x1b, 0x3b, 0x56, 0xb5, 0x8d, 0x4d, 0x6d, 0x0f, 0xdd, 0x83, 0xdb, 0x53, 0x3c, 0x66,
	0xa7, 0x5d, 0xad, 0x27, 0x51, 0x7b, 0x0f, 0x3d, 0x80, 0x7b, 0x73, 0x85, 0x28, 0xa6, 0xfd, 0x9c,
	0x08, 0xb1, 0x6c, 0xe3, 0x48, 0xfe, 0x4f, 0x6b, 0xb4, 0x9e, 0x6a, 0xf7, 0x73, 0xac, 0x87, 0xcd,
	0xe7, 0x06, 0xae, 0x39, 0x1d, 0xe3, 0x45, 0xfb, 0xc4, 0x96, 0x04, 0xad, 0x92, 0xe3, 0x02, 0xd5,
	0xba, 0x59, 0x3d, 0xea, 0xb4, 0x1b, 0x2d, 0x5b, 0x7b, 0x90, 0xa3, 0x2e, 0xf7, 0x4d, 0xe3, 0x98,
	0xaf, 0x87, 0x6d, 0xed, 0x8d, 0x1c, 0x86, 0x23, 0xf3, 0x85, 0x83, 0xdb, 0xb6, 0x0c, 0x85, 0x37,
	0xd1, 0x4d, 0xb8, 0x96, 0x7b, 0x3c, 0x1a, 0x45, 0x77, 0x66, 0xa2, 0xd8, 0xfe, 0xdc, 0x31, 0x31,
	0x6e, 0x63, 0xed, 0xfb, 0xc2, 0xe1, 0xbb, 0x5f, 0xbc, 0xd3, 0x0d, 0x5d, 0x2a, 0xf2, 0xb2, 0xf8,
	0xc5, 0xda, 0x0d, 0xfd, 0x03, 0x2f, 0x7c, 0x2c, 0xbe, 0xe3, 0xc7, 0xd9, 0xdf, 0xcd, 0x2f, 0x57,
	0x05, 0xfc, 0xd1, 0xbf, 0x02, 0x00, 0x00, 0xff, 0xff, 0x57, 0xb6, 0x9a, 0xdd, 0x87, 0x1e, 0x00,
	0x00,
}
